= Notices for Eclipse uProtocol

This content is produced and maintained by the Eclipse uProtocol project.

* Project home: https://projects.eclipse.org/projects/automotive.uprotocol

== Trademarks

Eclipse uProtocol is trademark of the Eclipse Foundation.
Eclipse, and the Eclipse Logo are registered trademarks of the Eclipse Foundation.

== Copyright

All content is the property of the respective authors or their employers.
For more information regarding authorship of content, please consult the
listed source code repository logs.

== Declared Project Licenses

This program and the accompanying materials are made available under the
terms of the or the Apache License, Version 2.0
which is available at https://www.apache.org/licenses/LICENSE-2.0.

SPDX-License-Identifier: Apache-2.0

== Third-party Content

The following are libraries that uProtocol project uses:

* http://cloudevents.io
* http://protobuf.dev

NOTE: Please refer to link:pom.xml[] for more information of library dependencies