= uProtocol Language Library
:toc:
:sectnums:

The key words "*MUST*", "*MUST NOT*", "*REQUIRED*", "*SHALL*", "*SHALL NOT*", "*SHOULD*", "*SHOULD NOT*", "*RECOMMENDED*", "*MAY*", and "*OPTIONAL*" in this document are to be interpreted as described in https://www.rfc-editor.org/info/bcp14[IETF BCP14 (RFC2119 & RFC8174)]

----
SPDX-FileCopyrightText: 2023 Contributors to the Eclipse Foundation

See the NOTICE file(s) distributed with this work for additional
information regarding copyright ownership.

This program and the accompanying materials are made available under
the terms of the Apache License Version 2.0 which is available at
https://www.apache.org/licenses/LICENSE-2.0
 
SPDX-FileType: DOCUMENTATION
SPDX-License-Identifier: Apache-2.0
----

== Overview 

uProtocol Language specific libraries (_libraries_) are written for a given programming language (ex. Java, C++, etc...) to implement the protocol and are the primary library that is used by applications and services (uEs) to communicate with other uEs. The _libraries_ declare the API for the uProtocol Transport Layer (uP-L1) and implement the uProtocol Communication Layer API (uP-L2).


== Requirements

=== Content

[.specitem,oft-sid="req~up-language-api~1",oft-needs="impl,utest"]
--
* *MUST* implement serializers, validators, and builders for the link:../basics/README.adoc[uProtocol data types] using the link:../up-core-api/README.adoc[up-core-api data model].
--

[.specitem,oft-sid="req~up-language-transport-api~1",oft-needs="impl,utest"]
--
* *MUST* declare the language specific link:up-l1/README.adoc[uProtocol Transport Layer interface], such that the interface can be implemented by the transport libraries.
--

[.specitem,oft-sid="req~up-language-comm-api~1",oft-needs="impl,utest"]
--
* *MUST* declare the language specific link:up-l2/README.adoc[uProtocol Communication Layer (uP-L2) API] and provide a default implementation based on the (abstract) Transport Layer API.
--

[.specitem,oft-sid="req~up-language-naming~1",oft-needs="impl,utest"]
--
* *MUST* be named according to pattern `up-[LANGUAGE]`
--

[.specitem,oft-sid="req~up-language-structure~1",oft-needs="impl,utest"]
--
* The top level namespace (package name) *MUST* contain `uprotocol` and *SHOULD* contain `org.eclipse.uprotocol` 
--

[.specitem,oft-sid="req~up-language-documentation~1",oft-needs="impl,utest"]
--
 * *MUST* contain a `README.adoc` that explains how to build and use the library. 
--

=== Test & CI

[.specitem,oft-sid="req~up-language-test~1",oft-needs="impl,utest"]
--
 * *MUST* be able to run the test suite such that merge requests (commits) cannot be merged till tests are passed
--

[.specitem,oft-sid="req~up-language-ci-build~1",oft-needs="impl,utest"]
--
 * *MUST* have CI workflow that verifies pull requests compiles before they can be merged
--

[.specitem,oft-sid="req~up-language-ci-test~1",oft-needs="impl,utest"]
--
 * *SHOULD* cover 100% of all code and specifications defined in <<Content>>
--

[.specitem,oft-sid="req~up-language-ci~1"]
--
 * *SHOULD* have linter for static code analysis as well as a tool that verifies APIs are properly documented
--


=== Build

[.specitem,oft-sid="req~up-language-build-sys~1",oft-needs="impl,utest"]
--
 * *SHOULD* employ an existing build system that is commonly used for the given programming language
--

[.specitem,oft-sid="req~up-language-build-deps~1",oft-needs="impl,utest"]
--
 * *MUST* resolve and include external dependencies as part of the build process only
--

== Class Diagram

.Class Diagram
[#up-libraries]
image:up_libraries.drawio.svg[width=640]