= uProtocol Language Library
:toc:
:sectnums:

The key words "*MUST*", "*MUST NOT*", "*REQUIRED*", "*SHALL*", "*SHALL NOT*", "*SHOULD*", "*SHOULD NOT*", "*RECOMMENDED*", "*MAY*", and "*OPTIONAL*" in this document are to be interpreted as described in https://www.rfc-editor.org/info/bcp14[IETF BCP14 (RFC2119 & RFC8174)]

----
SPDX-FileCopyrightText: 2023 Contributors to the Eclipse Foundation

See the NOTICE file(s) distributed with this work for additional
information regarding copyright ownership.

This program and the accompanying materials are made available under
the terms of the Apache License Version 2.0 which is available at
https://www.apache.org/licenses/LICENSE-2.0
 
SPDX-FileType: DOCUMENTATION
SPDX-License-Identifier: Apache-2.0
----

== Overview

Language specific uProtocol libraries (_the library_) implement the data model defined in link:../basics/README.adoc[uProtocol Basic Types] in a particular programming language like Java, Rust or C/C++. A library also provides helpers for validating data model instances, serializing UUris to a textual representation as well as builders for correctly instantiating more complex data types. Each library includes the language specific declaration of the abstract interfaces defined in uProtocol link:../up-l1/README.adoc[Layer 1] and link:../up-l2/README.adoc[Layer 2].

NOTE: All libraries *MUST* be made available under a permissive (OSS) license like Apache 2.0 or MIT and *MUST* be hosted under the https://github.com/eclipse-uprotocol[Eclipse uProtocol GitHub Organization].

== Source Code Structure

The following sections define the content and structure of these libraries.

* The root namespace (package name) *MUST* be `org.eclipse.uprotocol`
* Modules defined in table <<content>> below *MUST* be implemented in their own folder (namespace)
* Each module *SHOULD* separate the implementation of the specification as defined in table <<folders>> below.


.Module Folders/Namespace
[#folders,width="80%",cols="20%,80%",options="header"]
|===
| Folder | Description

| `validators`
| static methods to validate the data model

| `serializer`
| Any code that is responsible to Serialize and deserialize the data model

| `factory` (or `builder`)
| Factory methods to build the data model per business logic (i.e. to build CloudEvents, UUIDs, etc..)

|===


=== Modules

Modules are packages (folders) that reside under the `src` directory. <<content>> table below lists the required modules.

.SDK Modules
[#content,width="100%",cols="20%,20%,60%",options="header"]
|===
| Folder | Specification |Description

| `uri`
| link:basics/uri.adoc[UUri]
| How things are addressed in uProtocol

| `uuid`
| link:basics/uuid.adoc[UUID]
| Unique ID & timestamp specification 

| `cloudevents`
| link:up-l1/cloudevents.adoc[CloudEvents]
| Specification of how uProtocol data models can be expressed using CloudEvents data model

| `transport`
| link:up-l1/README.adoc[uTransport]
a| uP-L1 Transport Interface & data model.

* *MUST* declare the interface & data model where as link:../upclient.adoc[uProtocol Client Library] implement the said interface.

| `rpc`
| link:up-l2/rpcclient.adoc[uP-L2 RPC Client]
a|APIs used by clients to invoke methods to simplify implementation of the RPC design pattern. 

|===


== Test

 * *SHOULD* include a test suite under the folder `test`
 * *MUST* be able to run the test suite such that merge requests (commits) cannot be merged till tests are passed
  * *SHOULD* cover 100% of all code and specifications defined in <<Source>>


== Build

 * *MUST* be easily built in both a Windows and Linux development environment. Any build requirements (i.e. package dependencies) need to be properly documented in the README
* *MUST* be able to be imported to any wellknown IDE (Eclipse, IntelliJ, VSCode, etc..) and include self contained build system to build the code and dependencies(ex. maven, gradle, clang, soong, etc...).
* *MUST* fetch external dependency libraries as handle build dependencies, *MUST NOT* copy external dependencies
* *MUST NOT* depend on external copyright or copyleft libraries/modules, only permissive licenses such as Apache 2.0, MIT, shall be accepted etc..


== Documentation

 * *MUST* include a main README.adoc file that explains how to build and use the library. 
 * Each module *MUST* also have a README.adoc that explains how to use said module
