= uProtocol Language Library
:toc:
:sectnums:

The key words "*MUST*", "*MUST NOT*", "*REQUIRED*", "*SHALL*", "*SHALL NOT*", "*SHOULD*", "*SHOULD NOT*", "*RECOMMENDED*", "*MAY*", and "*OPTIONAL*" in this document are to be interpreted as described in https://www.rfc-editor.org/info/bcp14[IETF BCP14 (RFC2119 & RFC8174)]

----
SPDX-FileCopyrightText: 2023 Contributors to the Eclipse Foundation

See the NOTICE file(s) distributed with this work for additional
information regarding copyright ownership.

This program and the accompanying materials are made available under
the terms of the Apache License Version 2.0 which is available at
https://www.apache.org/licenses/LICENSE-2.0
 
SPDX-FileType: DOCUMENTATION
SPDX-License-Identifier: Apache-2.0
----

== Overview 

A uProtocol Language specific libraries (_libraries_), are written for a given programming language (ex. Java, C++, etc...) to implement the protocol and are the primary library that is used by applications and services (uEs) to communicate with other uEs. The _libraries_ declare the API for the uProtocol Transport Layer (uP-L1) and implement the uProtocol Communication Layer API (uP-L2).


== Requirements

=== Content

[oft-sid="req~up-language-api~1"]
--
* *MUST* implement serializers, validators, and builders for the link:../basics/README.adoc[uProtocol data types] using the link:../up-core-api/README.adoc[up-core-api data model].
--

[oft-sid="req~up-language-transport-api~1"]
--
* *MUST* declare the language specific link:up-l1/README.adoc[uProtocol Transport Layer interface], such that the interface can be implemented by the transport libraries.
--

[oft-sid="req~up-language-comm-api~1"]
--
* *MUST* provide an implementation of the link:up-l2/README.adoc[uProtocol Communication Layer API].
--

[oft-sid="req~up-language-naming~1"]
--
* *MUST* be named according to pattern `up-[LANGUAGE]`
--

[oft-sid="req~up-language-license~1"]
--
* *MUST* use a permissive (OSS) license like Apache 2.0 or MIT and located in https://github.com/eclipse-uprotocol[Eclipse uProtocol GitHub Organization] that is documented in `LICENSE` file.
--

[oft-sid="req~up-language-legal~1"]
--
* *MUST* contain `CONTRIBUTING.adoc`, `CODE_OF_CONDUCT.adoc`, `SECURITY.adoc` that point to the versions of these files in this project.
--

[oft-sid="req~up-language-legal~2"]
--
* Dependencies *MUST* only be permissive licensed code/libraries (i.e. *MUST NOT* depend on external code that will pollute the license of the library).
--

[oft-sid="req~up-language-structure~1"]
--
* The top level namespace (package name) *MUST* contain `uprotocol` and *SHOULD* contain `org.eclipse.uprotocol` 
--

[oft-sid="req~up-language-documentation~1"]
--
 * *MUST* contain a `README.adoc` that explains how to build and use the library. 
--

=== Test & CI

[oft-sid="req~up-language-test~1"]
--
 * *MUST* be able to run the test suite such that merge requests (commits) cannot be merged till tests are passed
--

[oft-sid="req~up-language-ci~1"]
--
 * *MUST* have workflows that ensures code compiles before the can be merged
--

[oft-sid="req~up-language-ci~2"]
--
 * *SHOULD* cover 100% of all code and specifications defined in <<Source>>
--

[oft-sid="req~up-language-ci~3"]
--
 * *SHOULD* have lint & documentation coverage checks
--


=== Build

[oft-sid="req~up-language-build~1"]
--
 * *MUST* be easily built in both a Windows and Linux development environment.
--

[oft-sid="req~up-language-build~2"]
--
 * *MUST* include self contained build system to build the code and dependencies(ex. maven, gradle, clang, soong, etc...).
--

[oft-sid="req~up-language-build~3"]
--
 * *MUST* fetch and build external dependency libraries, *MUST NOT* copy external dependencies
--

== Class Diagram

.Class Diagram
[#up-libraries]
image:up_libraries.drawio.svg[width=800]