= uProtocol Client Library
:toc:
:sectnums:

The key words "*MUST*", "*MUST NOT*", "*REQUIRED*", "*SHALL*", "*SHALL NOT*", "*SHOULD*", "*SHOULD NOT*", "*RECOMMENDED*", "*MAY*", and "*OPTIONAL*" in this document are to be interpreted as described in https://www.rfc-editor.org/info/bcp14[IETF BCP14 (RFC2119 & RFC8174)]

----
Copyright (c) 2023 General Motors GTO LLC

Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.

SPDX-FileType: DOCUMENTATION
SPDX-FileCopyrightText: 2023 General Motors GTO LLC
SPDX-License-Identifier: Apache-2.0
----

== Overview

uPClient library is the application facing library that uEs use to communicate to a given implementation of uProtocol (ex. up-android, up-zenoh, etc...). The library contains a transport specific implementation of the link:up-l1/README.adoc[uTransport], link:up-l2/rpcclient.adoc[RpcClient], and link:up-l2/rpcserver.adoc[RpcServer] interfaces declared in link:languages.adoc[uProtocol Language Specific Library Specifications]. The library also includes implementation specific client-side implementations of the core uServices uDiscovery, uTwin, and uSubscription.

== Requirements

* *MUST* implement the uProtocol uP-L1 & uP-L2 protocol specific interfaces link:up-l1/README.adoc[uTransport], link:up-l2/rpcclient.adoc[RpcClient], and link:up-l2/rpcserver.adoc[RpcServer]
* *MUST* implement (client-side) uProtocol uP-L3 core uService interfaces link:up-l3/usubscription/v3/README.adoc[uSubscription], link:up-l3/utwin/v3/README.adoc[uTwin], and link:up-l3/udiscovery/v3/README.adoc[uDiscovery]
* *MUST* Follow the naming convention `up-client-[IMPLEMENTATION]-[LANGUAGE]` 

== Class Diagram
<<up-client>> below illustrates how the upClient implements the interfaces that are declared in the language libraries.

.upClient Class Diagram
[#up-client]
image:up_libraries.drawio.svg[width=640]


