= uProtocol Client Library
:toc:
:sectnums:

The key words "*MUST*", "*MUST NOT*", "*REQUIRED*", "*SHALL*", "*SHALL NOT*", "*SHOULD*", "*SHOULD NOT*", "*RECOMMENDED*", "*MAY*", and "*OPTIONAL*" in this document are to be interpreted as described in https://www.rfc-editor.org/info/bcp14[IETF BCP14 (RFC2119 & RFC8174)]

----
SPDX-FileCopyrightText: 2023 Contributors to the Eclipse Foundation

See the NOTICE file(s) distributed with this work for additional
information regarding copyright ownership.

This program and the accompanying materials are made available under
the terms of the Apache License Version 2.0 which is available at
https://www.apache.org/licenses/LICENSE-2.0
 
SPDX-FileType: DOCUMENTATION
SPDX-License-Identifier: Apache-2.0
----

== Overview

uPClient library is the application facing library that uEs use to communicate to a given implementation of uProtocol (ex. up-android, up-zenoh, etc...). The library contains a transport specific implementation of the link:up-l1/README.adoc[uTransport], and link:up-l2/rpcclient.adoc[RpcClient] interfaces declared in link:languages.adoc[uProtocol Language Specific Library Specifications]. The library also includes implementation specific client-side implementations of the core uServices uDiscovery, uTwin, and uSubscription.

== Requirements

* *MUST* implement the uProtocol uP-L1 & uP-L2 protocol specific interfaces link:up-l1/README.adoc[uTransport], and link:up-l2/rpcclient.adoc[RpcClient]
* *MUST* implement (client-side) uProtocol uP-L3 core uService interfaces link:up-l3/usubscription/v3/README.adoc[uSubscription], link:up-l3/utwin/v3/README.adoc[uTwin], and link:up-l3/udiscovery/v3/README.adoc[uDiscovery]
* *MUST* Follow the naming convention `up-client-[IMPLEMENTATION]-[LANGUAGE]` 

== Class Diagram
<<up-client>> below illustrates how the upClient implements the interfaces that are declared in the language libraries.

.upClient Class Diagram
[#up-client]
image:up_libraries.drawio.svg[width=640]


