= uProtocol Client Library
:toc:
:sectnums:

The key words "*MUST*", "*MUST NOT*", "*REQUIRED*", "*SHALL*", "*SHALL NOT*", "*SHOULD*", "*SHOULD NOT*", "*RECOMMENDED*", "*MAY*", and "*OPTIONAL*" in this document are to be interpreted as described in https://www.rfc-editor.org/info/bcp14[IETF BCP14 (RFC2119 & RFC8174)]

----
SPDX-FileCopyrightText: 2023 Contributors to the Eclipse Foundation

See the NOTICE file(s) distributed with this work for additional
information regarding copyright ownership.

This program and the accompanying materials are made available under
the terms of the Apache License Version 2.0 which is available at
https://www.apache.org/licenses/LICENSE-2.0
 
SPDX-FileType: DOCUMENTATION
SPDX-License-Identifier: Apache-2.0
----

== Overview

A uProtocol Client library is the application facing library that uEntities use to interact with other uEntities. The library contains a programminb language and transport protocol specific implementation of the low level link:up-l1/README.adoc[Transport Layer API] and the link:up-l2/rpcclient.adoc[Communication Layer API]. The library also includes implementation specific client-side implementations of the core uServices uDiscovery, uTwin, and uSubscription.

== Requirements

Each uProtocol Client library
[oft-sid="req~up-client-transport-api~1"]
--
* *MUST* provide an implementation of the link:up-l1/README.adoc[uProtocol Transport Layer API].
--

[oft-sid="req~up-client-comm-api~1"]
--
* *MUST* provide an implementation of the link:up-l2/rpcclient.adoc[uProtocol Communication Layer API].
--

[oft-sid="req~up-client-app-api~1"]
--
* *MUST* provide an implementation of the link:up-l3/README.adoc[uProtocol Application Layer API].
--

[oft-sid="req~up-client-naming~1"]
--
* *MUST* be named according to pattern `up-client-[TRANSPORT]-[LANGUAGE]`
--

== Class Diagram
<<up-client>> below illustrates how the upClient implements the interfaces that are declared in the language libraries.

.upClient Class Diagram
[#up-client]
image:up_libraries.drawio.svg[width=640]


