@startuml
'https://plantuml.com/sequence-diagram

' Copyright (c) 2023 General Motors GTO LLC
'
' Licensed to the Apache Software Foundation (ASF) under one
' or more contributor license agreements.  See the NOTICE file
' distributed with this work for additional information
' regarding copyright ownership.  The ASF licenses this file
' to you under the Apache License, Version 2.0 (the
' "License"); you may not use this file except in compliance
' with the License.  You may obtain a copy of the License at
'
'  http://www.apache.org/licenses/LICENSE-2.0
'
' Unless required by applicable law or agreed to in writing,
' software distributed under the License is distributed on an
' "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
' KIND, either express or implied.  See the License for the
' specific language governing permissions and limitations
' under the License.
'
' SPDX-FileCopyrightText: 2023 General Motors GTO LLC
' SPDX-FileType: SOURCE
' SPDX-License-Identifier: Apache-2.0


autonumber

box uDevice #white
	Collections uEs #red
	entity uLDS #orange
	entity uDDS #orange
	entity uCDS #orange
end box
entity CDS #orange

uEs -> uLDS: FinduE(FinduERequest)
note right
<size:14>**FinduERequest:**</size>
""uri"": ""//topic//""
end note

alt Found Locally
uLDS --> uEs: FinduEResponse
note right
<size:14>**FinduEResponse:**</size>
""uris"": {""//topic//"", ""//topic//""}
""result"": {""code"": ""OK""}
end note
|||
else Invalid Argument or Permission Denied
uLDS --> uEs: FinduEResponse
note right
<size:14>**FinduEResponse:**</size>
""result"" : { ""code"": ""INVALID_ARGUMENT | PERMISSION_DENIED"" }
end note
|||
else Remote Lookup Required
uLDS -> uDDS: FinduE(FinduERequest)
alt Success
uDDS --> uLDS: FinduEResponse
note right
<size:14>**FinduEResponse:**</size>
""uris"": {""//topic//"", ""//topic//""}
""result"": {""code"": ""OK""}
end note
uLDS -> uLDS: Cache (per ttl)
uLDS --> uEs: FinduEResponse
note right
<size:14>**FinduEResponse:**</size>
""uris"": {""//topic//"", ""//topic//""}
""result"": {""code"": ""OK""}
end note
|||
else Remote Lookup Required
uDDS -> uCDS: FinduE(FinduERequest)
alt Success
uCDS --> uDDS: FinduEResponse
note right
<size:14>**FinduEResponse:**</size>
""uris"": {""//topic//"", ""//topic//""}
""result"": {""code"": ""OK""}
end note
uDDS -> uDDS: Cache (per ttl)
uDDS --> uLDS: FinduEResponse
uLDS -> uLDS : Cache( per ttl)
uLDS --> uEs : FinduEResponse
note right
<size:14>**FinduEResponse:**</size>
""uris"": {""//topic//"", ""//topic//""}
""result"": {""code"": ""OK""}
end note
|||
else Failure
uDDS --> uLDS: FinduEResponse
note right
<size:14>**FinduEResponse:**</size>
""result"": {""code"": ""INVALID_ARGUMENT | NOT_FOUND | PERMISSION_DENIED""}
end note
uLDS --> uEs: FinduEResponse
end alt

else Not Found
uLDS --> uEs: FinduEResponse
note right
<size:14>**FinduEResponse:**</size>
""result"": {""code"": ""NOT_FOUND""}
end note
end alt

uLDS --> uEs: FinduEResponse
end alt
@enduml