@startuml
'https://plantuml.com/sequence-diagram

' Copyright (c) 2023 General Motors GTO LLC
'
' Licensed to the Apache Software Foundation (ASF) under one
' or more contributor license agreements.  See the NOTICE file
' distributed with this work for additional information
' regarding copyright ownership.  The ASF licenses this file
' to you under the Apache License, Version 2.0 (the
' "License"); you may not use this file except in compliance
' with the License.  You may obtain a copy of the License at
'
'  http://www.apache.org/licenses/LICENSE-2.0
'
' Unless required by applicable law or agreed to in writing,
' software distributed under the License is distributed on an
' "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
' KIND, either express or implied.  See the License for the
' specific language governing permissions and limitations
' under the License.
'
' SPDX-FileCopyrightText: 2023 General Motors GTO LLC
' SPDX-FileType: SOURCE
' SPDX-License-Identifier: Apache-2.0


autonumber

box uDevice1 #white
	Collections uEs #red
	entity LDS #orange
end box
entity CDS #orange

group Local uDevice Query
	uEs -> LDS: FinduE(FinduERequest)
  	note right
			<size:14>**UriRequest:**</size>
			""uri"": ""//topic//""
	end note
	
	alt Found
		LDS --> uEs: FindNodesResponse
		note right
		<size:12>**FindNodesResponse:**</size>
			""nodes"": { //One or more nodes// }
			""status"": {""code"": ""OK""}
		end note
	else Error
 		LDS --> uEs: FindNodesResponse
		note right
		<size:12>**FindNodesResponse:**</size>
			""nodes"": { //Empty Node// }
			""status"": {""code"":  ""INVALID_ARGUMENT | NOT_FOUND | PERMISSION_DENIED""}
		end note
  end alt
end
|||
group Remote uDevice Query
	uEs -> LDS: FindNodes(FindNodesRequest)
	note right
	<size:12>**FindNodesRequest:**</size>
		""uri"":  "up://Device2/uService"
		""depth"": -1
	end note
	LDS -> CDS: FindNodes(FindNodesRequest)
 	alt Found
		CDS --> LDS: FindNodesResponse
		note right
		<size:12>**FindNodesResponse:**</size>
			""nodes"": { //One or more nodes// }
			""status"": {""code"": ""OK""}
		end note
		LDS -> LDS: Cache Node Info (per ttl)
	else NOT FOUND
  		CDS --> LDS: FindNodesResponse
		note right
		<size:12>**FindNodesResponse:**</size>
			""nodes"": { //Empty Node// }
			""status"": {""code"":  ""NOT_FOUND""}
			""ttl"": 432000000 ///* 5 days *///
		end note
		LDS -> LDS: Cache Node Info (per ttl)
	else TIMEOUT
 		note right
		<size:12>**FindNodesResponse:**</size>
			""nodes"": { //Empty Node// }
			""status"": {""code"":  ""DEADLINE_EXCEEDED""}
		end note
 	else ERROR
 		CDS --> LDS: FindNodesResponse
		note right
		<size:12>**FindNodesResponse:**</size>
			""nodes"": { //One or more nodes// }
			""status"": {""code"":  ""INVALID_ARGUMENT | PERMISSION_DENIED""}
		end note
  	end alt
	LDS --> uEs: FindNodesResponse
end
@enduml