@startuml
'https://plantuml.com/sequence-diagram

' SPDX-FileCopyrightText: 2023 Contributors to the Eclipse Foundation
'
' See the NOTICE file(s) distributed with this work for additional
' information regarding copyright ownership.
' 
' This program and the accompanying materials are made available under
' the terms of the Apache License Version 2.0 which is available at
' https://www.apache.org/licenses/LICENSE-2.0
'
' SPDX-FileType: SOURCE
' SPDX-License-Identifier: Apache-2.0

autonumber

box uDevice #white
	Collections uEs #red
	entity LDS #orange
end box
entity CDS #orange

uEs -> LDS: LookupUri(UriRequest)
note right
<size:14>**UriRequest:**</size>
""uri"": ""//topic//""
end note

alt Found Locally
LDS --> uEs: UriResponse
note right
<size:14>**UriRequest:**</size>
""uris"": {""//topic//"", ""//topic//""}
""result"": {""code"": ""OK""}
end note
|||
else Invalid Argument or Permission Denied
LDS --> uEs: UriResponse
note right
<size:14>**UriResponse:**</size>
""result"" : { ""code"": ""INVALID_ARGUMENT | PERMISSION_DENIED"" }
end note
|||
else Remote Lookup Required
LDS -> CDS: LookupUri(UriRequest)
alt Success
CDS --> LDS: UriResponse
note right
<size:14>**UriResponse:**</size>
""uris"": {""//topic//"", ""//topic//""}
""result"": {""code"": ""OK""}
end note
LDS -> LDS: Cache (per ttl)
LDS --> uEs: UriResponse
note right
<size:14>**UriResponse:**</size>
""uris"": {""//topic//"", ""//topic//""}
""result"": {""code"": ""OK""}
end note
else Failure
CDS --> LDS: UriResponse
note right
<size:14>**UriResponse:**</size>
""result"": {""code"": ""INVALID_ARGUMENT | NOT_FOUND | PERMISSION_DENIED""}
end note
LDS --> uEs: UriResponse
end alt

else Not Found
LDS --> uEs: UriResponse
note right
<size:14>**UriResponse:**</size>
""result"": {""code"": ""NOT_FOUND""}
end note
end alt

LDS --> uEs: UriResponse
@enduml