@startuml
'https://plantuml.com/sequence-diagram

' SPDX-FileCopyrightText: 2023 Contributors to the Eclipse Foundation
'
' See the NOTICE file(s) distributed with this work for additional
' information regarding copyright ownership.
' 
' This program and the accompanying materials are made available under
' the terms of the Apache License Version 2.0 which is available at
' https://www.apache.org/licenses/LICENSE-2.0
'
' SPDX-FileType: SOURCE
' SPDX-License-Identifier: Apache-2.0


autonumber

box uDevice2 #white
    actor CDS #orange
end box
box uDevice1 #white
	entity LDS as DS #orange
	actor uApp #red
endbox
group uApp to LDS Registration
	uApp ->DS: RegisterForNotifications(\nNotificationsRequest)
	note right
		<size:12>**NotificationsRequest:**</size>
		""uris"": [ "up://Device1/uService/1", "up://Device2/uService/1"]
		""observer"": { ""uri": "up://Device1/uApp/1" }
	end note
	alt Success
		DS -> DS: Save NotificationRequest
		DS --> uApp: Status
		note right
			<size:12>**Status:**</size>
			""code"": ""OK""
		end note
	else Error
	 	DS --> uApp: Status
		note right
			<size:12>**Status:**</size>
			""code"": ""INVALID_ARGUMENT |""
			""NOT_FOUND | PERMISSION_DENIED""
		end note
	end alt
end
|||
group LDS to CDS Registration
DS -> CDS: RegisterForNotifications(\nNotificationsRequest)
note right
	<size:12>**NotificationsRequest:**</size>
	""uris"": "up://Device2/uSerivce/1"
	""observer"": { ""uri"": "up://Device1/core.udiscovery/2" }
	}
end note
alt Success
	CDS -> CDS: Save NotificationRequest
	CDS --> DS: Status
	note right
		<size:12>**Status:**</size>
		""code"": ""OK""
	end note
else Error
 	CDS --> DS: Status
	note right
		<size:12>**Status:**</size>
		""code"": ""INVALID_ARGUMENT |""
		""NOT_FOUND | PERMISSION_DENIED""
	end note
end alt
end

@enduml