@startuml
'https://plantuml.com/sequence-diagram

' Copyright (c) 2023 General Motors GTO LLC
'
' Licensed to the Apache Software Foundation (ASF) under one
' or more contributor license agreements.  See the NOTICE file
' distributed with this work for additional information
' regarding copyright ownership.  The ASF licenses this file
' to you under the Apache License, Version 2.0 (the
' "License"); you may not use this file except in compliance
' with the License.  You may obtain a copy of the License at
'
'  http://www.apache.org/licenses/LICENSE-2.0
'
' Unless required by applicable law or agreed to in writing,
' software distributed under the License is distributed on an
' "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
' KIND, either express or implied.  See the License for the
' specific language governing permissions and limitations
' under the License.
'
' SPDX-FileCopyrightText: 2023 General Motors GTO LLC
' SPDX-FileType: SOURCE
' SPDX-License-Identifier: Apache-2.0


autonumber

box uDevice2 #white
    actor CDS #orange
end box
box uDevice1 #white
	entity LDS as DS #orange
	actor uApp #red
endbox
group uApp to LDS Registration
	uApp ->DS: RegisterForNotifications(\nNotificationsRequest)
	note right
		<size:12>**NotificationsRequest:**</size>
		""uris"": [ "up://Device1/uService/1", "up://Device2/uService/1"]
		""observer"": { ""uri": "up://Device1/uApp/1" }
	end note
	alt Success
		DS -> DS: Save NotificationRequest
		DS --> uApp: Status
		note right
			<size:12>**Status:**</size>
			""code"": ""OK""
		end note
	else Error
	 	DS --> uApp: Status
		note right
			<size:12>**Status:**</size>
			""code"": ""INVALID_ARGUMENT |""
			""NOT_FOUND | PERMISSION_DENIED""
		end note
	end alt
end
|||
group LDS to CDS Registration
DS -> CDS: RegisterForNotifications(\nNotificationsRequest)
note right
	<size:12>**NotificationsRequest:**</size>
	""uris"": "up://Device2/uSerivce/1"
	""observer"": { ""uri"": "up://Device1/core.udiscovery/2" }
	}
end note
alt Success
	CDS -> CDS: Save NotificationRequest
	CDS --> DS: Status
	note right
		<size:12>**Status:**</size>
		""code"": ""OK""
	end note
else Error
 	CDS --> DS: Status
	note right
		<size:12>**Status:**</size>
		""code"": ""INVALID_ARGUMENT |""
		""NOT_FOUND | PERMISSION_DENIED""
	end note
end alt
end

@enduml