@startuml
'https://plantuml.com/sequence-diagram

' Copyright (c) 2023 General Motors GTO LLC
'
' Licensed to the Apache Software Foundation (ASF) under one
' or more contributor license agreements.  See the NOTICE file
' distributed with this work for additional information
' regarding copyright ownership.  The ASF licenses this file
' to you under the Apache License, Version 2.0 (the
' "License"); you may not use this file except in compliance
' with the License.  You may obtain a copy of the License at
'
'  http://www.apache.org/licenses/LICENSE-2.0
'
' Unless required by applicable law or agreed to in writing,
' software distributed under the License is distributed on an
' "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
' KIND, either express or implied.  See the License for the
' specific language governing permissions and limitations
' under the License.
'
' SPDX-FileCopyrightText: 2023 General Motors GTO LLC
' SPDX-FileType: SOURCE
' SPDX-License-Identifier: Apache-2.0

autonumber

box Device2 #white
	actor CDS #orange
endbox
box Device1 #white
	entity LDS as DS #orange
	entity uService as US #blue
	actor uApp #red
endbox

US -> DS: UpdateNode(\nUpdateNodeRequest)
note right
	<size:12>**UpdateNodeRequest:**</size>
	""node"" { //Changed Info//	}
	""ttl"": -1
end note
DS -> DS: Update Node
note right
 	<size:12>**Node Metadata:**</size>
	save //""ttl""//
	//""last_updated""//=//current time//
 	//""inactive""//=""false""
end note
DS --> US: Status
note right
	<size:12>**Status:**</size>
	""code"": ""OK""
end note
|||
loop Notify Observers
	DS -[#0000FF]-\ uApp: <font color=blue>Notification</font>
	note right
		<size:12>**Notification:**</size>
		""uri"" : //uri of changed node//
		""operation"": ""UPDATE""
		""ttl"": -1
	end note
	DS -[#0000FF]-\ CDS: <font color=blue>Notification</font>

	opt Fetch Updated Node
		CDS -> DS: FindNodes(FindNodesRequest)
 		note right
			<size:12>**FindNodesRequest:**</size>
			""uri"": //uri of the changed node//
			""depth"": -1
		end note
		DS --> CDS: FindNodesResponse
		note right
			<size:12>**FindNodesResponse:**</size>
			""nodes"": { //updated node// }
			""status"": {""code"": ""OK""}
		end note
	end opt
end loop
@enduml