@startuml me_advertise
'https://plantuml.com/sequence-diagram

' SPDX-FileCopyrightText: 2023 Contributors to the Eclipse Foundation
'
' See the NOTICE file(s) distributed with this work for additional
' information regarding copyright ownership.
' 
' This program and the accompanying materials are made available under
' the terms of the Apache License Version 2.0 which is available at
' https://www.apache.org/licenses/LICENSE-2.0
'
' SPDX-FileType: SOURCE
' SPDX-License-Identifier: Apache-2.0
autonumber
box mDevice
	entity uE #red 
	entity SOMEIPSD as DS #orange
end box
box uDevice
	entity SOMEIPBridge as Bridge #orange
	entity uDDS #brown
end box

uE --\DS: Start|Stop Service
DS -[#orange]-\ Bridge: OfferService |\n StopOfferService
Bridge ->Bridge: Convert to FindNodesRequest
Bridge ->uDDS: FindNodes(FindNodesRequest)
uDDS -->Bridge: FindNodesResponse
Bridge ->Bridge: Create UpdateNodeRequest
Bridge ->uDDS: UpdateNode(UpdateNodeRequest)
uDDS -->Bridge: Status
@enduml