@startuml me_disvover_ue
'https://plantuml.com/sequence-diagram

' SPDX-FileCopyrightText: 2023 Contributors to the Eclipse Foundation
'
' See the NOTICE file(s) distributed with this work for additional
' information regarding copyright ownership.
' 
' This program and the accompanying materials are made available under
' the terms of the Apache License Version 2.0 which is available at
' https://www.apache.org/licenses/LICENSE-2.0
'
' SPDX-FileType: SOURCE
' SPDX-License-Identifier: Apache-2.0
autonumber
skinparam BoxPadding 40

box mDevice #white
	entity SOMEIPSD as DS #orange
end box

box uDevice #white 
	entity SOMEIPBridge as Bridge #orange
	entity uDDS #brown
end box

DS -[#orange]-\ Bridge: OfferService
Bridge ->Bridge: Convert to AddNodeRequest
Bridge ->uDDS: FindNodes(FindNodesRequest)
uDDS -->Bridge: FindNodesResponse
Bridge -> Bridge: Convert to OfferService
Bridge -[#orange]-\ DS: OfferService
@enduml
