@startuml subscribe_m_2_u
'https://plantuml.com/sequence-diagram

' SPDX-FileCopyrightText: 2023 Contributors to the Eclipse Foundation
'
' See the NOTICE file(s) distributed with this work for additional
' information regarding copyright ownership.
' 
' This program and the accompanying materials are made available under
' the terms of the Apache License Version 2.0 which is available at
' https://www.apache.org/licenses/LICENSE-2.0
'
' SPDX-FileType: SOURCE
' SPDX-License-Identifier: Apache-2.0
autonumber

box mDevice #white
	actor mE #red
end box
box uDevice #white
	entity SOMEIPBridge as Bridge #orange
  	entity uSubscription as SM1 #brown
 end box

mE -[#orange]> Bridge: SubscribeEventgroup()
Bridge -> Bridge: Create SubscriptionRequest
Bridge -> SM1: Subscribe(SubscriptionRequest)
note right
 	<size:12>**SubscriptionRequest:**</size> 
	""topic:"" { ""uri"": ""//topic//"" }  
	""subscriber"": { ""uri"": "up://mDevice/0/2" }
end note
SM1 --> Bridge: SubscriptionResponse
Bridge -> Bridge: Create SubscribeEventgroupAck|Nack()
Bridge -[#orange]-> mE: SubscribeEventgroupAck|Nack()
@enduml