@startuml unsubscribe_m_2_u
'https://plantuml.com/sequence-diagram

' SPDX-FileCopyrightText: 2023 Contributors to the Eclipse Foundation
'
' See the NOTICE file(s) distributed with this work for additional
' information regarding copyright ownership.
' 
' This program and the accompanying materials are made available under
' the terms of the Apache License Version 2.0 which is available at
' https://www.apache.org/licenses/LICENSE-2.0
'
' SPDX-FileType: SOURCE
' SPDX-License-Identifier: Apache-2.0

autonumber

box mDevice #white
	actor mE #red
end box
box uDevice #white
	entity SOMEIPBridge as Bridge #orange
  	entity uSubscription as SM1 #brown
 end box

mE -[#orange]> Bridge: StopSubscribeEventgroup()
Bridge -> Bridge: Create UnsubscribeRequest
Bridge -> SM1: Unsubscribe(UnsubscribeRequest)
note right
 	<size:12>**UnsubscriptionRequest:**</size> 
	""topic:"" { ""uri"": ""//topic//"" }  
	""subscriber"": { ""uri"": "up://mDevice/0/2" }
end note
SM1 --> Bridge: Status
note right
	<size:12>**Status:**</size>
	""code"": ""OK""
end note
@enduml