= uProtocol Error Model (UStatus)
:toc:
:sectnums:

The key words "*MUST*", "*MUST NOT*", "*REQUIRED*", "*SHALL*", "*SHALL NOT*", "*SHOULD*", "*SHOULD NOT*", "*RECOMMENDED*", "*MAY*", and "*OPTIONAL*" in this document are to be interpreted as described in https://www.rfc-editor.org/info/bcp14[IETF BCP14 (RFC2119 & RFC8174)]

----
SPDX-FileCopyrightText: 2023 Contributors to the Eclipse Foundation

See the NOTICE file(s) distributed with this work for additional
information regarding copyright ownership.

This program and the accompanying materials are made available under
the terms of the Apache License Version 2.0 which is available at
https://www.apache.org/licenses/LICENSE-2.0
 
SPDX-FileType: DOCUMENTATION
SPDX-License-Identifier: Apache-2.0
----

uProtocol supports invoking operations on (remote) service providers by means of _Remote Procedure Calls_ (RPC).
In order to do so, a client uEntity (service consumer) sends an xref:uattributes.adoc#request-attributes[RPC Request message] to the service provider and waits for a corresponding xref:uattributes.adoc#response-attributes[RPC Response message] which conveys the outcome of the invocation of the operation.

In general, an RPC can succeed or fail from the service consumer's point of view. In the former case, the response message contains the data/information that is the result of successfully processing the input data conveyed in the request message. In the latter case, the response message contains details regarding the reason why processing of the request message has failed.

uProtocol follows Google's https://cloud.google.com/apis/design/errors[protocol-agnostic API error model]. In particular, a service consumer *MUST* consider an RPC as _failed_ if the `commstatus` property contained in the xref:uattributes.adoc#response-attributes[response message attributes] has a value other than `OK`. In that case the response message's payload *MUST* be a serialized xref:../up-core-api/uprotocol/v1/ustatus.proto[UStatus] containing detail information about the reason for failure.

== Service Interface Design

uProtocol uses https://protobuf.dev/programming-guides/proto3/#services[Protobuf] for defining a service provider's operations. Based on the error model defined above, the _Protobuf Message_ defined/used as the response of an operation *SHOULD* only contain the data/information that represents the outcome of _successful_ execution of the operation.

If an operation does not return any data/information on successful execution, the operation *SHOULD* use a dedicated empty response Message:

[example]
----
service HvacService {
  rpc SetTemperature(SetTemperatureRequest) returns (SetTemperatureResponse);
}

message SetTemperatureRequest {
    uint32 temperature = 1;
}

message SetTemperatureResponse {}
----

A service consumer invoking this operation will then receive a `UMessage` with an empty payload.

== Service Implementation

In case of _successful_ execution of a service operation, a service provider:

* *MUST* put the operation's response Protobuf Message into the response xref:umessage.adoc[`UMessage`]'s `payload`
* *MAY* set `commstatus` attribute (of the response message) to value `UCode.OK` to indicate successful execution. If the `commstatus` attribute is not set, it is assumed to be `UCode.OK`.

In case of _erroneous_ execution a service provider:

* *MUST* set the `commstatus` attribute of the response xref:umessage.adoc[`UMessage`] to the appropriate xref:../up-core-api/uprotocol/v1/ucode.proto[`UCode`] value indicating the failure reason. 
* *SHOULD* populate the response xref:umessage.adoc[`UMessage`] `payload` with xref:../up-core-api/uprotocol/v1/ustatus.proto[`UStatus`] message that contains additional failure information (ex. message, details). The `UCode` from `commstatus` *MUST* be the same as that of `UStatus`.
