= QoS
:sectnums:

The key words "*MUST*", "*MUST NOT*", "*REQUIRED*", "*SHALL*", "*SHALL NOT*", "*SHOULD*", "*SHOULD NOT*", "*RECOMMENDED*", "*MAY*", and "*OPTIONAL*" in this document are to be interpreted as described in https://www.rfc-editor.org/info/bcp14[IETF BCP14 (RFC2119 & RFC8174)]

----
SPDX-FileCopyrightText: 2023 Contributors to the Eclipse Foundation

See the NOTICE file(s) distributed with this work for additional
information regarding copyright ownership.

This program and the accompanying materials are made available under
the terms of the Apache License Version 2.0 which is available at
https://www.apache.org/licenses/LICENSE-2.0
 
SPDX-FileType: DOCUMENTATION
SPDX-License-Identifier: Apache-2.0
----

uProtocol allows messages to be exchanged between uEntities on the same and/or different devices. The network bandwidth and/or CPU cycles available for performing this task may be limited, though. uProtocol therefore supports priority based message processing at the xref:../up-l1/README.adoc[Transport] and xref:../up-l2/README.adoc[Communication Layer] based on https://datatracker.ietf.org/doc/html/rfc4594[RFC4594 - Configuration Guidelines for DiffServ Service Classes].

For this purpose, each xref:umessage.adoc[UMessage] is assigned to one of the following service classes:

.QoS Classifications
[cols="1,4,3"]
|===
|Class |Description |Typical Use Case

|*CS0* |Low Priority. No bandwidth assurance |File Transfer
|*CS1* |Standard, undifferentiated application |General (unclassified)
|*CS2* |Operations, Administration, and Management |Streamer messages (sub, connect, etc…)
|*CS3* |Multimedia streaming |Video Streaming
|*CS4* |Real-time interactive |High priority (RPC events)
|*CS5* |Important |Signaling
|*CS6* |Safety Critical |Network control
|===

These classes are represented by the values of the link:../up-core-api/uprotocol/v1/uattributes.proto[UPriority protobuf enum].

[#default-priority]
* A UMessage *MAY* be assigned _explicitly_ to a service class by setting the message's xref:uattributes.adoc#common-attributes[`priority`] property to the desired value. If the property is not set, the UMessage belongs to class `CS1` by default.
* link:../upclient.adoc[uProtocol Client Libraries] *SHOULD* map the message's service class to a corresponding mechanism of the underlying transport protocol, if available.
