= uProtocol Attributes (UAttributes)
:toc: preamble
:sectnums:
:stem: latexmath

The key words "*MUST*", "*MUST NOT*", "*REQUIRED*", "*SHALL*", "*SHALL NOT*", "*SHOULD*", "*SHOULD NOT*", "*RECOMMENDED*", "*MAY*", and "*OPTIONAL*" in this document are to be interpreted as described in https://www.rfc-editor.org/info/bcp14[IETF BCP14 (RFC2119 & RFC8174)]

----
SPDX-FileCopyrightText: 2023 Contributors to the Eclipse Foundation

See the NOTICE file(s) distributed with this work for additional
information regarding copyright ownership.

This program and the accompanying materials are made available under
the terms of the Apache License Version 2.0 which is available at
https://www.apache.org/licenses/LICENSE-2.0
 
SPDX-FileType: DOCUMENTATION
SPDX-License-Identifier: Apache-2.0
----

== Overview 

UAttributes contain meta data describing a particular message's purpose, content and processing requirements.

[#data-model-definition]
== Data Model

The diagram below shows the UAttributes class and its properties using UML2 notation.

NOTE: The UCode, UUri and UUID classes are defined in detail in xref:error_model.adoc[Error Model Specification], xref:uri.adoc[UUri Specification] and xref:uuid.adoc[UUID Specification] respectively.

.UAttributes Data Model
[#uattributes-data-model]
[mermaid]
ifdef::env-github[[source,mermaid]]
----
classDiagram

class UAttributes {
  id: UUID
  source: UUri
  sink: UUri [0..1]
  ttl : UInt32 = 0
  commstatus: UCode [0..1]
  permissionLevel: UInt32 [0..1]
  requestId: UUID [0..1]
  token: String [0..1]
  traceparent: String [0..1]
}

class UMessageType {
  <<Enumeration>>
  Publish
  Notification
  RpcRequest
  RpcResponse
}

class UPriority {
  <<Enumeration>>
  CS0
  CS1
  CS2
  CS3
  CS4
  CS5
  CS6
}

class UPayloadFormat {
  <<Enumeration>>
  Unspecified
  ProtobufWrappedInAny
  Protobuf
  Json
  SomeIp
  SomeIpTlv
  Raw
  Text
  SHM
}

UAttributes o-- UMessageType : type
UAttributes o-- UPriority : priority
UAttributes o-- "0..1" UPayloadFormat : payloadFormat
----

Each xref:../languages.adoc[uProtocol Language Library]

[.specitem,oft-sid="req~uattributes-data-model-impl~2",oft-needs="impl,utest",oft-tags="LanguageLibrary"]
--
* *MUST* implement the <<uattributes-data-model>> using the language specific type system.
--

[.specitem,oft-sid="req~uattributes-data-model-proto~1",oft-needs="impl,utest",oft-tags="LanguageLibrary"]
--
* *MUST* support writing and reading of an instance of the <<uattributes-data-model>> to/from a protobuf as defined in link:../up-core-api/uprotocol/v1/uattributes.proto[uattributes.proto].
--

[#uattributes-message-types]
uProtocol defines four types of messages:

.Message Types
[cols="1,5"]
|===
|Type |Description

|Publish
|A message that is used to notify all interested consumers about an event that has occurred.

|Notification
|A message that is used to inform a specific consumer about an event that has occurred.

|RpcRequest
|A message that is used by a service consumer to invoke one of a service provider's methods with some input data, expecting the service provider to reply with a response message.

|RpcResponse
|A message that is used by a service provider to send the outcome of processing a request message
from a service consumer.
|===

Each type of message is described by a set of mandatory and optional attributes.

[#common-attributes]
== Common Message Attributes

The following table defines attributes that are used for all message types:

[%autowidth]
|===
|Name |Type |Mandatory | Default Value | Description

|`type`
|<<uattributes-message-types, UMessageType>>
|yes
|none
|The message type.

|`id`
|xref:uuid.adoc[UUID]
|yes
|none
a|
[.specitem,oft-sid="dsn~up-attributes-id~1",oft-needs="impl,utest",oft-tags="LanguageLibrary"]
--
Every message *MUST* have a unique message identifier. The timestamp contained in the UUID is used as the message's creation time.
--

|`priority`
|xref:upriority.adoc[UPriority]
|yes
|xref:upriority.adoc#default-priority[default priority]
a|
The level of priority that this message should be processed/delivered with.

|`ttl`
|`UInt32`
|yes
a|`0`
a|
The amount of time (in milliseconds) after which this message is no longer delivered/processed.
[.specitem,oft-sid="dsn~up-attributes-ttl-timeout~1",oft-needs="impl,utest",oft-tags="TransportLayerImpl"]
--
A consumer *MUST NOT* process an expired message. A message is expired if the TTL is > `0` and the consumer's current time is _after_ the message's creation time _plus_ its TTL:

stem:[expired := t_{current} > t_{id} + ttl]
--
[.specitem,oft-sid="dsn~up-attributes-ttl~1",oft-needs="impl,utest",oft-tags="TransportLayerImpl"]
--
A consumer *MUST NOT* consider a message expired if it has a TTL value of `0`.
--

|`traceparent`
|https://w3c.github.io/trace-context/#traceparent-header[W3C Trace Context Level 3, traceparent]
|no
|none

a|
A tracing identifier to use for correlating messages across the system, intended to be compatible with https://github.com/cloudevents/spec/blob/main/cloudevents/extensions/distributed-tracing.md[CloudEvents distributed tracing extension].

[.specitem,oft-sid="dsn~up-attributes-traceparent~1",oft-needs="impl,utest",oft-tags="LanguageLibrary"]
--
The traceparent *MUST* either be empty or contain a value as defined by https://w3c.github.io/trace-context/#traceparent-header[W3C Trace Context Level 3].
--


|`payloadFormat`
|<<payload-format,UPayloadFormat>>
|no
|none
a|The format of the payload (data).
[.specitem,oft-sid="dsn~up-attributes-payload-format~2",oft-needs="impl,utest",oft-tags="LanguageLibrary"]
--
The payload format *MUST* be empty if the message has no payload, otherwise it *MUST NOT* be empty.
--

|===

[#publish-attributes]
== Publish Message Attributes

The following table defines attributes that are used for publish messages in addition to the common attributes:

[%autowidth]
|===
|Attribute |Type |Mandatory |Default Value| Description

|`type`
|<<uattributes-message-types, UMessageType>>
|yes
a|
[.specitem,oft-sid="dsn~up-attributes-publish-type~1",oft-needs="impl,utest",oft-tags="LanguageLibrary"]
--
`Publish` (fixed)
--
|The message type.

|`source`
|xref:uri.adoc[UUri]
|yes
|none
a|The topic that this message is published to.

[.specitem,oft-sid="dsn~up-attributes-publish-source~2",oft-needs="impl,utest",oft-tags="LanguageLibrary"]
--
The topic (source) UUri of a Publish message *MUST* have its `resource_id` set to a value in range `[0x8000, 0xFFFE]`.
The topic UUri *MUST NOT* contain any wildcard values in any of its fields.
--

|`sink`
|xref:uri.adoc[UUri]
|no
|none
a|

[.specitem,oft-sid="dsn~up-attributes-publish-sink~2",oft-needs="impl,utest",oft-tags="LanguageLibrary"]
--
A xref:../up-l2/dispatchers/README.adoc#dispatcher-types[uStreamer] *MAY* set the `sink` property of a Publish message to indicate to an underlying transport implementation the authority of remote uEntities that have subscribed to the message's topic. Any such UUri

* *MUST* contain a non-empty _authority_name_, and
* *MUST* contain wildcard values for all of the UUri's other fields.
--
|===

[#notification-attributes]
== Notification Message Attributes

The following table defines attributes that are used for notification messages in addition to the common attributes:

[%autowidth]
|===
|Attribute |Type |Mandatory |Default Value| Description

|`type`
|<<uattributes-message-types, UMessageType>>
|yes
a|
[.specitem,oft-sid="dsn~up-attributes-notification-type~1",oft-needs="impl,utest",oft-tags="LanguageLibrary"]
--
`Notification` (fixed)
--
|The message type.

|`source`
|xref:uri.adoc[UUri]
|yes
|none
a|
A xref:uri.adoc[UUri] representing the component that this notification originates from.

[.specitem,oft-sid="dsn~up-attributes-notification-source~2",oft-needs="impl,utest",oft-tags="LanguageLibrary"]
--
The origin (source) UUri of a Notification message *MUST* have its `resource_id` set to a value in range `[0x8000, 0xFFFE]`.
The origin UUri *MUST NOT* contain any wildcard values in any of its fields.
--

|`sink`
|xref:uri.adoc[UUri]
|yes
|none
a|A xref:uri.adoc[UUri] representing the destination of this notification.

[.specitem,oft-sid="dsn~up-attributes-notification-sink~2",oft-needs="impl,utest",oft-tags="LanguageLibrary"]
--
The destination (sink) UUri of a Notification message *MUST* have its `resource_id` set to `0`.
The destination UUri *MUST NOT* contain any wildcard values in any of its fields.
--

|===

[#request-attributes]
== RPC Request Message Attributes

The following table defines attributes that are used for RPC request messages in addition to the common attributes:

[%autowidth]
|===
|Attribute |Type |Mandatory |Default Value|Description

|`type`
|<<uattributes-message-types, UMessageType>>
|yes
a|
[.specitem,oft-sid="dsn~up-attributes-request-type~1",oft-needs="impl,utest",oft-tags="LanguageLibrary"]
--
`RpcRequest` (fixed)
--
|The message type.

|`source`
|xref:uri.adoc[UUri]
|yes
|none
a|The xref:uri.adoc[UUri] that the service consumer expects to receive the response message at.

[.specitem,oft-sid="dsn~up-attributes-request-source~2",oft-needs="impl,utest",oft-tags="LanguageLibrary"]
--
The reply-to (source) UUri of an RPC Request message *MUST* have its `resource_id` set to `0`.
The reply-to UUri *MUST NOT* contain any wildcard values in any of its fields.
--

|`sink`
|xref:uri.adoc[UUri]
|yes
|none
a|A xref:uri.adoc[UUri] identifying the service provider's method to invoke.

[.specitem,oft-sid="dsn~up-attributes-request-sink~2",oft-needs="impl,utest",oft-tags="LanguageLibrary"]
--
The invoked method (sink) UUri of an RPC Request message *MUST* have its `resource_id` set to a value in range `[0x0001, 0x7FFF]`.
The invoked method UUri *MUST NOT* contain any wildcard values in any of its fields.
--

|`priority`
|xref:upriority.adoc[UPriority]
|yes
a|`CS4`
a|The xref:upriority.adoc[level of priority] that this message should be processed/delivered with.

[.specitem,oft-sid="dsn~up-attributes-request-priority~1",oft-needs="impl,utest",oft-tags="LanguageLibrary"]
--
The priority of an RPC Request message *MUST* be set to `CS4` or higher.
--


|`ttl`
|`UInt32`
|yes
|none
a|The amount of time (in milliseconds) after which this request message should no longer be delivered to or processed by a service provider.

[.specitem,oft-sid="dsn~up-attributes-request-ttl~1",oft-needs="impl,utest",oft-tags="LanguageLibrary"]
--
The TTL of an RPC Request message *MUST* be set to a value > 0.
--

|`permissionLevel`
|`UInt32`
|no
|none
a|The service consumer's permission level.

[.specitem,oft-sid="dsn~up-attributes-permission-level~1",oft-needs="impl,utest",oft-tags="LanguageLibrary"]
--
The permission level of an RPC Request message *MUST* be empty or contain a valid permission level as defined in xref:permissions.adoc#_code_based_access_permissions_caps[Code-Based uEntity Access Permissions (CAPs)].
--

|`token`
|`String`
|no
|none
a|The service consumer's access token.

[.specitem,oft-sid="dsn~up-attributes-request-token~1",oft-needs="impl,utest",oft-tags="LanguageLibrary"]
--
The access token of an RPC Request message *MUST* be empty or contain a token as defined in xref:permissions.adoc#_token_based_access_permissionstaps[Token-Based uEntity Access Permissions (TAPs)].
--

|===

[#response-attributes]
== RPC Response Message Attributes

The following table defines attributes that are used for RPC response messages in addition to the common attributes:

[%autowidth]
|===
|Attribute |Type |Mandatory |Default Value| Description

|`type`
|<<uattributes-message-types, UMessageType>>
|yes
a|
[.specitem,oft-sid="dsn~up-attributes-response-type~1",oft-needs="impl,utest",oft-tags="LanguageLibrary"]
--
`RpcResponse` (fixed)
--
|The message type.

|`source`
|xref:uri.adoc[UUri]
|yes
|none
a|The xref:uri.adoc[UUri] identifying the method that has been invoked and which this message is the outcome of.

[.specitem,oft-sid="dsn~up-attributes-response-source~2",oft-needs="impl,utest",oft-tags="LanguageLibrary"]
--
The invoked method (source) UUri of an RPC Response message *MUST* have its `resource_id` set to a value in range `[0x0001, 0x7FFF]`.
The invoked method UUri *MUST NOT* contain any wildcard values in any of its fields.
--

|`sink`
|xref:uri.adoc[UUri]
|yes
|none
a|The xref:uri.adoc[UUri] that the service consumer expects to receive this response message at.

[.specitem,oft-sid="dsn~up-attributes-response-sink~2",oft-needs="impl,utest",oft-tags="LanguageLibrary"]
--
The reply-to (sink) UUri of an RPC Response message *MUST* have its `resource_id` set to `0`.
The reply-to UUri *MUST NOT* contain any wildcard values in any of its fields.
--

|`requestId`
|xref:uuid.adoc#data-model-definition[UUID]
|yes
a|
[.specitem,oft-sid="dsn~up-attributes-response-correlation-id~1",oft-needs="impl,utest",oft-tags="ServiceProvider"]
--
*MUST* be set to the value of the `id` property of the request message that this is the response to.
--
|The identifier of the request message that this response message is the outcome of.

|`priority`
|xref:upriority.adoc[UPriority]
|yes
a|
[.specitem,oft-sid="dsn~up-attributes-response-priority~1",oft-needs="impl,utest",oft-tags="ServiceProvider"]
--
*MUST* be the same value as that of the corresponding request message's `priority` attribute.
--
|The xref:upriority.adoc[level of priority] that this message should be processed/delivered with. 


|`ttl`
|`UInt32`
|yes
a|
[.specitem,oft-sid="dsn~up-attributes-response-ttl~1",oft-needs="impl,utest",oft-tags="ServiceProvider"]
--
*MUST* be the same value as that of the corresponding request message's `ttl` attribute.
--
|The amount of time (in milliseconds) after which this response message should no longer be delivered to or processed by the service consumer.

|`commstatus`
|xref:error_model.adoc#data-model-definition[UCode]
|yes
a|`UCode.Ok`
a|The outcome of the RPC. `UCode.Ok` indicates successful invocation of the operation. All other values indicate that invocation was unsuccessful. The concrete value indicates the type of error that has occurred. The message's payload may contain additional information about the error.

|===

[#payload-format]
== Payload Format

The following table provides an overview of the payload formats supported by uProtocol.

[%autowidth]
|===
|UPayloadFormat |MIME Type |Payload encoding

| `Unspecified`
| N/A
| The payload format is unknown. Clients will need to have gained knowledge about the concrete encoding and semantics of the payload by means of an out-of-band mechanism.


|`ProtobufWrappedInAny`
|`application/x-protobuf`
a|The network byte order serialization of a `google.protobuf.Any` structure that contains the payload itself along with the schema URI indicating the (protobuf) type of the payload.

**Note:** Using this payload format allows receivers of messages to determine the type of the payload from the schema URI and deserialize it accordingly. However, it also adds some overhead to the message size due to the additional `google.protobuf.Any` wrapper.

|`Protobuf`
|https://www.iana.org/assignments/media-types/application/protobuf[application/protobuf]
a|The network byte order serialization of the protobuf structure representing the payload data.

**Note:** Using this payload format requires that receivers of messages know the type of the payload in advance, as it is not included in the message itself. This can be achieved through out-of-band mechanisms or by using a predefined schema.

|`Json`
|https://www.iana.org/assignments/media-types/application/json[application/json]
|The network byte order UTF-8 encoding of a JSON structure representing the payload data.

|`SomeIp`
|`application/x-someip`
|The network byte order serialization of SOME/IP payload data as defined in [Open SOME/IP Specification, Section 5.4](https://some-ip.com/open-someip-specification/open_someip_specification_2025-12.pdf).

|`SomeIpTlv`
|`application/x-someip_tlv`
|The network byte order serialization of SOME/IP payload data using the (optional) TLV encoding as defined in [SOME/IP Protocol Specification, Section 5.1.3.3](https://www.autosar.org/fileadmin/standards/R25-11/FO/AUTOSAR_FO_PRS_SOMEIPProtocol.pdf).

|`Raw`
|https://www.iana.org/assignments/media-types/application/octet-stream[application/octet-stream]
|A byte array representing the payload data.

|`Text`
|https://www.iana.org/assignments/media-types/text/plain[text/plain]
|The network byte order UTF-8 encoding of a unicode string representing the payload data.

|`SHM`
|`application/x-shm`
a|The network byte order address of a shared memory segment.

**Note:** The `SHM` payload format is supposed to be used for payloads that are stored in a shared memory segment. The `payload` of the `UMessage` will contain the address of the shared memory segment, and the `payloadFormat` attribute will be set to `SHM`. The actual data in the shared memory segment is not part of the `UMessage` and is not transmitted over the network. The semantics of how to access and interpret the data in the shared memory segment is left to the application and is not defined by uProtocol.
|===
