= uProtocol Attributes (uAttributes)
:toc:
:sectnums:
:stem: latexmath

The key words "*MUST*", "*MUST NOT*", "*REQUIRED*", "*SHALL*", "*SHALL NOT*", "*SHOULD*", "*SHOULD NOT*", "*RECOMMENDED*", "*MAY*", and "*OPTIONAL*" in this document are to be interpreted as described in https://www.rfc-editor.org/info/bcp14[IETF BCP14 (RFC2119 & RFC8174)]

----
SPDX-FileCopyrightText: 2023 Contributors to the Eclipse Foundation

See the NOTICE file(s) distributed with this work for additional
information regarding copyright ownership.

This program and the accompanying materials are made available under
the terms of the Apache License Version 2.0 which is available at
https://www.apache.org/licenses/LICENSE-2.0
 
SPDX-FileType: DOCUMENTATION
SPDX-License-Identifier: Apache-2.0
----

== Overview 

UAttributes contain metadata describing a particular message's purpose, content and processing requirements.

NOTE: Please refer to link:../up-core-api/uprotocol/v1/uattributes.proto[uattributes.proto] for the latest version of the UAttributes data model.

uProtocol defines four types of messages:

[%autowidth]
|===
|Type |Description

|Publish
|A message that is used to notify all interested consumers about an event that has occurred.

|Notification
|A message that is used to inform a specific consumer about an event that has occurred.

|RPC Request
|A message that is used by a service consumer to invoke one of a service provider's methods with some input data, expecting the service provider to reply with a response message.

|RPC Response
|A message that is used by a service provider to send the outcome of processing a request message
from a service consumer.
|===

Each type of message is described by a set of mandatory and optional attributes.

[#common-attributes]
== Common Message Attributes

The following table defines attributes that are used for all message types:

[%autowidth]
|===
|Name |Type |Mandatory |Description

|`id`
|link:uuid.adoc[UUID]
|yes
a|
[.specitem,oft-sid="dsn~up-attributes-id~1",oft-needs="impl,utest"]
--
Every message *MUST* have a unique message identifier. The timestamp contained in the UUID is used as the message's creation time.
--

|`priority`
|link:qos.adoc[UPriority]
|no
a|
The QoS level that this message should be processed/delivered with. 
[.specitem,oft-sid="dsn~up-attributes-priority~1",oft-needs="impl,utest"]
--
A consumer *MUST* assume a message to have the link:qos.adoc#default-priority[default priority] if not set explicitly.
--

|`ttl`
|`unsigned integer`
|no
a|
The amount of time (in milliseconds) after which this message is no longer delivered/processed.
[.specitem,oft-sid="dsn~up-attributes-ttl-timeout~1",oft-needs="impl,utest"]
--
A consumer *MUST NOT* process an expired message. A message is expired if the TTL is > `0` and the consumer's current time is _after_ the message's creation time _plus_ its TTL.
--
[.specitem,oft-sid="dsn~up-attributes-ttl~1",oft-needs="impl,utest"]
--
A consumer *MUST* not consider a message expired if it has a TTL value of `0`.
--


stem:[t_{current} > t_{id} + ttl]

|`traceparent`
|https://w3c.github.io/trace-context/#traceparent-header[W3C Trace Context Level 3, traceparent]
|no
a|
A tracing identifier to use for correlating messages across the system. Intended to be compatible with https://github.com/cloudevents/spec/blob/main/cloudevents/extensions/distributed-tracing.md[CloudEvents distributed tracing extension].

[.specitem,oft-sid="dsn~up-attributes-traceparent~1",oft-needs="impl,utest"]
--
* *MAY* contain traceparent attribute.
--


|`payload format`
|link:upayloadformat.adoc[UPayloadFormat]
|no
a|The format of the payload (data).
[.specitem,oft-sid="dsn~up-attributes-payload-format~1",oft-needs="impl,utest"]
--
* *MAY* contain payload format attribute.
--

|===

[#publish-attributes]
== Publish Message Attributes

The following table defines attributes that are used for publish messages in addition to the common attributes:

[%autowidth]
|===
|Attribute |Mandatory |Description

|`type`
|yes
a| 
[.specitem,oft-sid="dsn~up-attributes-publish-type~1",oft-needs="impl,utest"]
--
*MUST* be set to `UMESSAGE_TYPE_PUBLISH`.
--

|`source`
|yes
a|A link:uri.adoc[UUri] representing the topic that this message is published to.

[.specitem,oft-sid="dsn~up-attributes-publish-source~1",oft-needs="impl,utest"]
--
* The UUri's `resource_id` *MUST* be set to a value in range `[0x8000, 0xFFFE]`.
--

|`sink`
|no
a|A link:uri.adoc[UUri] representing the receiver of this published message. This information is 
only required when we are sending the published event between devices through the streamer, publishers are not required to populate this information.

[.specitem,oft-sid="dsn~up-attributes-publish-sink~1",oft-needs="impl,utest"]
--
* *MAY* be present in the message. If present, the UUri *MUST* only contain the `authority_name` field.
--

|===

[#notification-attributes]
== Notification Message Attributes

The following table defines attributes that are used for notification messages in addition to the common attributes:

[%autowidth]
|===
|Attribute |Mandatory |Description

|`type`
|yes
a|
[.specitem,oft-sid="dsn~up-attributes-notification-type~1",oft-needs="impl,utest"]
--
*MUST* be set to `UMESSAGE_TYPE_NOTIFICATION`.
--
|`source`
|yes
a|
A link:uri.adoc[UUri] representing the component that this notification originates from.

[.specitem,oft-sid="dsn~up-attributes-notification-source~1",oft-needs="impl,utest"]
--
* The UUri's `resource_id` *MUST* be set to a value in range `[0x8000, 0xFFFE]`.
--

|`sink`
|yes
a|A link:uri.adoc[UUri] representing the receiver of this notification.

[.specitem,oft-sid="dsn~up-attributes-notification-sink~1",oft-needs="impl,utest"]
--
* The UUri's `resource_id` *MUST* be set to `0`.
--

|===

[#request-attributes]
== RPC Request Message Attributes

The following table defines attributes that are used for RPC request messages in addition to the common attributes:

[%autowidth]
|===
|Attribute |Mandatory |Description

|`type`
|yes
a|
[.specitem,oft-sid="dsn~up-attributes-request-type~1",oft-needs="impl,utest"]
--
*MUST* be set to `UMESSAGE_TYPE_REQUEST`.
--

|`source`
|yes
a|The link:uri.adoc[UUri] that the service consumer expects to receive the response message at.

[.specitem,oft-sid="dsn~up-attributes-request-source~1",oft-needs="impl,utest"]
--
* The UUri's `resource_id` *MUST* be set to `0`.
--

|`sink`
|yes
a|A link:uri.adoc[UUri] identifying the service provider's method to invoke.

[.specitem,oft-sid="dsn~up-attributes-request-sink~1",oft-needs="impl,utest"]
--
* The UUri's `resource_id` *MUST* be set to a value in range `[1, 0x7FFF]`.
--

|`priority`
|yes
a|The link:qos.adoc[QoS] level that this message should be processed/delivered with.

[.specitem,oft-sid="dsn~up-attributes-request-priority~1",oft-needs="impl,utest"]
--
* *MUST* be set to `UPRIORITY_CS4` or higher.
--


|`ttl`
|yes
a|The amount of time (in milliseconds) after which this request message should no longer be delivered to or processed by a service provider.

[.specitem,oft-sid="dsn~up-attributes-request-ttl~1",oft-needs="impl,utest"]
--
* *MUST* be set to a value > 0
--

|`permission_level`
|no
a|The service consumer's permission level as defined in link:permissions.adoc#_code_based_access_permissions_caps[Code-Based uE Access Permissions (CAPs)].

[.specitem,oft-sid="dsn~up-attributes-permission-level~1",oft-needs="impl,utest"]
--
* *MAY* contain permission level attribute.
--

|`token`
|no
a|The service consumer's access token as defined in link:permissions.adoc#_token_based_access_permissionstaps[Token-Based uE Access Permissions (TAPs)].

[.specitem,oft-sid="dsn~up-attributes-request-token~1",oft-needs="impl,utest"]
--
* *MAY* contain token attribute.
--

|===

[#response-attributes]
== RPC Response Message Attributes

The following table defines attributes that are used for RPC response messages in addition to the common attributes:

[%autowidth]
|===
|Attribute |Mandatory |Description

|`type`
|yes
a|
[.specitem,oft-sid="dsn~up-attributes-response-type~1",oft-needs="impl,utest"]
--
*MUST* be set to `UMESSAGE_TYPE_RESPONSE`.
--

|`source`
|yes
a|The link:uri.adoc[UUri] identifying the method that has been invoked and which this message is the outcome of.

[.specitem,oft-sid="dsn~up-attributes-response-source~1",oft-needs="impl,utest"]
--
* The UUri's `resource_id` *MUST* be set to a value in range `[1, 0x7FFF]`.
--

|`sink`
|yes
a|The link:uri.adoc[UUri] that the service consumer expects to receive this response message at.

[.specitem,oft-sid="dsn~up-attributes-response-sink~1",oft-needs="impl,utest"]
--
* The UUri's `resource_id` *MUST* be set to `0`.
--

|`reqid`
|yes
|The `id` property value of the request message that this is the response to.

|`priority`
|yes
a|
The link:qos.adoc[QoS] level that this message should be processed/delivered with. 

[.specitem,oft-sid="dsn~up-attributes-response-reqid~1",oft-needs="impl,utest"]
--
* *MUST* be the same value as that of the corresponding request message's `priority` attribute.
--

|`ttl`
|no
a|
The amount of time after which this response message should no longer be delivered to or processed by the service consumer.

[.specitem,oft-sid="dsn~up-attributes-response-ttl~1",oft-needs="impl,utest"]
--
* *MUST* be the same value as that of the corresponding request message's `ttl` attribute.
--

|`commstatus`
|no
a|A link:../up-core-api/uprotocol/v1/ustatus.proto[UCode] indicating an error that has occurred during the delivery of either the RPC request or response message. A value of `0` or no value indicates that no communication error has occurred.

[.specitem,oft-sid="dsn~up-attributes-response-commstatus~1",oft-needs="impl,utest"]
--
* *MUST* contain commstatus attribute if the request message was not delivered successfully or the server was unable to process the request.
--

|===

