= uProtocol Attributes (UAttributes)
:toc: preamble
:sectnums:
:stem: latexmath

The key words "*MUST*", "*MUST NOT*", "*REQUIRED*", "*SHALL*", "*SHALL NOT*", "*SHOULD*", "*SHOULD NOT*", "*RECOMMENDED*", "*MAY*", and "*OPTIONAL*" in this document are to be interpreted as described in https://www.rfc-editor.org/info/bcp14[IETF BCP14 (RFC2119 & RFC8174)]

----
SPDX-FileCopyrightText: 2023 Contributors to the Eclipse Foundation

See the NOTICE file(s) distributed with this work for additional
information regarding copyright ownership.

This program and the accompanying materials are made available under
the terms of the Apache License Version 2.0 which is available at
https://www.apache.org/licenses/LICENSE-2.0
 
SPDX-FileType: DOCUMENTATION
SPDX-License-Identifier: Apache-2.0
----

== Overview 

UAttributes contain meta data describing a particular message's purpose, content and processing requirements.

[#data-model-definition]
== Data Model

The diagram below shows the UAttributes class and its properties using UML2 notation.

NOTE: The UCode, UUri and UUID classes are defined in detail in xref:error_model.adoc[Error Model Specification], xref:uri.adoc[UUri Specification] and xref:uuid.adoc[UUID Specification] respectively.

.UAttributes Data Model
[#uattributes-data-model]
[mermaid]
ifdef::env-github[[source,mermaid]]
----
classDiagram

class UAttributes {
  id: UUID
  source: UUri
  sink: UUri [0..1]
  ttl : UInt32 [0..1]
  commstatus: UCode [0..1]
  permissionLevel: UInt32 [0..1]
  requestId: UUID [0..1]
  token: String [0..1]
  traceparent: String [0..1]
}

class UMessageType {
  <<Enumeration>>
  Publish
  Notification
  RPC Request
  RPC Response
}

class UPriority {
  <<Enumeration>>
  CS0
  CS1
  CS2
  CS3
  CS4
  CS5
  CS6
}

class UPayloadFormat {
  <<Enumeration>>
  UPAYLOAD_FORMAT_UNSPECIFIED
  UPAYLOAD_FORMAT_PROTOBUF_WRAPPED_IN_ANY
  UPAYLOAD_FORMAT_PROTOBUF
  UPAYLOAD_FORMAT_JSON
  UPAYLOAD_FORMAT_SOMEIP
  UPAYLOAD_FORMAT_SOMEIP_TLV
  UPAYLOAD_FORMAT_RAW
  UPAYLOAD_FORMAT_TEXT
  UPAYLOAD_FORMAT_SHM
}

UAttributes-->UMessageType : type
UAttributes--> "0..1" UPriority : priority
UAttributes--> "0..1" UPayloadFormat : payloadFormat
----

Each xref:../languages.adoc[uProtocol Language Library]

[.specitem,oft-sid="req~uattributes-data-model-impl~1",oft-needs="impl,utest",oft-tags="LanguageLibrary"]
--
* *MUST* implement the <<uattributes-data-model>> using the language specific type system.
--

[.specitem,oft-sid="req~uattributes-data-model-proto~1",oft-needs="impl,utest",oft-tags="LanguageLibrary"]
--
* *MUST* support writing and reading of an instance of the <<uattributes-data-model>> to/from a protobuf as defined in link:../up-core-api/uprotocol/v1/uattributes.proto[uattributes.proto].
--

uProtocol defines four types of messages:

[cols="1,5"]
|===
|Type |Description

|Publish
|A message that is used to notify all interested consumers about an event that has occurred.

|Notification
|A message that is used to inform a specific consumer about an event that has occurred.

|RPC Request
|A message that is used by a service consumer to invoke one of a service provider's methods with some input data, expecting the service provider to reply with a response message.

|RPC Response
|A message that is used by a service provider to send the outcome of processing a request message
from a service consumer.
|===

Each type of message is described by a set of mandatory and optional attributes.

[#common-attributes]
== Common Message Attributes

The following table defines attributes that are used for all message types:

[%autowidth]
|===
|Name |Type |Mandatory |Description

|`id`
|xref:uuid.adoc[UUID]
|yes
a|
[.specitem,oft-sid="dsn~up-attributes-id~1",oft-needs="impl,utest",oft-tags="LanguageLibrary"]
--
Every message *MUST* have a unique message identifier. The timestamp contained in the UUID is used as the message's creation time.
--

|`priority`
|xref:qos.adoc[UPriority]
|no
a|
The QoS level that this message should be processed/delivered with.
[.specitem,oft-sid="dsn~up-attributes-priority~1",oft-needs="impl,utest",oft-tags="TransportLayerImpl"]
--
A consumer *MUST* assume a message to have the xref:qos.adoc#default-priority[default priority] if not set explicitly.
--

|`ttl`
|`UInt32`
|no
a|
The amount of time (in milliseconds) after which this message is no longer delivered/processed.
[.specitem,oft-sid="dsn~up-attributes-ttl-timeout~1",oft-needs="impl,utest",oft-tags="TransportLayerImpl"]
--
A consumer *MUST NOT* process an expired message. A message is expired if the TTL is > `0` and the consumer's current time is _after_ the message's creation time _plus_ its TTL:

stem:[expired := t_{current} > t_{id} + ttl]
--
[.specitem,oft-sid="dsn~up-attributes-ttl~1",oft-needs="impl,utest",oft-tags="TransportLayerImpl"]
--
A consumer *MUST* not consider a message expired if it has a TTL value of `0`.
--

|`traceparent`
|https://w3c.github.io/trace-context/#traceparent-header[W3C Trace Context Level 3, traceparent]
|no
a|
A tracing identifier to use for correlating messages across the system. Intended to be compatible with https://github.com/cloudevents/spec/blob/main/cloudevents/extensions/distributed-tracing.md[CloudEvents distributed tracing extension].

[.specitem,oft-sid="dsn~up-attributes-traceparent~1",oft-needs="impl,utest",oft-tags="LanguageLibrary"]
--
* *MUST* either be empty or contain a valid https://w3c.github.io/trace-context/#traceparent-header[traceparent].
--


|`payloadFormat`
|<<payload-format,UPayloadFormat>>
|no
a|The format of the payload (data).
[.specitem,oft-sid="dsn~up-attributes-payload-format~1",oft-needs="impl,utest",oft-tags="LanguageLibrary"]
--
* *MUST NOT* contain a value if the message has no payload.
--

|===

[#publish-attributes]
== Publish Message Attributes

The following table defines attributes that are used for publish messages in addition to the common attributes:

[%autowidth]
|===
|Attribute |Type |Mandatory |Description

|`type`
|<<uattributes-data-model,UMessageType>>
|yes
a| 
[.specitem,oft-sid="dsn~up-attributes-publish-type~1",oft-needs="impl,utest",oft-tags="LanguageLibrary"]
--
*MUST* be set to `UMESSAGE_TYPE_PUBLISH`.
--

|`source`
|xref:uri.adoc[UUri]
|yes
a|The topic that this message is published to.

[.specitem,oft-sid="dsn~up-attributes-publish-source~1",oft-needs="impl,utest",oft-tags="LanguageLibrary"]
--
* The UUri's `resource_id` *MUST* be set to a value in range `[0x8000, 0xFFFE]`.
--

|`sink`
|xref:uri.adoc[UUri]
|no
a|A xref:../up-l2/dispatchers/README.adoc#dispatcher-types[uStreamer] can set this property to indicate to an underlying transport implementation the authority of remote uEntities that have subscribed to the message's topic. For this purpose, the streamer may add a UUri that:

[.specitem,oft-sid="dsn~up-attributes-publish-sink~2",oft-needs="impl,utest",oft-tags="LanguageLibrary"]
--
* *MUST* contain a non-empty _authority_name_ and
* *MUST* contain wildcard values for all of the UUri's other fields.
--

|`priority`
|xref:qos.adoc[UPriority]
|yes
a|
The QoS level that this message should be processed/delivered with.
|===

[#notification-attributes]
== Notification Message Attributes

The following table defines attributes that are used for notification messages in addition to the common attributes:

[%autowidth]
|===
|Attribute |Type |Mandatory |Description

|`type`
|<<uattributes-data-model,UMessageType>>
|yes
a|
[.specitem,oft-sid="dsn~up-attributes-notification-type~1",oft-needs="impl,utest",oft-tags="LanguageLibrary"]
--
*MUST* be set to `UMESSAGE_TYPE_NOTIFICATION`.
--
|`source`
|xref:uri.adoc[UUri]
|yes
a|
A xref:uri.adoc[UUri] representing the component that this notification originates from.

[.specitem,oft-sid="dsn~up-attributes-notification-source~1",oft-needs="impl,utest",oft-tags="LanguageLibrary"]
--
* The UUri's `resource_id` *MUST* be set to a value in range `[0x8000, 0xFFFE]`.
--

|`sink`
|xref:uri.adoc[UUri]
|yes
a|A xref:uri.adoc[UUri] representing the receiver of this notification.

[.specitem,oft-sid="dsn~up-attributes-notification-sink~1",oft-needs="impl,utest",oft-tags="LanguageLibrary"]
--
* The UUri's `resource_id` *MUST* be set to `0`.
--

|===

[#request-attributes]
== RPC Request Message Attributes

The following table defines attributes that are used for RPC request messages in addition to the common attributes:

[%autowidth]
|===
|Attribute |Type |Mandatory |Description

|`type`
|<<uattributes-data-model,UMessageType>>
|yes
a|
[.specitem,oft-sid="dsn~up-attributes-request-type~1",oft-needs="impl,utest",oft-tags="LanguageLibrary"]
--
*MUST* be set to `UMESSAGE_TYPE_REQUEST`.
--

|`source`
|xref:uri.adoc[UUri]
|yes
a|The xref:uri.adoc[UUri] that the service consumer expects to receive the response message at.

[.specitem,oft-sid="dsn~up-attributes-request-source~1",oft-needs="impl,utest",oft-tags="LanguageLibrary"]
--
* The UUri's `resource_id` *MUST* be set to `0`.
--

|`sink`
|xref:uri.adoc[UUri]
|yes
a|A xref:uri.adoc[UUri] identifying the service provider's method to invoke.

[.specitem,oft-sid="dsn~up-attributes-request-sink~1",oft-needs="impl,utest",oft-tags="LanguageLibrary"]
--
* The UUri's `resource_id` *MUST* be set to a value in range `[1, 0x7FFF]`.
--

|`priority`
|xref:qos.adoc[UPriority]
|yes
a|The xref:qos.adoc[QoS] level that this message should be processed/delivered with.

[.specitem,oft-sid="dsn~up-attributes-request-priority~1",oft-needs="impl,utest",oft-tags="LanguageLibrary"]
--
* *MUST* be set to `UPRIORITY_CS4` or higher.
--


|`ttl`
|`UInt32`
|yes
a|The amount of time (in milliseconds) after which this request message should no longer be delivered to or processed by a service provider.

[.specitem,oft-sid="dsn~up-attributes-request-ttl~1",oft-needs="impl,utest",oft-tags="LanguageLibrary"]
--
* *MUST* be set to a value > 0
--

|`permissionLevel`
|`UInt32`
|no
a|The service consumer's permission level.

[.specitem,oft-sid="dsn~up-attributes-permission-level~1",oft-needs="impl,utest",oft-tags="LanguageLibrary"]
--
* *MUST* be empty or contain a vaild permission level as defined in xref:permissions.adoc#_code_based_access_permissions_caps[Code-Based uEntity Access Permissions (CAPs)].
--

|`token`
|`String`
|no
a|The service consumer's access token.

[.specitem,oft-sid="dsn~up-attributes-request-token~1",oft-needs="impl,utest",oft-tags="LanguageLibrary"]
--
* *MUST* be empty or contain a token as defined in xref:permissions.adoc#_token_based_access_permissionstaps[Token-Based uEntity Access Permissions (TAPs)].
--

|===

[#response-attributes]
== RPC Response Message Attributes

The following table defines attributes that are used for RPC response messages in addition to the common attributes:

[%autowidth]
|===
|Attribute |Type |Mandatory |Description

|`type`
|<<uattributes-data-model,UMessageType>>
|yes
a|
[.specitem,oft-sid="dsn~up-attributes-response-type~1",oft-needs="impl,utest",oft-tags="LanguageLibrary"]
--
*MUST* be set to `UMESSAGE_TYPE_RESPONSE`.
--

|`source`
|xref:uri.adoc[UUri]
|yes
a|The xref:uri.adoc[UUri] identifying the method that has been invoked and which this message is the outcome of.

[.specitem,oft-sid="dsn~up-attributes-response-source~1",oft-needs="impl,utest",oft-tags="LanguageLibrary"]
--
* The UUri's `resource_id` *MUST* be set to a value in range `[1, 0x7FFF]`.
--

|`sink`
|xref:uri.adoc[UUri]
|yes
a|The xref:uri.adoc[UUri] that the service consumer expects to receive this response message at.

[.specitem,oft-sid="dsn~up-attributes-response-sink~1",oft-needs="impl,utest",oft-tags="LanguageLibrary"]
--
* The UUri's `resource_id` *MUST* be set to `0`.
--

|`requestId`
|xref:uuid.adoc#data-model-definition[UUID]
|yes
a|

[.specitem,oft-sid="dsn~up-attributes-response-correlation-id~1",oft-needs="impl,utest",oft-tags="ServiceProvider"]
--
* *MUST* be set to the value of the `id` property of the request message that this is the response to.
--

|`priority`
|xref:qos.adoc[UPriority]
|yes
a|
The xref:qos.adoc[QoS] level that this message should be processed/delivered with. 

[.specitem,oft-sid="dsn~up-attributes-response-priority~1",oft-needs="impl,utest",oft-tags="ServiceProvider"]
--
* *MUST* be the same value as that of the corresponding request message's `priority` attribute.
--

|`ttl`
|`UInt32`
|yes
a|
The amount of time after which this response message should no longer be delivered to or processed by the service consumer.

[.specitem,oft-sid="dsn~up-attributes-response-ttl~1",oft-needs="impl,utest",oft-tags="ServiceProvider"]
--
* *MUST* be the same value as that of the corresponding request message's `ttl` attribute.
--

|`commstatus`
|xref:error_model.adoc#data-model-definition[UCode]
|no
a|The outcome of the RPC. No value or `UCode.OK` indicate successful invocation of the operation. All other values indicate that invocation was unsuccessful. The concrete value indicates the type of error that has occurred.

|===

[#payload-format]
== Payload Format

The following table provides an overview of the payload formats supported by uProtocol.

[%autowidth]
|===
|UPayloadFormat |MIME Type |Payload encoding

| `UPAYLOAD_FORMAT_UNSPECIFIED`
| N/A
| The payload format is unknown. Clients will need to have gained knowledge about the concrete encoding and semantics of the payload by means of an out-of-band mechanism.


|`UPAYLOAD_FORMAT_PROTOBUF_WRAPPED_IN_ANY`
|`application/x-protobuf`
|The network byte order serialization of a `google.protobuf.Any` structure that contains the payload itself along with the schema URI indicating the (protobuf) type of the payload. 

|`UPAYLOAD_FORMAT_PROTOBUF`
|`application/protobuf`
|The network byte order serialization of the protobuf structure representing the payload data.

|`UPAYLOAD_FORMAT_JSON`
|`application/json`
|The network byte order UTF-8 encoding of a JSON structure representing the payload data.

|`UPAYLOAD_FORMAT_SOMEIP`
|`application/x-someip`
|The network byte order serialization of SOME/IP payload data.

|`UPAYLOAD_FORMAT_SOMEIP_TLV`
|`application/x-someip_tlv`
|The network byte order serialization of SOME/IP TLV payload data.

|`UPAYLOAD_FORMAT_RAW`
|`application/octet-stream`
|A byte array representing the payload data.

|`UPAYLOAD_FORMAT_TEXT`
|`text/plain`
|The network byte order UTF-8 encoding of a unicode string representing the payload data.

|`UPAYLOAD_FORMAT_SHM`
|`application/x-shm`
|The network byte order address of a shared memory segment.
|===
