= UUID
:toc:
:sectnums:

The key words "*MUST*", "*MUST NOT*", "*REQUIRED*", "*SHALL*", "*SHALL NOT*", "*SHOULD*", "*SHOULD NOT*", "*RECOMMENDED*", "*MAY*", and "*OPTIONAL*" in this document are to be interpreted as described in https://www.rfc-editor.org/info/bcp14[IETF BCP14 (RFC2119 & RFC8174)]

----
SPDX-FileCopyrightText: 2023 Contributors to the Eclipse Foundation

See the NOTICE file(s) distributed with this work for additional
information regarding copyright ownership.

This program and the accompanying materials are made available under
the terms of the Apache License Version 2.0 which is available at
https://www.apache.org/licenses/LICENSE-2.0
 
SPDX-FileType: DOCUMENTATION
SPDX-License-Identifier: Apache-2.0
----

== Overview
Universal Unique Identifier (UUID) are used in uProtocol to uniquely identify link:umessage.adoc[`UMessages`]. The UUID include a timestamp used to verify the liveliness of a message (ex. if a type of message should expire or not).  For more explanation of the use cases for the uProtocol UUID, please refer to link:uattributes.adoc[UAttributes Specifications].

[.specitem,oft-sid="req~uuid-spec~1",oft-needs="impl,utest"]
--
 * *MUST* be a https://www.rfc-editor.org/rfc/rfc9562#name-uuid-version-7[UUIDv7] per https://www.rfc-editor.org/rfc/rfc9562[RFC 9562].
--
    

The UUID may be represented in one of the following formats:

 * An instantiation of the <<Data Model>> in a supported programming language
 * or as a "hex-and-dash" string defined in https://www.rfc-editor.org/rfc/rfc9562#name-uuid-format[RFC 9562]


[#data-model-definition]
== Data Model

The diagram below shows a UUID and its properties using UML2 notation.

.UUID Data Model
[#uuID-data-model]
[mermaid]
ifdef::env-github[[source,mermaid]]
----
classDiagram

class UUID {
  msb : UInt64
  lsb : UInt64
}
----

[.specitem,oft-sid="req~uuid-proto~1",oft-needs="impl,utest"]
--
Each link:../languages.adoc[uProtocol Language Library] *MUST* support writing and reading of an instance of the data model to/from a protobuf as defined in link:../up-core-api/uprotocol/v1/uuid.proto[uuid.proto].
--


