= Application Layer (uP-L3)
:toc:
:sectnums:

The key words "*MUST*", "*MUST NOT*", "*REQUIRED*", "*SHALL*", "*SHALL NOT*", "*SHOULD*", "*SHOULD NOT*", "*RECOMMENDED*", "*MAY*", and "*OPTIONAL*" in this document are to be interpreted as described in https://www.rfc-editor.org/info/bcp14[IETF BCP14 (RFC2119 & RFC8174)]

----
SPDX-FileCopyrightText: 2023 Contributors to the Eclipse Foundation

See the NOTICE file(s) distributed with this work for additional
information regarding copyright ownership.

This program and the accompanying materials are made available under
the terms of the Apache License Version 2.0 which is available at
https://www.apache.org/licenses/LICENSE-2.0
 
SPDX-FileType: DOCUMENTATION
SPDX-License-Identifier: Apache-2.0
----

Application layer, also known as the business logic layer, is responsible for declaration interfaces between clients and servers for features and functions, the API layer that defines the methods and topics served by a service.

In this specification we will also define core uProtocol business logic (APIs) such as  subscription management, discovery, and digital twin. These interfaces are _declared once, used everywhere_ so that the mental model for developers is consistent across different heterogeneous systems.

== Architecture Patterns

uProtocol supports the architecture patterns defined in the table below to implement the majority of use cases that could be required for business logic communication between clients and services.

.Architecture Patterns
[width="100%",cols="19%,11%,28%,42%",options="header",]
|===
|Architecture Pattern |Delivery Policy |Description |Requirements

|*RPC* |At-least-once |When uE requires acknowledgement from the receiver  a|
* If the client-side business logic requires retry policy, it *MUST* implement the retry policy
* Server-side business logic *MUST* implement Idempotency for remote procedural calls
* Dispatchers that are unable to deliver req.v1, *MUST* generate a _delivery failure res.v1_ and send it back to the Sender uE

|*Publication* |At-most-once |When uE wishes to publish an CE to multiple consumers (a.k.a. "fire & forget") a|
* Dispatcher *MUST* provide access to CEs that have failed to be delivered (DLT defined in a later section), for both the Sender and/or Receiver uE business logic

|*Notification* |At-most-once |When a uE wishes to notify a specific uE (a.k.a a publication with a destination) |
|===


== Core uProtocol uEs

This special purpose built uEs are required to implement uProtocol and must be present on each uDevice. 

.Core uEs
[width="100%",cols="20%,10,70%",options="header",]
|===
|uE |Ver |Description

|*uSubscription*
|link:usubscription/v3/README.adoc[*v3*]
|Subscription management service that is responsible for managing subscriptions between uEs to realize the publisher/subscriber design pattern.

|*uDiscovery*
|link:udiscovery/v3/README.adoc[*v3*]
|Discovery of uThings locally, within a domain, and throughout the network. Supports URI resolution (to find where something is located)

|*uTwin*
|link:utwin/v2/README.adoc[*v2*]
|Local cache of published events
|===


== Name & Number Registry

In the following section we will elaborate on requirements for assigning names and numbers (ids) to uEs to avoid name space and number collisions.

=== Reserved uE IDs

.Reserved ue_ids
[width="75%",cols="25%,75%",options="header",]
|===
|`ue_id` |Requirement

| *`0x0`* | uSubscription
| *`0x1`* | uDiscovery Client APIs
| *`0x2`* | uDiscovery Replication APIs
| *`0x3`* | uTwin
| *`0x4`* | uStreamer
| *`0x5-0xFF`* | Reserved for Eclipse-uProtocol
| *`0x100 - 0xFFF`* | Reserved for link:https://covesa.global/project/uservices/[COVESA-uServices]
| *`0x1000 - 0x7FFF`* | Reserved for future use
| *`0x8000 - 0xFFFE`* | Vendor specific
| *`0xFFFF`* | Reserved

|===

* uProtocol uE names and numbers *MUST* be declared in protos and added to xref:../up-core-api/uprotocol/core/README.adoc[up-core-api].

=== Names

 * uProtocol defined names *MUST* have `core.` prefix
 * Vendor specific uE names *SHOULD* have the vendor name in the prefix, ex. `volvo.`, 'bmw', etc...
