= Application Layer (uP-L3)
:toc:
:sectnums:

The key words "*MUST*", "*MUST NOT*", "*REQUIRED*", "*SHALL*", "*SHALL NOT*", "*SHOULD*", "*SHOULD NOT*", "*RECOMMENDED*", "*MAY*", and "*OPTIONAL*" in this document are to be interpreted as described in https://www.rfc-editor.org/info/bcp14[IETF BCP14 (RFC2119 & RFC8174)]

----
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
----

Application layer, also known as the business logic layer, is responsible for declaration interfaces between clients and servers for features and functions, the API layer that defines the methods and topics served by a service.

In this specification we will also define core uProtocol business logic (APIs) such as  subscription management, discovery, and digital twin. These interfaces are _declared once, used everywhere_ so that the mental model for developers is consistent across different heterogeneous systems.

== Architecture Patterns

uProtocol supports the architecture patterns defined in the table below to implement the majority of use cases that could be required for business logic communication between clients and services.

.Architecture Patterns
[width="100%",cols="19%,11%,28%,42%",options="header",]
|===
|Architecture Pattern |Delivery Policy |Description |Requirements

|*RPC* |At-least-once |When uE requires acknowledgement from the receiver  a|
* If the client-side business logic requires retry policy, it *MUST* implement the retry policy
* Server-side business logic *MUST* implement Idempotency for remote procedural calls
* Dispatchers that are unable to deliver req.v1, *MUST* generate a _delivery failure res.v1_ and send it back to the Sender uE

|*Publication* |At-most-once |When uE wishes to publish an CE to multiple consumers (a.k.a. "fire & forget") a|
* Dispatcher *MUST* provide access to CEs that have failed to be delivered (DLT defined in a later section), for both the Sender and/or Receiver uE business logic

|*Notification* |At-most-once |When a uE wishes to notify a specific uE (a.k.a a publication with a destination) |
|===


== Core Platform uEs

This special purpose built uEs are required to implement uProtocol and must be present on each uDevice. 

.Core Platform uEs
[width="100%",cols="20%,10,70%",options="header",]
|===
|uE |Ver |Description

|*uSubscription*
|link:../../../src/main/proto/core/usubscription/v2/README.adoc[v2]
|Subscription management service that is responsible for managing subscriptions between uEs to realize the publisher/subscriber design pattern.

|*uDiscovery*
|link:udiscovery/README.adoc[*v2*]
|Discovery of uThings locally, within a domain, and throughout the network. Supports URI resolution (to find where something is located)

|*uTwin*
|link:uTwin/README.adoc[v1]
|Local cache of published events
|===
