= MQTT 5 Transport Protocol
:toc:
:sectnums:

The key words "*MUST*", "*MUST NOT*", "*REQUIRED*", "*SHALL*", "*SHALL NOT*", "*SHOULD*", "*SHOULD NOT*", "*RECOMMENDED*", "*MAY*", and "*OPTIONAL*" in this document are to be interpreted as described in https://www.rfc-editor.org/info/bcp14[IETF BCP14 (RFC2119 & RFC8174)]

----
SPDX-FileCopyrightText: 2023 Contributors to the Eclipse Foundation

Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.

SPDX-FileType: DOCUMENTATION
SPDX-License-Identifier: Apache-2.0
----

== Overview

MQTT is an OASIS standard messaging protocol for the Internet of Things (IoT). It is designed as an extremely lightweight publish/subscribe messaging transport that is ideal for connecting remote devices with a small code footprint and minimal network bandwidth. MQTT today is used in a wide variety of industries, such as automotive, manufacturing, telecommunications, oil and gas, etc

For more information, please refer to https://mqtt.org/

This document will discuss the uTransport implementation on MQTT 5.

== Specifications

=== UAttribute Mapping

MQTT 5 supports custom header fields, and we leverage this to map the UAttribute values into the MQTT header.

[cols="1,1"]
|===
| MQTT Header Property Code | Value (key:value)
| UserProperty
| ("1", "{UAttribute.id}") # UUID id
| UserProperty
| ("2", "{UAttribute.type}") # UMessageType
| UserProperty
| ("3","{UAttribute.source}") # Short Form Serialized Source UURI
| UserProperty
| ("4","{UAttribute.sink}") # Short Form Serialized Sink UURI
| UserProperty
| ("5","{UAttribute.priority}") # UPriority
| UserProperty
| ("6", "{UAttribute.ttl}") # Optional ttl
| UserProperty
| ("7", "{UAttribute.permissionLevel}") # Optional permission level
| UserProperty
| ("8", "{UAttribute.commStatus}") # Optional UCode commstatus
| UserProperty
| ("9", "{UAttribute.reqId}") # UUID reqid
| UserProperty
| ("10", "{UAttribute.token}") # Optional token
| UserProperty
| ("11", "{UAttribute.traceParent}") # Optional traceparent
|===

All uAttributes are mapped to a MQTT header UserProperty, where the key is the UAttribute protobuf field number. The value is a string representation of the UAttribute field.

=== URI Mapping to MQTT topics

The MQTT topic a message is published on utilizes elements from both the source and sink UUri fields. Which elements from the UUri are used in the topic depend on whether the sink UUri is present. In addition, there is a client identifier that defines where the uTransport client is located.

Has sink UUri:

`{client_identifier}/{source.authority_name}/{sink.authority_name}/{sink.ue_id}/{sink.ue_version_major}/{sink.resource_id}`

No sink UUri (Publish message type only):

`{client_identifier}/{source.authority_name}//{source.ue_id}/{source.ue_version_major}/{source.resource_id}`

The entity and resource elements always represent the destination of the message. In the case of a Publish message type, the destination happens to be based on the source UUri. The source authority information is also always present to allow for authorization controls based on the authority information, since an authority maps to the uE sending the message.

The client_identifier is used to determine where messages are coming from. The valid values for the client_identifier are:

- `c` : Indicates that the message originated from the cloud
- `d` : Indicates that the message originated from a device and is remote
- `l` : Indicates that the message originated from a device and is local to that device

The client_identifier that is used for the topic is based on the kind of MQTT uTransport client that is sending the message. An MQTT uTransport client can be one of the following:

- Cloud MQTT uTransport client: A client that runs in the cloud.
- Remote MQTT uTransport client: A client that runs on a device and is connected to a cloud MQTT broker.
- Local MQTT uTransport client: A client that runs on a device and is connected to a local MQTT broker.

Below are examples of messages being sent and how to subscribe to those messages:

==== Remote uTransport Client Examples

How a source and sink UUri are mapped to an MQTT topic when the message is sent from a remote uTransport client:

[cols="1,1,1,1"]
|===
| source | sink | send topic | listen topic
| /vehicle_1.veh.com/1234/1/5678 | /vehicle_2.veh.com/4321/1/8765 | d/vehicle_1.veh.com/vehicle_2.veh.com/4321/1/8765 | c/vehicle_1.veh.com/vehicle_2.veh.com/4321/1/8765
| /vehicle_1.veh.com/1234/1/5678 | None | d/vehicle_1.veh.com//1234/1/5678 | c/vehicle_1.veh.com//1234/1/5678/
|===

Listener examples with wildcards:

[cols="1,1,1,1"]
|===
| goal | source filter | sink filter | listener topic
| Subscribe to all incoming message to a UAuthority | empty | /vehicle_1.veh.com/4294967295/255/65535 | c/\+/vehicle_1.veh.com/+/\+/+
| Subscribe to all publish messages from a UAuthority | /vehicle_1.veh.com/4294967295/255/65535 | None | c/vehicle_1.veh.com//\+/+/+
|===

==== Cloud uTransport Client Examples

Shows how source and sink filters can be used to construct wildcard topics for listening to messages from many devices.

[cols="1,1,1,1"]
|===
| goal | source filter | sink filter | listener topic
| Subscribe to all publish messages from devices | empty | None | d/\+//+/\+/+
| Subscribe to all messages sent from a UAuthority | /vehicle_1.veh.com/4294967295/255/65535 | empty | d/vehicle_1.veh.com/\+/+/\+/+
|===

=== Payload Encoding

The MQTT payload **MUST** be a UPayload that is represented as a byte array to reduce size.
