= MQTT 5 Transport Protocol
:toc:
:sectnums:

The key words "*MUST*", "*MUST NOT*", "*REQUIRED*", "*SHALL*", "*SHALL NOT*", "*SHOULD*", "*SHOULD NOT*", "*RECOMMENDED*", "*MAY*", and "*OPTIONAL*" in this document are to be interpreted as described in https://www.rfc-editor.org/info/bcp14[IETF BCP14 (RFC2119 & RFC8174)]

----
SPDX-FileCopyrightText: 2023 Contributors to the Eclipse Foundation

See the NOTICE file(s) distributed with this work for additional
information regarding copyright ownership.

This program and the accompanying materials are made available under
the terms of the Apache License Version 2.0 which is available at
https://www.apache.org/licenses/LICENSE-2.0

SPDX-FileType: DOCUMENTATION
SPDX-License-Identifier: Apache-2.0
----

== Overview

MQTT is an OASIS standard messaging protocol for the Internet of Things (IoT). It is designed as an extremely lightweight publish/subscribe messaging transport that is ideal for connecting remote devices with a small code footprint and minimal network bandwidth. MQTT today is used in a wide variety of industries, such as automotive, manufacturing, telecommunications, oil and gas, etc

For more information, please refer to https://mqtt.org/

This document will discuss the uTransport implementation on MQTT 5 for two well known use cases:
1. *Device-2-Device (D2D) Communication:* This is when devices (through the streamer) was to send messages to other devices through a cloud gateway (broker). 
2. *uE-2-uE Communication:* When MQTT is used as a local software bus for uEs to talk to each other through a local broker.

The reason for the different configurations is that cloud MQTT brokers often have limitations on the number of topics that can be subscribed to as well as the topic segment lengths so we need to ensure that message routing is as efficient as possible.

== MQTT5 Header

MQTT 5 supports custom header fields, and we leverage this to map the `UAttributes` values into the `UserProperty` MQTT header in string format.

[.specitem,oft-sid="req~up-transport-mqtt5-attributes~1",oft-needs="impl,utest"]
--
* `UserProperty` Keys *MUST* map to the UAttributes protobuf field numbers.
--

.uAttributes Mapping to MQTT5 User Properties
[cols="1,2,5"]
|===
| key |value | Description

| "0"
| "1"
a| The version of the UAttributes protobuf
[.specitem,oft-sid="req~up-transport-mqtt5-attribute-version~1",oft-needs="impl,utest"]
--
* *MUST* represent the major version of the UAttributes protobuf. Currently should be set to `1`.
--

| "1"
| "{UAttributes.id}"
a| Unique identifier for the message

[.specitem,oft-sid="req~up-transport-mqtt5-attribute-id~1",oft-needs="impl,utest"]
--
* *MUST* be set to the https://www.rfc-editor.org/rfc/rfc4122.html#section-3[hyphenated string representation] of the UUID.
--

| "2"
| "{UAttributes.type}"
a| The type of message

[.specitem,oft-sid="req~up-transport-mqtt5-attribute-type~1",oft-needs="impl,utest"]
--
* *MUST* be the enum value for `UAttributes.type` link:../up-core-api/uprotocol/v1/uattributes.proto[UMessageType enum].
--

| "3"
| "{UAttributes.source}"
a| The origin (address) of the message

[.specitem,oft-sid="req~up-transport-mqtt5-attribute-source~1",oft-needs="impl,utest"]
--
* *MUST* be the link:../basics/uri.adoc[string serialization of the UUri]
--

| "4"
| "{UAttributes.sink}"
a| The destination (address) of the message

[.specitem,oft-sid="req~up-transport-mqtt5-attribute-sink~1",oft-needs="impl,utest"]
--
* *MUST* be the link:../basics/uri.adoc[string serialization of the UUri]
--

| "5"
| "{UAttributes.priority}"
a| The message's priority as defined in link:../basics/qos.adoc[QoS doc]

[.specitem,oft-sid="req~up-transport-mqtt5-attribute-priority~1",oft-needs="impl,utest"]
--
* *MUST* be set to the enum value for UAttributes.priority link:../up-core-api/uprotocol/v1/uattributes.proto[UPriority enum].
--

| "6"
| "{UAttributes.ttl}"
a| The amount of time (in milliseconds) after which this message MUST NOT be delivered/processed anymore
    
[.specitem,oft-sid="req~up-transport-mqtt5-attribute-ttl~1",oft-needs="impl,utest"]
--
* *MUST* be set to the TTL value in milliseconds as a string.
--

| "7"
| "{UAttributes.permissionLevel}"
a| The service consumer's permission level as defined in link:../up-l2/permissions.adoc#_code_based_access_permissions_caps[Code-Based uE Access Permissions (CAPs)]

[.specitem,oft-sid="req~up-transport-mqtt5-attribute-permission-level~1",oft-needs="impl,utest"]
--
* *MUST* be set to the link:../up-l2/permissions.adoc#_code_based_access_permissions_caps[CAPs]'s integer value as a string. 
--

| "8" 
| "{UAttributes.commStatus}"
a| A UCode indicating an error that has occurred during the delivery of either an RPC Request or Response message

[.specitem,oft-sid="req~up-transport-mqtt5-attribute-comm-status~1",oft-needs="impl,utest"]
--
* *MUST* be set to the link:../up-core-api/uprotocol/v1/ustatus.proto[UCode]'s integer value as a string.
--

| "9"
| "{UAttributes.reqId}"
a| The identifier that a service consumer can use to correlate an RPC response message with its RPC request

[.specitem,oft-sid="req~up-transport-mqtt5-attribute-req-id~1",oft-needs="impl,utest"]
--
* *MUST* be set to the https://www.rfc-editor.org/rfc/rfc4122.html#section-3[hyphenated string representation] of the UUID.
--

| "10"
| "{UAttributes.token}"
a| The service consumer's access token

[.specitem,oft-sid="req~up-transport-mqtt5-attribute-token~1",oft-needs="impl,utest"]
--
* *MUST* be the token value as a string.
--

| "11"
| "{UAttributes.traceparent}"
a| A tracing identifier to use for correlating messages across the system

[.specitem,oft-sid="req~up-transport-mqtt5-attribute-traceparent~1",oft-needs="impl,utest"]
--
* *MUST* be set to the traceparent value as a string.
--

| "12"
| "{UAttributes.payload_format}"
a| The format for the data stored in the UMessage

[.specitem,oft-sid="req~up-transport-mqtt5-attribute-payload-format~1",oft-needs="impl,utest"]
--
* *MUST* be set to the enum value for UAttributes.payload_format link:../up-core-api/uprotocol/v1/uattributes.proto[UPayloadFormat enum].
--

|===

All uAttributes are mapped to a MQTT header UserProperty, where the key is the UAttributes protobuf field number. The value is a string representation of the UAttributes field. Only UAttributes that are used in the message are included in the MQTT header. If a UAttributes field is not present in the header, than it is considered not used when recompiling the UAttributes.

== Payload Encoding

[.specitem,oft-sid="req~up-transport-mqtt5-payload-encoding~1",oft-needs="impl,utest"]
--
* The MQTT payload **MUST** be the `UMessage.payload` field, which is a byte array to reduce size.
--


== MQTT5 Topics

The MQTT topic a message is published on utilizes the source and sink UUri fields. The topic is dependent on the use case for the transport implementation that will be discussed below.


=== uE-2-uE Communication

When a message is sent from one uE to another uE, the topic is constructed using the source and sink UUri fields. The topic is constructed as follows using the string representation of a `UUri`:

[.specitem,oft-sid="req~up-transport-mqtt5-ue2ue-topic~1",oft-needs="impl,utest"]
--
`{UAttributes.source}/{UAttributes.sink}/`
--

[.specitem,oft-sid="req~up-transport-mqtt5-ue2ue-topic-nosink~1",oft-needs="impl,utest"]
--
If the messages does not have a sink `UUri`, then the sink portion of the MQTT5 topic *MUST* be omitted.
--

==== Examples

.uE-2-uE Communication Topics
[cols="1,2,2,4"]
|===
| Type| source URI | sink URI | MQTT5 Topic

| *Request* | `//device1/AB34/1/0` | `//device1/43BA/1/2` | `device1/AB34/1/0/device1/43BA/1/2`
| *Response* | `//device1/43BA/1/2` | `//device1/AB34/1/0` | `device1/43BA/1/2/device1/AB34/1/0`
| *Publish* | `//device1/AB34/1/8000` | None | `device1/AB34/1/8000`
| *Notification* | `//device1/43BA/1/8001` | `//device1/AB34/1/0` | `device1/43BA/1/8001/device1/AB34/1/0`
|===


.uE-2-uE Communication UTransport::registerListener() Examples
[cols="1,1,1,1"]
|===
| Use Case | source filter | sink filter | MQTT Subscription

| Single Publish Topic | `//device1/AB34/1/8000` | None | `device1/AB34/1/8000`
| Incoming requests for a Method | empty | `//device1/AB34/1/12CD` | `\+/+/\+/+/device1/AB34/1/12CD`
| Any Notifications or RPC Responses | empty | //device1/AB34/1/0 | `\+/+/\+/+/device1/AB34/1/0`

|===


=== D2D Communication

D2D routing of messages only require the authority portion of the source and sink attributes for routing between devices so the MQTT5 topic shall be:

[.specitem,oft-sid="req~up-transport-mqtt5-d2d-topic~1",oft-needs="impl,utest"]
--
`{UAttributes.source.authority_name}/{UAttributes.sink.authority_name}`
--

==== Examples

===== Registering Listener to Receive All Messages 
`UTransport::registerListener(ANY, getSource())` where getSource(0 returns the local device's UUri, this translates into the MQTT subscribe to topic `+/{my_source_authority_name}`

===== Sending a Message
`UTransport::send(UMessage)` translates to the MQTT publish to topic `{UMessage.source.authority_name}/{UMessage.sink.authority_name}`



