= MQTT Transport Protocol
:toc:
:sectnums:

The key words "*MUST*", "*MUST NOT*", "*REQUIRED*", "*SHALL*", "*SHALL NOT*", "*SHOULD*", "*SHOULD NOT*", "*RECOMMENDED*", "*MAY*", and "*OPTIONAL*" in this document are to be interpreted as described in https://www.rfc-editor.org/info/bcp14[IETF BCP14 (RFC2119 & RFC8174)]

----
Copyright (c) 2023 General Motors GTO LLC

Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.

SPDX-FileType: DOCUMENTATION
SPDX-FileCopyrightText: 2023 General Motors GTO LLC
SPDX-License-Identifier: Apache-2.0
----

== Overview

MQTT is an OASIS standard messaging protocol for the Internet of Things (IoT). It is designed as an extremely lightweight publish/subscribe messaging transport that is ideal for connecting remote devices with a small code footprint and minimal network bandwidth. MQTT today is used in a wide variety of industries, such as automotive, manufacturing, telecommunications, oil and gas, etc

For more information, please refer to https://mqtt.org/

== Specifications

=== UAttribute Mapping

MQTT 5 supports custom header fields, and we leverage this to map certain UAttribute values into the MQTT header.

[cols="1,1"]
|===
| MQTT Header Property Code | Value (key:value)
| UserProperty
| ("upriority","{UAttribute.priority}")
| CorrelationData
| ("reqid", "{UAttribute.reqId}")
| UserProperty
| ("sink","{UAttribute.sink}") # Should this be serialized to MicroUri?
| UserProperty
| ("type", "{UAttribute.type}")
|===

The upriority field is needed as mqtt's QoS is very limited, so this will allow listeners to prioritize messages.

The Correlation Data Property Code contains the request correlation id.

The sink field is used to correctly map a message to the correct uE as the topic name may not contain all of the information.

=== URI Mapping

Depending on whether the UURI is local or remote, the MQTT Topic that the message will be published on will be different:

* The remote UUri (with UAuthority): `upr/UUri.UAthority.name`
* The local UUri (without UAuthority): `upl/UUri.UEntity/UUri.UResource`

Examples:

* The remote UUri (with UAuthority):

[source]
----
UUri {
  authority: UAuthority {
    name: "Vehicle_1",
    number: Id({01, 02, 03, 10, 11, 12})
  },
  entity: UEntity {
    name: "body.access",
    version_major: 1,
    id: 1234,
  }
  resource: UResource {
    name: "door",
    instance: "front_left",
    message: "Door",
    id: 5678,
  }
}
----

Since this is a remote UUri, the MQTT Topic will simply be `upr/Vehicle_1`.

* The local UUri (without UAuthority):

[source]
----
UUri {
  authority: empty,
  entity: UEntity {
    name: "body.access",
    version_major: 1,
    id: 1234,
  }
  resource: UResource {
    name: "door",
    instance: "front_left",
    message: "Door",
    id: 5678,
  }
}
----

Since this is a local UUri, the MQTT Topic will be constructed from the UEnity name and the UResource name `upl/body.access/door`.

=== Payload Encoding

The MQTT payload **MUST** be a UMessage that is represented as a byte array to reduce size.
