= MQTT 5 Transport Protocol
:toc: preamble
:sectnums:
:stem: latexmath

The key words "*MUST*", "*MUST NOT*", "*REQUIRED*", "*SHALL*", "*SHALL NOT*", "*SHOULD*", "*SHOULD NOT*", "*RECOMMENDED*", "*MAY*", and "*OPTIONAL*" in this document are to be interpreted as described in https://www.rfc-editor.org/info/bcp14[IETF BCP14 (RFC2119 & RFC8174)]

----
SPDX-FileCopyrightText: 2023 Contributors to the Eclipse Foundation

See the NOTICE file(s) distributed with this work for additional
information regarding copyright ownership.

This program and the accompanying materials are made available under
the terms of the Apache License Version 2.0 which is available at
https://www.apache.org/licenses/LICENSE-2.0

SPDX-FileType: DOCUMENTATION
SPDX-License-Identifier: Apache-2.0
----

== Overview

MQTT is an OASIS standard messaging protocol for the Internet of Things (IoT). It is designed as an extremely lightweight publish/subscribe messaging transport that is ideal for connecting remote devices with a small code footprint and minimal network bandwidth. MQTT today is used in a wide variety of industries, such as automotive, manufacturing, telecommunications, oil and gas etc.

For more information, please refer to https://mqtt.org/

This document defines how MQTT 5 PUBLISH packets can be used to transfer uProtocol messages (UMessages) between uEntities for the following use cases:

1. *uEntity-2-uEntity* (E2E): Communication between uEntities within the same vehicle by means of an _in-vehicle_ MQTT broker.
2. *Device-2-Device* (D2D): Communication between uEntities in vehicles and a (cloud) back end system by means of an _off-vehicle_ MQTT broker, e.g. running in the back end. MQTT brokers running on cloud infrastructure often have limitations regarding the number of topics that can be subscribed and the number of segments those topics may contain. The mapping for this use case therefore uses a coarser grained topic structure than the one for in-vehicle only communication.

== UMessage Mapping

A uProtocol message consists of _UAttributes_ and optional payload. The following sections define how these are mapped to/from an MQTT 5 PUBLISH packet.

=== UAttributes

[.specitem,oft-sid="dsn~up-transport-mqtt5-attributes-mapping~1",oft-needs="impl,utest",oft-tags="TransportLayerImpl"]
--
An MQTT 5 PUBLISH packet that is used to convey a uProtocol message *MUST* contain properties as defined in <<uAttributes Mapping to MQTT 5 PUBLISH Properties>> for those and only those of the UMessage's attributes which have a non-empty value.
--

.uAttributes Mapping to MQTT 5 PUBLISH Properties
[cols="1,2,5"]
|===
| uAttributes Property
| PUBLISH Packet Property
| Description

| N/A
| User Property [key: _uP_]
a| The uProtocol version being used

* *MUST* be set to the (major) version of the uProtocol specification that the message mapping adheres to. At the time of writing, the version is `1`.
* Message consumers *MAY* use this property to determine that the (PUBLISH) packet contains a uProtocol message.

| _id_
| User Property [key: _1_]
a| The unique identifier of the message

* *MUST* be set to the https://www.rfc-editor.org/rfc/rfc4122.html#section-3[hyphenated string representation] of the UUID.

| _type_
| User Property [key: _2_]
a| The message type

* *MUST* be set to the value of the _uprotocol.ce_name_ option defined for the
link:../up-core-api/uprotocol/uattributes.proto[UMessageType enum].

| _source_
| User Property [key: _3_]
a| The origin (address) of the message

* *MUST* be set to the link:../basics/uri.adoc#uri-definition[string serialization of the UUri]

| _sink_
| User Property [key: _4_]
a| The destination (address) of the message

* *MUST* be set to the link:../basics/uri.adoc#uri-definition[string serialization of the UUri]

| _priority_
| User Property [key: _5_]
a| The message's priority as defined in link:../basics/qos.adoc[QoS doc]

* *MUST* be set to the value of the _uprotocol.ce_name_ option defined for the
link:../up-core-api/uprotocol/uattributes.proto[UPriority enum].

| _ttl_
| User Property [key: _6_] +
_Message Expiry Interval_

a| The amount of time after which this message must no be delivered/processed anymore
    
The _Message Expiry Interval_ property *MUST* be set to

stem:[expiry := ceil(ttl/1000)].

The User Property *MUST* be set to the value of _ttl_ if, and only if

stem:[ttl \bmod 1000 > 0].

This is necessary to retain the original value for the receiving end, because the MQTT message expiry interval has second granularity only.
If the TTL is a multiple of 1000, i.e. has second granularity as well, then it is sufficient to set the _Message Expiry Interval_, from which the receiving side can derive the original TTL.

| _permissionLevel_
| User Property [key: _7_]
a| The service consumer's permission level as defined in link:../up-l2/permissions.adoc#_code_based_access_permissions_caps[Code-Based uE Access Permissions (CAPs)]

* *MUST* be set to the link:../up-l2/permissions.adoc#_code_based_access_permissions_caps[CAP] value's decimal string representation. 

| _commStatus_
| User Property [key: _8_]
a| A UCode indicating an error that has occurred during the delivery of either an RPC Request or Response message

* *MUST* be set to the link:../up-core-api/uprotocol/v1/ustatus.proto[UCode enum] integer value's decimal string representation.

| _reqId_
| _Correlation Data_
a| The identifier that a service consumer can use to correlate an RPC response message with its RPC request

* *MUST* be set to the UUID's 16 byte representation in big endian order.

| _token_
| User Property [key: _10_]
a| The service consumer's access token

* *MUST* be set to the token value.

| _traceparent_
| User Property [key: _11_]
a| A tracing identifier to use for correlating messages across the system

* *MUST* be set to the traceparent value.

| _payload_format_
| _Content Type_
a| The type of data contained in the message's payload

* *MUST* be set to the link:../up-core-api/uprotocol/v1/uattributes.proto[UPayloadFormat enum] integer value's decimal string representation.

Note that the enum's integer value is used instead of the _uprotocol.mime_type_ option's value in order to reduce the overall size of the PUBLISH packet.

|===

=== Payload

[.specitem,oft-sid="dsn~up-transport-mqtt5-payload-mapping~1",oft-needs="impl,utest",oft-tags="TransportLayerImpl"]
--
An MQTT 5 PUBLISH packet that is used to convey a uProtocol message *MUST* contain in its payload the unaltered value of the UMessage's _payload_ field.
--


== MQTT Topic Structure

Message producers publish messages to _topics_ maintained by an MQTT broker. Other clients can then subscribe to such topics in order to receive the messages that are being published to these topics.

The topic name of an MQTT 5 PUBLISH packet that is used to transfer a uProtocol message is derived from the message's `source` and `sink` attributes.

=== uEntity-2-uEntity Communication

[.specitem,oft-sid="dsn~up-transport-mqtt5-e2e-topic-names~1",oft-needs="impl,utest",oft-tags="TransportLayerImpl"]
--
The topic name of an MQTT 5 PUBLISH packet containing a _Publish_ UMessage that is published to an _in-vehicle_ broker **MUST** consist of the following segments:

`{source.authority}/{source.ue_type}/{source.ue_instance}/{source.ue_version}/{source.resource}`

The topic name of an MQTT 5 PUBLISH packet containing a _Notification_, _RPC Request_ or _RPC Response_ UMessage that is published to an _in-vehicle_ broker **MUST** consist of the following segments:

`{source.authority}/{source.ue_type}/{source.ue_instance}/{source.ue_version}/{source.resource}/{sink.authority}/{sink.ue_type}/{sink.ue_instance}/{sink.ue_version}/{sink.resource}`
--

Please refer to <<UUri Encoding Rules>> for details regarding the encoding of the `source` and `sink` UUris into the topic's segments.

==== Examples

The examples below show the MQTT 5 topic names to use for sending different types of UMessages via an _in-vehicle_ broker. The sending uEntity has uEntity type ID `3BA`.

.Publishing an event on a topic
--
[cols="2,8"]
|===
|*Source URI*
|`up://device1/3BA/3/9876`

|*Sink URI*
|-

|*MQTT Topic Name*
|`device1/3BA/0/3/9876`
|===
--

.Sending a Notification to another uEntity
--
[cols="2,8"]
|===
|*Source URI*
|`up://device1/3BA/3/B1`

|*Sink URI*
|`up://device1/200AB/1/0`

|*MQTT Topic Name*
|`device1/3BA/0/3/8001/device1/AB/2/1/0`
|===
--

.Sending an RPC Request to a service provider
--
[cols="2,8"]
|===
|*Source URI*
|`up://device1/403BA/3/0`

|*Sink URI*
|`up:///AB/1/2`

|*MQTT Topic Name*
|`device1/3BA/4/3/0/device1/AB/0/1/2`
|===
--

.Sending an RPC Response to a service client
--
[cols="2,8"]
|===
|*Source URI*
|`up:///3BA/3/67`

|*Sink URI*
|`up://device1/100AB/1/0`

|*MQTT Topic Name*
|`device1/3BA/0/3/67/device1/AB/1/1/0`
|===
--

The examples below show the MQTT 5 topic filters to use for receiving different types of UMessages via an _in-vehicle_ broker. The receiving uEntity has uEntity type ID `AB`.

.Subscribe to a specific topic
--
[cols="2,8"]
|===
|*Source Filter*
|`up://*/FFFF03BA/3/9876`

|*Sink Filter*
|-

|*MQTT Topic Filter*
|`\+/3BA/+/3/9876`
|===
--

.Receive Notifications from the default instance of a specific uEntity
--
[cols="2,8"]
|===
|*Source Filter*
|`up://device1/3BA/4/FFFF`

|*Sink Filter*
|`up://device1/AB/1/0`

|*MQTT Topic Filter*
|`device1/3BA/0/4/+/device1/AB/0/1/0`
|===
--

.Receive all RPC Requests for a specific method
--
[cols="2,8"]
|===
|*Source Filter*
|-

|*Sink Filter*
|`up:///AB/0/1/12CD`

|*MQTT Topic Filter*
|`\+/+/\+/+/+/device1/AB/0/1/12CD`
|===
--

.Receive all RPC Responses
--
[cols="2,8"]
|===
|*Source Filter*
|-

|*Sink Filter*
|`up:///AB/0/1/0`

|*MQTT Topic Filter*
|`\+/+/\+/+/+/device1/AB/0/1/0`
|===
--

=== Device-2-Device Communication

[.specitem,oft-sid="dsn~up-transport-mqtt5-d2d-topic-names~1",oft-needs="impl,utest",oft-tags="TransportLayerImpl"]
--
The topic name of an MQTT 5 PUBLISH packet containing a UMessage that is published to an _off-vehicle_ broker **MUST** consist of the following segments:

`{source.authority}/{sink.authority}`
--

Please refer to <<UUri Encoding Rules>> for details regarding the encoding of the source and sink UUris into topic segments.

==== Examples

The MQTT 5 topic name used by uEntities with authority name `vehicle1` for sending any type of UMessage to uEntities with authority name `backend` via an _off-vehicle_ broker is

`vehicle1/backend`

The MQTT 5 topic filter used by uEntities with authority name `backend` for receiving all types of UMessages from uEntities with arbitrary authority names via an _off-vehicle_ broker is

`+/backend`

=== UUri Encoding Rules

The table below contains the rules for encoding a UUri's fields into an MQTT topic name's or filter's segments.

[cols="2,2,6"]
|===
| Topic Segment
| UUri Field
| Encoding

|`authority`
|`authority_name`
a| The segment *MUST* contain the (UTF8) string representation of the 

1. `+` (`U+002B`, Plus Sign) character, if the authority name is the xref:../basics/uri.adoc#pattern-matching[wildcard authority].
2. name of the host/authority that the (local) uEntity is running on, if authority name is empty.
3. authority name, otherwise.

|`ue_type`
|`ue_id`
a| The segment *MUST* contain the (UTF8) string representation of the

1. `+` (`U+002B`, Plus Sign) character, if the uEntity type identifier is the xref:../basics/uri.adoc#pattern-matching[wildcard type ID].
2. the upper-case link:https://www.rfc-editor.org/rfc/rfc4648#section-8[base16 encoding] of the uEntity type identifier with all leading `0` characters omitted.

|`ue_instance`
|`ue_id`
a| The segment *MUST* contain the (UTF8) string representation of the

1. `+` (`U+002B`, Plus Sign) character, if the uEntity instance identifier is the xref:../basics/uri.adoc#pattern-matching[wildcard instance ID].
2. the upper-case link:https://www.rfc-editor.org/rfc/rfc4648#section-8[base16 encoding] of the uEntity instance identifier with all leading `0` characters omitted.

|`ue_version`
|`ue_version_major`
a| The segment *MUST* contain the (UTF8) string representation of the

1. `+` (`U+002B`, Plus Sign) character, if the uEntity major version is the xref:../basics/uri.adoc#pattern-matching[wildcard version].
2. the upper-case link:https://www.rfc-editor.org/rfc/rfc4648#section-8[base16 encoding] of the uEntity major version with all leading `0` characters omitted.

|`resource`
|`resource_id`
a| The segment *MUST* contain the (UTF8) string representation of the

1. `+` (`U+002B`, Plus Sign) character, if the resource identifier is the xref:../basics/uri.adoc#pattern-matching[wildcard resource ID].
2. the upper-case link:https://www.rfc-editor.org/rfc/rfc4648#section-8[base16 encoding] of the resource identifier with all leading `0` characters omitted.

|===

== Connection Handling

[.specitem,oft-sid="req~up-transport-mqtt5-session-config~1",oft-needs="impl,utest",oft-tags="TransportLayerImpl"]
--
Each transport implementing this specification *MUST* provide means to configure the values of the https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html#_Toc3901048[Session Expiry Interval] and https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html#_Toc3901039[Clean Start] properties of the MQTT CONNECT packet being used when establishing a connection to a broker.
--

[.specitem,oft-sid="req~up-transport-mqtt5-reconnection~1",oft-needs="impl,utest",oft-tags="TransportLayerImpl"]
--
Each transport implementing this specification *MUST*

* re-establish a lost connection to an MQTT broker using an exponential backoff strategy.
* re-subscribe to all previously subscribed topics, if the broker indicates that link:https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html#_Toc3901078[no session is present] after successful reconnection.

The following table provides some guidance for implementation:

[cols="3,2,2,2,2,2"]
|===
| Reconnect attempt | 1 | 2 | 3 | 4 | n > 4
| Backoff (ms)      | `500` | `1000` | `2000` | `4000` | `10000`
|===
--
