= MQTT 5 Transport Protocol
:toc: preamble
:sectnums:

The key words "*MUST*", "*MUST NOT*", "*REQUIRED*", "*SHALL*", "*SHALL NOT*", "*SHOULD*", "*SHOULD NOT*", "*RECOMMENDED*", "*MAY*", and "*OPTIONAL*" in this document are to be interpreted as described in https://www.rfc-editor.org/info/bcp14[IETF BCP14 (RFC2119 & RFC8174)]

----
SPDX-FileCopyrightText: 2023 Contributors to the Eclipse Foundation

See the NOTICE file(s) distributed with this work for additional
information regarding copyright ownership.

This program and the accompanying materials are made available under
the terms of the Apache License Version 2.0 which is available at
https://www.apache.org/licenses/LICENSE-2.0

SPDX-FileType: DOCUMENTATION
SPDX-License-Identifier: Apache-2.0
----

== Overview

MQTT is an OASIS standard messaging protocol for the Internet of Things (IoT). It is designed as an extremely lightweight publish/subscribe messaging transport that is ideal for connecting remote devices with a small code footprint and minimal network bandwidth. MQTT today is used in a wide variety of industries, such as automotive, manufacturing, telecommunications, oil and gas etc.

For more information, please refer to https://mqtt.org/

This document defines the mapping of uProtocol messages (UMessages) to MQTT version 5 PUBLISH packets for the following use cases:

1. *uEntity-2-uEntity* (E2E): Communication between uEntities within the same vehicle by means of an _in-vehicle_ MQTT broker.
2. *Device-2-Device* (D2D): Communication between vehicles and uEntities in a (cloud) back end system by means of an _off-vehicle_ MQTT broker, e.g. running in the back end. MQTT brokers running on cloud infrastructure often have limitations regarding the number of topics that can be subscribed and the number of segments those topics may contain. The mapping for this use case therefore uses a coarser grained topic structure than the one for in-vehicle only communication.

== UMessage Mapping

A uProtocol messages consists of _UAttributes_ and optional payload. The following sections define how these are mapped to/from an MQTT 5 PUBLISH packet.

=== UAttributes

All of a UMessage's attributes are mapped to custom header fields of an MQTT 5 PUBLISH packet.

[.specitem,oft-sid="dsn~up-transport-mqtt5-attributes-non-empty~1",oft-needs="impl,utest"]
--
* All of a UMessage's attributes having a non-empty value *MUST* be mapped to MQTT header _User Properties_ as defined in <<uAttributes Mapping to MQTT 5 User Properties>>.
* Attributes having an empty value *MUST NOT* be mapped.
--

.uAttributes Mapping to MQTT 5 User Properties
[cols="1,2,5"]
|===
| uAttributes Property
| MQTT 5 User Property Key
| Description

| N/A
| `0`
a| The version of the UAttributes proto3 definition being used
[.specitem,oft-sid="dsn~up-transport-mqtt5-attribute-version~1",oft-needs="impl,utest"]
--
* *MUST* be set to the (major) version of the UAttributes data structure being used. At the time of writing, the version is `1`.
--

| `id`
| `1`
a| The unique identifier of the message

[.specitem,oft-sid="dsn~up-transport-mqtt5-attribute-id~1",oft-needs="impl,utest"]
--
* *MUST* be set to the https://www.rfc-editor.org/rfc/rfc4122.html#section-3[hyphenated string representation] of the UUID.
--

| `type`
| `2`
a| The message type

[.specitem,oft-sid="dsn~up-transport-mqtt5-attribute-type~1",oft-needs="impl,utest"]
--
* *MUST* be set to the value of the `uprotocol.ce_name` option defined for the
link:../up-core-api/uprotocol/uattributes.proto[UMessageType enum].
--

| `source`
| `3`
a| The origin (address) of the message

[.specitem,oft-sid="dsn~up-transport-mqtt5-attribute-source~1",oft-needs="impl,utest"]
--
* *MUST* be set to the link:../basics/uri.adoc[string serialization of the UUri]
--

| `sink`
| `4`
a| The destination (address) of the message

[.specitem,oft-sid="dsn~up-transport-mqtt5-attribute-sink~1",oft-needs="impl,utest"]
--
* *MUST* be set to the link:../basics/uri.adoc[string serialization of the UUri]
--

| `priority`
| `5`
a| The message's priority as defined in link:../basics/qos.adoc[QoS doc]

[.specitem,oft-sid="dsn~up-transport-mqtt5-attribute-priority~1",oft-needs="impl,utest"]
--
* *MUST* be set to the value of the `uprotocol.ce_name` option defined for the
link:../up-core-api/uprotocol/uattributes.proto[UPriority enum].
--

| `ttl`
| `6`
a| The amount of time (in milliseconds) after which this message MUST NOT be delivered/processed anymore
    
[.specitem,oft-sid="dsn~up-transport-mqtt5-attribute-ttl~1",oft-needs="impl,utest"]
--
* *MUST* be set to the TTL value's decimal string representation.
--

| `permissionLevel`
| `7`
a| The service consumer's permission level as defined in link:../up-l2/permissions.adoc#_code_based_access_permissions_caps[Code-Based uE Access Permissions (CAPs)]

[.specitem,oft-sid="dsn~up-transport-mqtt5-attribute-permission-level~1",oft-needs="impl,utest"]
--
* *MUST* be set to the link:../up-l2/permissions.adoc#_code_based_access_permissions_caps[CAP] value's decimal string representation. 
--

| `commStatus`
| `8` 
a| A UCode indicating an error that has occurred during the delivery of either an RPC Request or Response message

[.specitem,oft-sid="dsn~up-transport-mqtt5-attribute-comm-status~1",oft-needs="impl,utest"]
--
* *MUST* be set to the link:../up-core-api/uprotocol/v1/ustatus.proto[UCode enum] integer value's decimal string representation.
--

| `reqId`
| `9`
a| The identifier that a service consumer can use to correlate an RPC response message with its RPC request

[.specitem,oft-sid="dsn~up-transport-mqtt5-attribute-req-id~1",oft-needs="impl,utest"]
--
* *MUST* be set to the https://www.rfc-editor.org/rfc/rfc4122.html#section-3[hyphenated string representation] of the UUID.
--

| `token`
| `10`
a| The service consumer's access token

[.specitem,oft-sid="dsn~up-transport-mqtt5-attribute-token~1",oft-needs="impl,utest"]
--
* *MUST* be set to the token value.
--

| `traceparent`
| `11`
a| A tracing identifier to use for correlating messages across the system

[.specitem,oft-sid="dsn~up-transport-mqtt5-attribute-traceparent~1",oft-needs="impl,utest"]
--
* *MUST* be set to the traceparent value.
--

| `payload_format`
| `12`
a| The format for the data stored in the UMessage

[.specitem,oft-sid="dsn~up-transport-mqtt5-attribute-payload-format~1",oft-needs="impl,utest"]
--
* *MUST* be set to the link:../up-core-api/uprotocol/v1/uattributes.proto[UPayloadFormat enum] integer value's decimal string representation.
--

|===

=== Payload

[.specitem,oft-sid="dsn~up-transport-mqtt5-payload-encoding~1",oft-needs="impl,utest"]
--
* The (byte array) value of the UMessage's `payload` field **MUST** be mapped to the MQTT 5 PUBLISH packet payload _as is_.
--


== MQTT Topic Structure

The topic name that is used for an MQTT 5 PUBLISH packet that contains a uProtocol message is derived from the message's `source` and `sink` attribute values.

=== uE-2-uE Communication

[.specitem,oft-sid="dsn~up-transport-mqtt5-ue2ue-topic~1",oft-needs="impl,utest"]
--
The topic name of an MQTT 5 PUBLISH packet containing a _Publish_ UMessage that is published to an _in-vehicle_ broker **MUST** consist of the following segments:

`{source.authority_name}/{source.ue_id}/{source.ue_version_major}/{source.resource_id}`

The topic name of an MQTT 5 PUBLISH packet containing a _Notification_, _RPC Request_ or _RPC Response_ UMessage that is published to an _in-vehicle_ broker **MUST** consist of the following segments:

`{source.authority_name}/{source.ue_id}/{source.ue_version_major}/{source.resource_id}/{sink.authority_name}/{sink.ue_id}/{sink.ue_version_major}/{sink.resource_id}`
--

==== Examples

The table below provides examples of MQTT 5 topic names to use for sending different types of UMessages via an _in-vehicle_ broker. The sending uEntity has uEntity type ID `43BA`.

.uE-2-uE Topic Names
[cols="1,2,2,4"]
|===
| UMessage Type | Source URI | Sink URI | MQTT 5 Topic

| _Publish_ | `up://device1/43BA/3/9876` | - | `device1/43BA/3/9876`
| _Notification_ | `up://device1/43BA/3/8001` | `up://device1/AB34/1/0` | `device1/43BA/3/8001/device1/AB34/1/0`
| _Request_ | `up://device1/43BA/3/0` | `up://device1/AB34/1/2` | `device1/43BA/3/0/device1/AB34/1/2`
| _Response_ | `up://device1/43BA/3/67` | `up://device1/AB34/1/0` | `device1/43BA/3/67/device1/AB34/1/0`
|===

The table below provides examples of MQTT 5 topic filters to use for receiving different types of UMessages via an _in-vehicle_ broker. The receiving uEntity has uEntity type ID `AB34`.

.uE-2-uE Topic Filters
[cols="1,1,1,1"]
|===
| Use Case | Source filter | Sink filter | MQTT Topic Filter

| Subscribe to a specific topic | `up://device1/43BA/3/9876` | - | `device1/43BA/3/9876`
| Receive Notifications from a specific uEntity | `up://device1/43BA/3/FFFF` | `up://device1/AB34/1/0` | `device1/43BA/3/+/device1/AB34/1/0`
| Receive all RPC Requests for a specific method | - | `up://device1/AB34/1/12CD` | `\+/+/\+/+/device1/AB34/1/12CD`
| Receive all RPC Responses | - | `up://device1/AB34/1/0` | `\+/+/\+/+/device1/AB34/1/0`

|===

=== D2D Communication

[.specitem,oft-sid="dsn~up-transport-mqtt5-d2d-topic~1",oft-needs="impl,utest"]
--
The topic name of an MQTT 5 PUBLISH packet containing a UMessage that is published to an _off-vehicle_ broker **MUST** consist of the following segments:

`{source.authority_name}/{sink.authority_name}`
--

==== Examples

The MQTT 5 topic name used by uEntities with authority name `vehicle1` for sending any type of UMessage to uEntities with authority name `backend` via an _off-vehicle_ broker is

`vehicle1/backend`

The MQTT 5 topic filter used by uEntities with authority name `backend` for receiving all types of UMessages from uEntities with arbitrary authority names via an _off-vehicle_ broker is

`+/backend`

== Connection Handling

[.specitem,oft-sid="req~up-transport-mqtt5-establish-connection~1",oft-needs="impl,utest"]
--
Each `UTransport` implementation *MUST* provide means to configure the values for the `cleanSession` and `sessionExpiry` properties being used when establishing a connection to an MQTT broker.

The table below provides some guidance regarding the impact that different values for these properties have on message retainment and delivery.

[cols="1,1,3"]
|===
| cleanSession | sessionExpiry | Resulting behavior
| true | 0 | Previous session data is deleted and state like messages, subscriptions etc. is lost if UTransport gets disconnected
| true | t>0 | Previous session data is deleted and new session will buffer data for time `t` if connection is lost
| false | t | Previous session including subscribtions, unreceived messages etc. is resumed and session will buffer data for time `t` if connection is lost
|===

Using a UTransport from the cloud side to connect to an MQTT broker we recommend to use `cleanSession=true` and `sessionExpiry=0` because we assume that there will always be at least one UTransport connected from the cloud which can handle messages so there is no need for buffering. 

Establishing an mqtt5 UTransport from a device there is no general recommendation. Using `cleanSession=true` and `sessionExpiry=0` might be best for scaling since it reduces the load on the MQTT broker. Doing this one needs to take special care for offline devices. Using `cleanSession=true` and `sessionExpiry=t` might stress the broker but the broker helps when dealing with offline devices.

--

[.specitem,oft-sid="req~up-transport-mqtt5-reconnection~1",oft-needs="impl,utest"]
--
A `UTransport` implementation *MUST*

* re-establish a lost connection to an MQTT broker using an exponential backoff strategy.
* re-subscribe to all previously subscribed topics, if the broker indicates that no session is present after successful reconnection.

The following table provides some guidance for implementation:

[cols="2,1,1,1,1,1,1"]
|===
| Reconnect attempt | 1 | 2 | 3 | 4 | 5 | _n > 5_
| Backoff           | 500ms | 1s | 2s | 4s | 10s | 10s
|===

--
