= Transport & Session Layer (uP-L1)
:toc:
:sectnums:

The key words "*MUST*", "*MUST NOT*", "*REQUIRED*", "*SHALL*", "*SHALL NOT*", "*SHOULD*", "*SHOULD NOT*", "*RECOMMENDED*", "*MAY*", and "*OPTIONAL*" in this document are to be interpreted as described in https://www.rfc-editor.org/info/bcp14[IETF BCP14 (RFC2119 & RFC8174)]

----
Copyright (c) 2023 General Motors GTO LLC

Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.

SPDX-FileType: DOCUMENTATION
SPDX-FileCopyrightText: 2023 General Motors GTO LLC
SPDX-License-Identifier: Apache-2.0
----


Transport & Session Layer is responsible for bidirectional point-2-point communication between uEs. What gets sent between uEs vary considerably depending on the type of payload (Safety, Security, fire & forget, etc...) as well as the deployment environment where the uEs are located (Android, Linux, MCU, etc...). 

The Purpose of this layer of the protocol is to define a common ubiquitous language for sending and receiving a messages in a common way across transports, heterogeneous system the uEs are deployed on, or the programming language used. 

This specification shall define the data models (types) and interfaces.

uProtocol programming language specific libraries (SDKs) declare the transport layer interfaces and define the data model, while transport technologies (ex. Binder, MQTT, Zenoh, SOME/IP, DDS, HTTP, etc...) implement said interfaces per language. 

NOTE: We will define the various interfaces in this specification using pseudo code in lieu of a particular IDL such as protobuf as we expect the implementations of this spec to vary slightly between languages. 

We will use the following terminology during this document:

.API Definition Terminology
[width="80%",cols="20%,80%"]
|===
|Term | Description

| `IN` | Input parameter
| `OUT`| Output parameter
| `IN/OUT` | Input/output parameter
| `&` | Parameter passed by reference
| `Future` | Language specific mechanism to access the result of asynchronous operations, ex. https://en.cppreference.com/w/cpp/thread/future[`std::future`] for C++, https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/CompletableFuture.html[`CompletableFuture`] for Java, etc...

|===

 * All APIs that return `Status` *MUST* follow link:../basics/error_model.adoc[uProtocol Error Model]


NOTE: uProtocol data model used by the uTransport interface are declared in https://github.com/eclipse-uprotocol/uprotocol-core-api[uprotocol-core-api]

== Data Model

Data model specifies the various types declared in protobuf in the SDKs and used by uTransport interface.
These specifications define the ubiquitous language so that they are consistent across languages and transport implementations. 

*NOTE:* Unless otherwise stated, the classification or category for various types (ex. enums vs templates vs classes vs structs vs records, etc..) is not specified and left up to the SDK authors.

* Object oriented programming languages *MUST* use object based types (ex. classes) to represent the types defined in this section unless otherwise stated below

* Variable length types such as C++ `std::string` or Java's `byte[]` *MAY* be replaced for fixed types (ex. `char[]`) where applicable


=== UAttributes

NOTE: Please refer to https://github.com/eclipse-uprotocol/uprotocol-core-api/blob/main/src/main/proto/uattributes.proto[uattributes.proto] for the data model definition of the UAttributes type.

=== UPayload

UPayload is a container for the uP-L3 application layer data to be transmitted between uEs. The UPayload structure contains the data itself (either a reference or value), the size of the data, and a hint to indicate the serialization format (if any) of the data. 

 * `data` *MUST* contain the address to the payload and `size` contains the actual data size

If `data` primitive object includes size parameter then the `size` attribute can be ommitted from the UPayload type (ex. `byte[]` for Java):


==== UPayloadFormat

NOTE: Please refer to https://github.com/eclipse-uprotocol/uprotocol-core-api/blob/main/src/main/proto/upayload.proto[upayload.proto] for definition of UPayloadFormat.

=== UListener

`UListener` is an interface used for receiving messages by the client uE from the uTransport layer. Listeners are used for receiving messages asynchronously by the uTransport layer.  

  * Type name *MUST* be `UListener`
  * *MUST* contain the method `UStatus onReceive(link:../basics/uri.adoc[UUri]&, <<UPayload>>&, <<UAttributes>>&)` that is called by the Transport to notify (callback) the client

=== UStatus

An interface used to return the status of the uTransport API calls.

  * Type name *MUST* be `UStatus`
  * *MUST* contain the method `int getCode()` that returns the status code per the link:../basics/error_model.adoc[uProtocol Error Model]
  * *MUST* contain the method `string getMessage()` that returns the status message 



== uTransport Interface

The transport layer API responsible for point-2-point communication. The interface provides common functionality across all transport implementations.

* *MUST* implement all APIs defined in this section

=== Authenticate()

API used to verify the identity of the calling uE by confirming that the passed <<UEntity>> matches that of the transport layer specific identity required for link:../up-l2/permissions.adoc[Code-Based Access Permissions (CAPs)]. 

`OUT <<UStatus>> authenticate(IN <<UEntity>>)`

==== Parameters
.Register Parameters
[width="100%",cols="20%,80%"]
|===
|Parameter | Description

| `UEntity`
| uProtocol UEntity name and version used for identification verification

|===

 * *MUST* be called before any other uTransport APIs
 * *MUST* be idempotent, subsequent calls to the API return the same value
 * *MUST* authenticate client uE identity by ensuring that the <<UEntity>> matches the transport specific identity mechanism. 
 * Non authenticated uEs *MUST* be returned `UNAUTHENTICATED` status code


=== Send()

Publish/send <<UPayload>> and <<UAttributes>> to a link:../basics/uri.adoc[UUri] (topic). 


Communication protocols (a.k.a. uProtocol Transports) define their own Protocol Data Unit (PDU) that comprises of header and payload. Some transports header parameters map already to uProtocol <<UAttributes>>. Sending <<UAttributes>> in the transport's payload as well as in the header increases overhead for little to no gain. To address this issue,  <<Send()>> allows flexibility for uTransport implementers to define however they see fit what gets mapped into their transport header vs payload. 

For example, if HartleyTransport can map only <<UPriority>> to its PDU header, then HartleyTransport would define a PDU payload type that includes <<UPayload>> and all the other <<UAttributes>> and send that new type in its PDU payload such that the receiver will not loose any metadata. 

The API signature:

`OUT <<UStatus>> send(IN/OUT link:../basics/uri.adoc[UUri&], IN <<UPayload>>&, IN <<UAttributes>>&)`

==== Parameters
.Send Parameters
[width="100%",cols="20%,80%"]
|===
|Parameter | Description

| link:../basics/uri.adoc[UUri]

| Destination for the <<UPayload>>

| <<UPayload>>
a| Data to be sent

 * *MUST* be passed by reference

| <<UAttributes>>
a| <<UPayload>> metadata

 * *MUST* be passed by reference

|===

 * All <<UAttribute>> metadata *MUST* be preserved during transmission and available to the receiver
 * *MUST* not manipulate the <<UPayload>> data during transmission
 * Transport *MAY* modify the link:../basics/uri.adoc[UUri&] to set the transportId 

=== RegisterListener()

Register a <<UListener>> to receive message(s) for a given link:../basics/uri.adoc[UUri] (topic). This API is used to implement the _push_ <<Delivery Method>>.

API Signature: 

`OUT <<UStatus>> registerListener(IN link:../basics/uri.adoc[UUri], IN <<UListener>>&)`


 * *MUST* support registering more than one listener per topic
 * *MUST* support registering more than one topic per listener
 * Transport implementations *MUST* declare the maximum number of listeners per topic that it can support. If the maximum number of listeners is reached, the transport *MUST* return `RESOURCE_EXHAUSTED` status code


==== Parameters
.RegisterListener Parameters
[width="100%",cols="20%,80%"]
|===
|Parameter | Description

| link:../basics/uri.adoc[UUri]
| Topic to register the listener for

| <<UListener>>
| Listener to be registered

|===


=== UnregisterListener()

API used to unregister a <<UListener>> for a given topic.

API Signature: 

`OUT <<UStatus>> unregisterListener(IN link:../basics/uri.adoc[UUri], IN <<UListener>>&)`

==== Parameters
.UnregisterListener Parameters
[width="70%",cols="20%,80%"]
|===
|Parameter | Description

| link:../basics/uri.adoc[UUri]
| Topic to unregister the listener for

| <<UListener>>
| Listener to be unregistered

|===


=== Receive()

Implements the _pull_ <<Delivery Method>> to fetch a message from the transport for a given link:../basics/uri.adoc[UUri] (topic).

`OUT <<UStatus>> receive(IN link:../basics/uri.adoc[UUri], OUT <<UPayload>>&, OUT <<UAttributes>>&)`

==== Parameters
.Receive Parameters
[width="100%",cols="20%,80%"]
|===
|Parameter | Description

| link:../basics/uri.adoc[UUri]
| Topic to receive the message from

| <<UPayload>>
a| Data received

 * *MUST* be passed by reference

| <<UAttributes>>
a| Message metadata

 * *MUST* be passed by reference

|===

 * *MUST* return `NOT_FOUND` if there are no messages for the given topic


=== Message Delivery

==== Policy

* Transport *MUST* support https://www.cloudcomputingpatterns.org/at_least_once_delivery/[*At-least-once delivery policy*], this means that a sender *MUST* have a way to guarantee that the CE was successfully received by the Receiver (through the returned <<UStatus>>)
* Transport *MUST* support retransmission of CEs that are no able to be sent

If the uP-L1 transport layer is above https://en.wikipedia.org/wiki/OSI_model[OSI Session layer 5]:

* *MUST* use Transmission Control Protocols (TCP) and *MUST NOT* User Datagram Protocol (UDP) for message delivery

==== Delivery Method

* Transport *MUST* support either _push_ or _pull_ delivery method
* *MAY* support both _push_ or _pull_ delivery methods between uEs
* Delivery method *SHOULD* be known by uEs at design time
* Receivers *MAY* select which delivery method they prefer if the transport between sender and receiver supports more than one delivery method

NOTE: Delivery method advertising shall be defined later
