= Transport & Session Layer (uP-L1)
:toc: preamble
:sectnums:

The key words "*MUST*", "*MUST NOT*", "*REQUIRED*", "*SHALL*", "*SHALL NOT*", "*SHOULD*", "*SHOULD NOT*", "*RECOMMENDED*", "*MAY*", and "*OPTIONAL*" in this document are to be interpreted as described in https://www.rfc-editor.org/info/bcp14[IETF BCP14 (RFC2119 & RFC8174)]

----
SPDX-FileCopyrightText: 2023 Contributors to the Eclipse Foundation

See the NOTICE file(s) distributed with this work for additional
information regarding copyright ownership.

This program and the accompanying materials are made available under
the terms of the Apache License Version 2.0 which is available at
https://www.apache.org/licenses/LICENSE-2.0
 
SPDX-FileType: DOCUMENTATION
SPDX-License-Identifier: Apache-2.0
----

== Overview

The Transport & Session Layer is responsible for bidirectional point-2-point communication between uEntities (uE). 
The purpose of this layer of uProtocol is to define a common API for sending and receiving messages across different transport protocols like Eclipse Zenoh, MQTT 5 or Android Binder, runtime environments like Android, Linux or MCUs, and programming languages like Java, Rust, Python or C/C++.

This specification defines the transport layer's abstract API which is mapped to supported programming languages by means of uProtocol's xref:../languages.adoc[language specific libraries]. The API is _implemented_ for particular transport protocols and programming languages by _uProtocol Transport Libraries_.

The Transport Layer API is defined using UML2 notation.

[mermaid]
ifdef::env-github[[source,mermaid]]
----
classDiagram

class UTransport {
  <<interface>>
  send(message : UMessage)
  receive(sourceFilter: UUri, sinkFilter: UUri [0..1]) UMessage
  registerListener(sourceFilter: UUri, sinkFilter: UUri [0..1], listener: UListener)
  unregisterListener(sourceFilter: UUri, sinkFilter: UUri [0..1], listener: UListener)
}

class UListener {
  <<interface>>
  onReceive(message : UMessage)
}

class LocalUriProvider {
  <<interface>>
  getAuthority() String
  getSource() UUri
  getResource(id: UInt16) UUri
}

UTransport ..> UListener
----

NOTE: The data types used in the following sections are defined in xref:../basics/README.adoc[uProtocol Basic Types].

== UListener

A uEntity registers a `UListener` with the transport in order to process (incoming) messages that are of interest to the uEntity.

[.specitem,oft-sid="dsn~ulistener-declaration~1",oft-needs="impl",oft-tags="LanguageLibrary"]
--
Each language library *MUST* declare the UListener interface using corresponding programming language specific means.
--

[#on-receive]
=== OnReceive

A <<UTransport>> implementation invokes this method for each newly arrived message that matches the criteria specified during <<register-listener,registration of the listener>>.

[source]
----
onReceive(message: UMessage)
----

.onReceive Parameters
[width="100%",cols="1,1,5"]
|===
|Parameter | Type | Description

| message
| xref:../basics/umessage.adoc[UMessage]
| The newly received message.

|===

[mermaid]
ifdef::env-github[[source,mermaid]]
----
sequenceDiagram

participant L as listener:UListener
participant T as transport:UTransport

T-)L : onReceive(UMessage)
activate L
deactivate L
----

== UTransport

This is the main entry point into a transport's messaging functionality.

[.specitem,oft-sid="dsn~utransport-declaration~1",oft-needs="impl",oft-tags="LanguageLibrary"]
--
Each language library *MUST* declare the UTransport interface using corresponding programming language specific means.
--

[#send]
=== Send

Clients use this method to transmit a single message.

[source]
----
send(message: UMessage)
----

.Send Parameters
[width="100%",cols="1,1,5"]
|===
|Parameter | Type | Description

| message
| xref:../basics/umessage.adoc[UMessage]
| The message to send.
|===

The successful completion of this method means that the given message has been handed over to the underyling communication protocol's message delivery mechanism. For a hub-and-spoke based communication protocol like MQTT, this typically means that the `send` method implementation has received the MQTT `PUBACK` packet, which indicates that the message has been transferred successfully to the broker from where the message remains to be retrieved by potential recipients. For a peer-to-peer based protocol like HTTP, this typically means that the `send` method implementation has received the peer's HTTP response message, which indicates that the message has been transferred successfully to the peer's HTTP endpoint. Based on that, a client using this method should not assume that the given message has already reached its destination nor that it has already been processed once the method has completed successfully.

On the other hand, unsuccessful completion of this method does not necessarily mean that the given message has not been sent at all. For example, an MQTT based implementation might lose its connection to the MQTT broker _after_ it has sent its MQTT `PUBLISH` packet but _before_ it has received the broker's `PUBACK`. In such a case, clients should use the returned error to determine, if another attempt to send the message is feasible or not. For example, if the initial attempt to send the message has failed with a `UCode.INVALID_ARGUMENT`, then trying to send the same unaltered message again will most likely yield the same result. However, if the initial attempt failed with a `UCode.UNAVAILABLE`, then resending the message using some back-off mechanism will likely succeed eventually.

NOTE: The above strategy for retrying failed attempts to send a message results in https://www.cloudcomputingpatterns.org/at_least_once_delivery/[at-least-once delivery]. Recipient(s) of these messages should therefore be https://www.cloudcomputingpatterns.org/idempotent_processor/[Idempotent Processors].

UTransport implementations

[.specitem,oft-sid="req~utransport-send-preserve-data~1",oft-needs="dsn",oft-tags="TransportLayerImpl"]
--
* *MUST* preserve all of the message's meta data and payload during transmission
--

[.specitem,oft-sid="dsn~utransport-send-error-invalid-parameter~1",oft-needs="impl,utest",oft-tags="TransportLayerImpl"]
--
* *MUST* fail invocations of <<send>> with a `UCode.INVALID_ARGUMENT`, if the passed UMessage failed validation.
--

[.specitem,oft-sid="req~utransport-send-error-permission-denied~2",oft-needs="dsn,uman",oft-tags="TransportLayerImpl"]
--
* *MUST* fail invocations of <<send>> with a `UCode.PERMISSION_DENIED`, if a non-streamer client tries to send a message with a `UAttributes.source` that differs from the source address associated with the transport in anything but the _resource ID_. This is to avoid address spoofing.
+
In general, an implementation of this specification will run in the same process as the client code and thus has no way of objectively asserting the client's authorities _on its own_. However, most transports will support or require clients to provide credentials for authentication as part of establishing a connection or sending messages. Most transports (like MQTT brokers or Eclipse Zenoh) will also support the definition of rules for authorizing an authenticated client. These mechanisms *MAY* then be used to implement this requirement.
--

[.specitem,oft-sid="req~utransport-send-qos-mapping~1",oft-needs="dsn,uman",oft-tags="TransportLayerImpl"]
--
* *MUST* document if and how the implementation maps the xref:../basics/qos.adoc[UMessage Service Classes] to an existing corresponding mechanism for message prioritization of the underlying transport protocol.
+
NOTE: An implementation *MAY* also completely ignore the service class and handle all messages equally, regardless of service class.
--

[mermaid]
ifdef::env-github[[source,mermaid]]
----
sequenceDiagram

actor C as Client
participant T as transport:UTransport

C->>T : send(UMessage)
activate T
opt error while sending
Note right of T: message may or may<br>not have been sent
T--)C : error : Ustatus
end
deactivate T
----

[#receive]
=== Receive

Clients use this method to receive a single message matching given filter criteria.

[source]
----
receive(sourceFilter: UUri, sinkFilter: UUri [0..1]) : UMessage
----

.Receive Parameters
[width="100%",cols="1,1,5"]
|===
|Parameter | Type | Description

| sourceFilter
| xref:../basics/uri.adoc[UUri]
| The _source_ address pattern that messages need to match.

| sinkFilter
| xref:../basics/uri.adoc[UUri]
| The _sink_ address pattern that messages need to match. If omitted, a message **MUST NOT** contain any sink address in order to match.

| result
| xref:../basics/umessage.adoc[UMessage]
| The least recent message that matches the given filter criteria and has not expired yet.

|===

This method implements the _pull_ <<delivery-method, delivery method>> on top of the underlying communication protocol.

UTransport implementations

[.specitem,oft-sid="dsn~utransport-receive-error-unimplemented~1",oft-needs="impl,utest",oft-tags="TransportLayerImpl"]
--
* *MUST* fail invocations of <<receive>> with a `UCode.UNIMPLEMENTED`, if the transport does not support the _pull_ <<delivery-method, delivery method>>.
--

[.specitem,oft-sid="dsn~utransport-receive-error-notfound~1",oft-needs="impl,utest",oft-tags="TransportLayerImplPull"]
--
* *MUST* fail invocations of <<receive>> with a `UCode.NOT_FOUND`, if there are no matching messages available.
--

[mermaid]
ifdef::env-github[[source,mermaid]]
----
sequenceDiagram

actor C as Client
participant T as transport:UTransport

C->>T : receive(UUri, UUri)
activate T
alt pull not supported
T--)C : error : UStatus(UCode.UNIMPLEMENTED)
else no message available
T--)C : error : UStatus(UCode.NOT_FOUND)
else
T--)C : matching message : UMessage
end
deactivate T
----

[#register-listener]
=== RegisterListener

Clients use this method to register a listener for messages matching given filter criteria.

[source]
----
registerListener(sourceFilter: UUri, sinkFilter: UUri [0..1], listener: UListener)
----

.registerListener Parameters
[width="100%",cols="1,1,5"]
|===
|Parameter | Type | Description

| sourceFilter
| xref:../basics/uri.adoc[UUri]
| The _source_ address pattern that messages need to match.

| sinkFilter
| xref:../basics/uri.adoc[UUri]
| The _sink_ address pattern that messages need to match. If omitted, a message must not contain any sink address in order to match.

| listener
| <<UListener>>
| The listener to be registered.
|===

This API is used to implement the _push_ <<delivery-method, delivery method>> on top of the underlying communication protocol.

UTransport implementations

[.specitem,oft-sid="dsn~utransport-registerlistener-error-unimplemented~1",oft-needs="impl,utest",oft-tags="TransportLayerImpl"]
--
* *MUST* fail invocations of <<register-listener>> with a `UCode.UNIMPLEMENTED` if the transport does not support the _push_ <<delivery-method, delivery method>>. In that case, the <<unregister-listener, unregisterListener>> method *MUST* also fail accordingly.
--

[.specitem,oft-sid="req~utransport-registerlistener-max-listeners~1",oft-needs="impl,utest,uman",oft-tags="TransportLayerImplPush"]
--
* *MUST* provide means to configure upper limits for
** the overall number of listeners that can be registered and
** the number of listeners that can be registered per address filter pattern.
* *SHOULD* use a reasonable default value for both limits.
--

[.specitem,oft-sid="dsn~utransport-registerlistener-error-resource-exhausted~1",oft-needs="impl,utest",oft-tags="TransportLayerImplPush"]
--
* *MUST* fail invocations of <<register-listener>> with a `UCode.RESOURCE_EXHAUSTED`, if the maximum number of listeners supported by the transport has already been registered.
--

[.specitem,oft-sid="dsn~utransport-registerlistener-error-invalid-parameter~1",oft-needs="impl,utest",oft-tags="TransportLayerImplPush"]
--
* *MUST* fail invocations of <<register-listener>> with a `UCode.INVALID_ARGUMENT`, if the source and sink filter arguments' resource IDs do not match any of the entries from the table below:
+
[#valid-source-sink-filters]
.Valid Source/Sink Resource IDs
[cols="4,^1,^1"]
|===
| Use Case | source `resource_id` | sink `resource_id`

| Listen for events published to a particular topic | [8000-FFFE] | None
| Listen for events published to any topic | FFFF | None
| Listen for notifications from a specific resource | [8000-FFFE] | 0
| Listen for RPC requests to a specific operation | 0 | [1-7FFF]
| Listen for RPC responses from a specific operation | [1-7FFF] | 0
| Listen for all incoming notifications and responses | FFFF | 0
| Listen for all incoming notifications, RPC requests, and responses | FFFF | FFFF
|===
--

[.specitem,oft-sid="dsn~utransport-registerlistener-number-of-listeners~1",oft-needs="impl,utest",oft-tags="TransportLayerImplPush"]
--
* *MUST* support registering more than one listener for any given address filter patterns
--
  
[.specitem,oft-sid="dsn~utransport-registerlistener-listener-reuse~1",oft-needs="impl,utest",oft-tags="TransportLayerImplPush"]
--
* *MUST* support registering the same listener for multiple address filter patterns
--

[.specitem,oft-sid="dsn~utransport-registerlistener-idempotent~1",oft-needs="impl,utest",oft-tags="TransportLayerImplPush"]
--
* *MUST* make sure that multiple calls to <<register-listener>> with the same parameters have the same effect as a single call.
--

[.specitem,oft-sid="dsn~utransport-registerlistener-start-invoking-listeners~1",oft-needs="impl,utest",oft-tags="TransportLayerImplPush"]
--
* *MUST* deliver matching messages to a successfully registered listener. This means that for each message that the transport receives _after_ <<register-listener>> has completed successfully, and which matches the listener's source and sink filter criteria according to the xref:../basics/uri.adoc#pattern-matching[UUri pattern matching rules], the transport *MUST* invoke the listener's <<on-receive>> method _at least once_.
--


.Registering a Listener
[mermaid]
ifdef::env-github[[source,mermaid]]
----
sequenceDiagram

actor C as Client
participant T as transport:UTransport

C->>T : register(UUri, UUri, UListener)
activate T
opt error
alt push not supported
T--)C : error : UStatus(UCode.UNIMPLEMENTED)
else invalid filter syntax
T--)C : error : UStatus(UCode.INVALID_ARGUMENT)
else max listeners exceeded
T--)C : error : UStatus(UCode.RESOURCE_EXHAUSTED)
else other
T--)C : error : UStatus
end
end
deactivate T
----

Sometimes it's necessary to distinguish the message types which should be listened to.

[%autowidth]
|===
| Message Type | Possible resource ID combinations `{source resource_id, sink resource_id}`

| Publish      | {[8000-FFFE], None}
| Notification | {[8000-FFFE], 0}, {FFFF, 0}, {FFFF, FFFF}
| Request      | {0, [1-7FFF]}, {FFFF, FFFF}
| Response     | {[1-7FFF], 0}, (FFFF, 0), {FFFF, FFFF}
|===

[#unregister-listener]
=== UnregisterListener

Clients use this method to unregister a previously registered listener.

[source]
----
unregisterListener(sourceFilter: UUri, sinkFilter: UUri [0..1], listener: UListener)
----

.RegisterListener Parameters
[width="100%",cols="1,1,5"]
|===
|Parameter | Type | Description

| sourceFilter
| xref:../basics/uri.adoc[UUri]
| The source address pattern that the listener had been registered for.

| sinkFilter
| xref:../basics/uri.adoc[UUri]
| The sink address pattern that the listener had been registered for.

| listener
| <<UListener>>
| The listener to be unregistered.
|===

UTransport implementations

[.specitem,oft-sid="dsn~utransport-unregisterlistener-error-unimplemented~1",oft-needs="impl,utest",oft-tags="TransportLayerImpl"]
--
* *MUST* fail invocations of <<unregister-listener>> with a `UCode.UNIMPLEMENTED`, if the transport does not support the _push_ <<delivery-method>>. In that case, the <<register-listener>> method *MUST* also fail accordingly.
--

[.specitem,oft-sid="dsn~utransport-unregisterlistener-error-notfound~1",oft-needs="impl,utest",oft-tags="TransportLayerImplPush"]
--
* *MUST* fail invocations of <<unregister-listener>> with a `UCode.NOT_FOUND`, if no such listener had been registered before.
--

[.specitem,oft-sid="dsn~utransport-unregisterlistener-error-invalid-parameter~1",oft-needs="impl,utest",oft-tags="TransportLayerImplPush"]
--
* *MUST* fail invocations of <<unregister-listener>> with a `UCode.INVALID_ARGUMENT`, if the source and sink filter arguments' resource IDs do not match any of entries from <<valid-source-sink-filters>>.
--

[.specitem,oft-sid="dsn~utransport-unregisterlistener-stop-invoking-listeners~1",oft-needs="impl,utest",oft-tags="TransportLayerImplPush"]
--
* *MUST NOT* deliver any messages to a successfully unregistered listener.
--

.Unregistering a Listener
[mermaid]
ifdef::env-github[[source,mermaid]]
----
sequenceDiagram

actor C as Client
participant T as transport:UTransport

C->>T : unregister(UUri, UUri, UListener)
activate T
opt error
alt push not supported
T--)C : error : UStatus(UCode.UNIMPLEMENTED)
else no such listener
T--)C : error : UStatus(UCode.NOT_FOUND)
else invalid filter syntax
T--)C : error : UStatus(UCode.INVALID_ARGUMENT)
else other
T--)C : error : UStatus
end
end
deactivate T
----

== LocalUriProvider

A uEntity can use the `LocalUriProvider` to create URIs representing the uEntity's local resources during runtime. This information can then be used in messages to be sent to other uEntities.

A `UTransport` implementation can use the `LocalUriProvider` to determine the uEntity's authority during runtime. This information might be useful for normalizing _local_ URIs passed into the Transport Layer API methods which do not contain an _authority name_.

[.specitem,oft-sid="dsn~localuriprovider-declaration~1",oft-needs="impl",oft-tags="LanguageLibrary"]
--
Each language library *MUST* declare the LocalUriProvider interface using corresponding programming language specific means.
--

=== GetAuthority

A uEntity invokes this method to get its own authority.

[.specitem,oft-sid="dsn~localuriprovider-getauthority~1",oft-needs="impl,utest",oft-tags="LocalUriProvider"]
--
The value returned by an implementation *MUST* be the uEntity's (fixed) local _authority name_.
Implementations *MAY* use any appropriate mechanism to determine the local authority during runtime, e.g. by means of a configuration file, environment variables or a central registry.
--

=== GetSource

A uEntity invokes this method to get the address that it expects incoming Notification or RPC Response messages to be sent to.

[.specitem,oft-sid="dsn~localuriprovider-getsource-uri-segments~1",oft-needs="impl,utest",oft-tags="LocalUriProvider"]
--
The address returned by an implementation *MUST* consist of the uEntity's (fixed) _authority_, _identifier_, _major version_ and _resource ID_ `0x0000`.
Implementations *MAY* use any appropriate mechanism to determine these values during runtime, e.g. by means of a configuration file, environment variables or a central registry.
--

=== GetResource

A uEntity invokes this method to get a resource specific address to publish messages to or that it expects incoming RPC Request messages to be sent to.

[.specitem,oft-sid="dsn~localuriprovider-getresource~1",oft-needs="impl,utest",oft-tags="LocalUriProvider"]
--
The address returned by an implementation *MUST* consist of the uEntity's (fixed) _authority_, _identifier_, _major version_ and the passed in _resource ID_.
Implementations *MAY* use any appropriate mechanism to determine these values during runtime, e.g. by means of a configuration file, environment variables or a central registry.
--

== Message Delivery

uProtocol distinguishes between the following message delivery methods:

[#delivery-method]
.Message Delivery Methods
[cols="1,7"]
|===
|Method |Definition

|https://peterdaugaardrasmussen.com/2021/02/26/polling-vs-pushing-data/[*Push*]
|Data is pushed by the sender to the receiver.


|https://peterdaugaardrasmussen.com/2021/02/26/polling-vs-pushing-data/[*Pull/Poll*]
|Data is pulled in by the receiver. This is done periodically at certain intervals, because the receiver (usually) does not know when new data will be available.

|===

UTransport implementations

[.specitem,oft-sid="req~utransport-delivery-methods~1",oft-needs="dsn,uman",oft-tags="TransportLayerImpl"]
--
* *MUST* support at least one of _push_ or _pull_ delivery methods and *MAY* support both.
--


== Communication Protocol Binding

Communication protocols like MQTT or HTTP define a specific Protocol Data Unit (PDU) for conveying control information and user data. A uProtocol Client implements the Transport Layer API defined above on top of such a communication protocol.

A _communication protocol binding_ defines how the uProtocol Transport Layer API maps to the communication protocol's message exchange pattern(s) and how uProtocol messages are mapped to the protocol's PDU. Many communication protocols distinguish between a message's metadata and the (raw) payload. This is often reflected by the structure of the protocol's PDU. For example, HTTP supports _header_ fields and a _body_ which can be used to convey a uProtocol message's attributes and payload respectively.

uProtocol currently defines bindings to the following communication protocols:

* xref:zenoh.adoc[*Eclipse Zenoh*]
* xref:mqtt_5.adoc[*MQTT 5*]
* xref:someip.adoc[*SOME/IP*]
