= Zenoh
:toc:
:sectnums:

The key words "*MUST*", "*MUST NOT*", "*REQUIRED*", "*SHALL*", "*SHALL NOT*", "*SHOULD*", "*SHOULD NOT*", "*RECOMMENDED*", "*MAY*", and "*OPTIONAL*" in this document are to be interpreted as described in https://www.rfc-editor.org/info/bcp14[IETF BCP14 (RFC2119 & RFC8174)]

----
Copyright (c) 2024 ZettaScale Technology

Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.

SPDX-FileType: DOCUMENTATION
SPDX-FileCopyrightText: 2024 ZettaScale Technology
SPDX-License-Identifier: Apache-2.0
----

== Overview

Zero Overhead Network Protocol.

Zenoh /zeno/ is a pub/sub/query protocol unifying data in motion, data at rest and computations. It elegantly blends traditional pub/sub with geo distributed storage, queries and computations, while retaining a level of time and space efficiency that is well beyond any of the mainstream stacks.

For more information, please visit https://projects.eclipse.org/projects/iot.zenoh or https://zenoh.io/

== Specifications

=== UAttribute Mapping

Zenoh supports user attachment.
We **MUST** send additional information with the mechanism, for example, UAttribute.
This reduces the unnecessary serialization on payload, which mostly takes time.

User attachment supports key-value pairs, and the following table is the key-value pairs using now.

[cols="1,1"]
|===
| key | value

| "uattr"
| UAttribute object encoded into protobuf
|===

Besides the user attachment, some features in the UAttribute **SHOULD** be mapped into Zenoh transport settings.

==== Message Type

There are 3 kinds of message types in uProtocol (publish, request, response).
Different message types **MUST** use different Zenoh API.

[cols="1,1"]
|===
| uProtocol message type | Zenoh API

| publish | put
| request | get (query)
| response | reply (queryable)
|===

==== Priority Mapping (uProtocol to Zenoh):

[cols="1,1"]
|===
| uProtocol priority | Zenoh Priority

| CS0 | BACKGROUND
| CS1 | DATA_LOW
| CS2 | DATA
| CS3 | DATA_HIGH
| CS4 | INTERACTIVE_LOW
| CS5 | INTERACTIVE_HIGH
| CS6 | REAL_TIME
|===

=== URI Mapping

UUri **MUST** be able to be serialized into link:../basics/uri.adoc#42-micro-uris[micro form].
Then we can transform the micro-form UUri, which is `u8` array, into string in lowercase hexadecimal representation.

Zenoh key for uProtocol consists of three parts and they are separated by `/`.
Zenoh key **MUST** start with `up/`.
If UAuthority is defined in UUri, it **MUST** be put in the second part.
Then the rest of the UUri **MUST** be put in the last part.

To be more specific:

* UUri without UAuthority: `up/[byte representation of the UUri]`
* UUri with UAuthority: `up/[byte representation of the UAuthority]/[byte representation of the rest of the UUri]`

Note that there is a special case. If the UUri only contains UAuthority with empty UEntity and UResource,
it's defined as a special form of Zenoh key `up/[byte representation of UAuthority]/**`.
It can listen to all the messages sending to a certain UAuthority.

Some examples:

* UUri without UAuthority:

[source]
----
UUri {
  authority: empty,
  entity: UEntity {
    name: "body.access",
    version_major: 1,
    id: 1234,
  }
  resource: UResource {
    name: "door",
    instance: "front_left",
    message: "Door",
    id: 5678,
  }
}
----

There is no UAuthority, which means it's a local URI, so we leave the second part blank.
Only ID in UEntity and UResource matters while serializing into link:../basics/uri.adoc#421-local-micro-uri[micro-form Uri].
Then transform it into lowercase hexadecimal representation.
The Zenoh key is `up/0100162e04d20100`.

* UUri with UAuthority

[source]
----
UUri {
  authority: UAuthority {
    name: UAuthName,
    number: Id({01, 02, 03, 10, 11, 12})
  },
  entity: empty,
  resource: empty,
}
----

The UAuthority is serialized into mirco form.
Given how a UAuthority containing an ID is serialized into micro form as outlined in link:../basics/uri.adoc#422-remote-micro-uris[the spec],
it is length + serialized UUri in lowercase hexadecimal representation, which is `06` + `0102030a0b0c`.
The UEntity and UResource are all blank, so it is the special form UUri.
It means that the third part is `+++**+++`.
Therefore, the Zenoh key is `up/060102030a0b0c/+++**+++`.

=== UPayload

Although UPayload can be encoded into protobuf, it saves a lot of time without encoding.
UPayload consists of three parts: length, format, data.

* Length only works with shared memory, and we ignore it temporarily.
* Format **SHOULD** be sent with Zenoh encoding. Zenoh supports `Encoding::WithSuffix`. The encoding here is `KnownEncoding::AppCustom` and the UPayloadFormat (int32) is transformed into the string.

[source, rust]
----
Encoding::WithSuffix(
    KnownEncoding::AppCustom,
    payload.format.value().to_string().into(),
)
----

* Zenoh takes data as a buffer simply and sends it directly. Ignore the shared memory (reference) temporarily.
