= Zenoh
:toc:
:sectnums:

The key words "*MUST*", "*MUST NOT*", "*REQUIRED*", "*SHALL*", "*SHALL NOT*", "*SHOULD*", "*SHOULD NOT*", "*RECOMMENDED*", "*MAY*", and "*OPTIONAL*" in this document are to be interpreted as described in https://www.rfc-editor.org/info/bcp14[IETF BCP14 (RFC2119 & RFC8174)]

----
Copyright (c) 2023 General Motors GTO LLC

Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.

SPDX-FileType: DOCUMENTATION
SPDX-FileCopyrightText: 2023 General Motors GTO LLC
SPDX-License-Identifier: Apache-2.0
----

== Overview

Zero Overhead Network Protocol.

Zenoh /zeno/ is a pub/sub/query protocol unifying data in motion, data at rest and computations. It elegantly blends traditional pub/sub with geo distributed storage, queries and computations, while retaining a level of time and space efficiency that is well beyond any of the mainstream stacks.


for more information, please visit https://projects.eclipse.org/projects/iot.zenoh or https://zenoh.io/

== Specifications

=== Zenoh Config

TODO: How to add Zenoh config

=== Attribute Mapping

Zenoh supports user attachment.
We can send additional information with the mechanism, for example, UAttribute.
This can reduce the unnecessary serialization on payload, which mostly takes time.

User attachment supports key-value pairs, and the following table is the key-value pairs using now.

[cols="1,1"]
|===
| key | value

| "uattributes"
| UAttribute object encoded into protobuf
|===

Besides the user attachment, some features in the uAttribute can be mapped into Zenoh transport settings.

==== Priority Mapping (uProtocol to Zenoh):

[cols="1,1"]
|===
| uProtocol priority | Zenoh Priority

| CS0 | BACKGROUND
| CS1 | DATA_LOW
| CS2 | DATA
| CS3 | DATA_HIGH
| CS4 | INTERACTIVE_LOW
| CS5 | INTERACTIVE_HIGH
| CS6 | REAL_TIME
|===

Note that the priority in Zenoh only works for publisher.

=== URI Mapping

TODO: Use micro-form for UURI

=== UPayload

Although UPayload can be encoded into protobuf, it can save a lot of time without encoding.
UPayload consists of three parts: length, format, data.

* Length should only work with shared memory, and we ignore it temporarily.
* Format can be sent with Zenoh encoding. Zenoh supports `Encoding::WithSuffix`. The type here should be `KnownEncoding::AppCustom` and the int32 format is transformed into the string.

[source, rust]
----
Encoding::WithSuffix(
    KnownEncoding::AppCustom,
    payload.format.to_string().into(),
)
----

* Zenoh takes data as a buffer simply and sends it directly. Ignore the shared memory (reference) temporarily.
