= Zenoh
:toc: preamble
:sectnums:

The key words "*MUST*", "*MUST NOT*", "*REQUIRED*", "*SHALL*", "*SHALL NOT*", "*SHOULD*", "*SHOULD NOT*", "*RECOMMENDED*", "*MAY*", and "*OPTIONAL*" in this document are to be interpreted as described in https://www.rfc-editor.org/info/bcp14[IETF BCP14 (RFC2119 & RFC8174)]

----
SPDX-FileCopyrightText: 2024 Contributors to the Eclipse Foundation

See the NOTICE file(s) distributed with this work for additional
information regarding copyright ownership.

This program and the accompanying materials are made available under
the terms of the Apache License Version 2.0 which is available at
https://www.apache.org/licenses/LICENSE-2.0
 
SPDX-FileType: DOCUMENTATION
SPDX-License-Identifier: Apache-2.0
----

== Overview

https://zenoh.io[Eclipse Zenoh&trade;] (/zeno/) is a pub/sub/query protocol unifying data in motion, data at rest and computations. It elegantly blends traditional pub/sub with geo distributed storage, queries and computations, while retaining a level of time and space efficiency that is well beyond any of the mainstream stacks.

This document defines how uProtocol messages can be exchanged by means of Zenoh _Resources_.

== Zenoh Version

[.specitem,oft-sid="dsn~up-transport-zenoh-protocol-version~1",oft-needs="impl",oft-tags="TransportLayerImpl"]
--
Each transport implementing this specification **MUST** use major version `1` of the Zenoh protocol in order to ensure interoperability of different language libraries.
--

== UMessage Mapping

A uProtocol message consists of _UAttributes_ and optional payload. The following sections define how these are mapped to/from Zenoh Resources.

=== UAttributes

[.specitem,oft-sid="dsn~up-transport-zenoh-attributes-mapping~1",oft-needs="impl,utest",oft-tags="TransportLayerImpl"]
--
The value of a Zenoh Resource that is used to convey a uProtocol message *MUST* contain _attachments_ as defined in <<uAttributes Mapping to Zenoh Attachments>>.
--

.uAttributes Mapping to Zenoh Attachments
[%autowidth]
|===
| order | value

| 1
a| *MUST* be set to a single byte representing the UProtocol major version (`0x01` at the time of writing)

| 2
a| *MUST* be set to the bytes representing the protobuf encoding of the UAttributes object as defined by link:../up-core-api/uprotocol/v1/uattributes.proto

|===


==== Message Type


[.specitem,oft-sid="dsn~up-transport-zenoh-message-type-mapping~1",oft-needs="impl,utest",oft-tags="TransportLayerImpl"]
--
All types of uProtocol messages *MUST* be transferred using Zenoh's pub/sub API only. Zenoh's Queryable API *MUST NOT* be used.
--

==== Message Priority

[.specitem,oft-sid="dsn~up-transport-zenoh-message-priority-mapping~1",oft-needs="impl,utest",oft-tags="TransportLayerImpl"]
--
The uProtocol and Zenoh message priority levels *MUST* be mapped according to the following table:

[cols="1,1"]
|===
| uProtocol Priority | Zenoh Priority

| `CS0` | `BACKGROUND`
| `CS1` | `DATA_LOW`
| `CS2` | `DATA`
| `CS3` | `DATA_HIGH`
| `CS4` | `INTERACTIVE_LOW`
| `CS5` | `INTERACTIVE_HIGH`
| `CS6` | `REAL_TIME`
|===
--

=== Payload Mapping

[.specitem,oft-sid="dsn~up-transport-zenoh-payload-mapping~1",oft-needs="impl,utest",oft-tags="TransportLayerImpl"]
--
A Zenoh message that is used to convey a uProtocol message *MUST* contain in its payload the unaltered value of the UMessage's _payload_ field.
--

== Zenoh Key Structure

Message producers publish messages to the Zenoh network using _keys_. Other clients can indicate their interest in particular keys or patterns in order to receive the messages that are being published using matching keys.

The Zenoh _key expression_ that is used to transfer a uProtocol message is derived from the message's `source` and `sink` attributes.

[.specitem,oft-sid="dsn~up-transport-zenoh-key-expr~1",oft-needs="impl,utest",oft-tags="TransportLayerImpl"]
--
The key expression of a Zenoh message containing a _Publish_ UMessage **MUST** consist of the following segments:

`up/[source.authority]/[source.ue_type]/[source.ue_instance]/[source.ue_version]/[source.resource]/{}/{}/{}/{}/{}`

The key expression of a Zenoh message containing a _Notification_, _RPC Request_ or _RPC Response_ UMessage **MUST** consist of the following segments:

`up/[source.authority]/[source.ue_type]/[source.ue_instance]/[source.ue_version]/[source.resource]/[sink.authority]/[sink.ue_type]/[sink.ue_instance]/[sink.ue_version]/[sink.resource]`

Please refer to <<UUri Encoding Rules>> for details regarding the encoding of the `source` and `sink` UUris into the key expression's segments.
--

=== UUri Encoding Rules

The table below contains the rules for encoding a UUri's fields into a Zenoh key expression's segments.

[cols="2,2,6"]
|===
| Key Expression Segment
| UUri Field
| Encoding

|`authority`
|`authority_name`
a| The segment *MUST* contain the (UTF8) string representation of the 

1. `*` (`U+002A`, Asterisk) character, if the authority name is the xref:../basics/uri.adoc#pattern-matching[wildcard authority].
2. name of the host/authority that the (local) uEntity is running on, if authority name is empty.
3. authority name, otherwise.

|`ue_type`
|`ue_id`
a| The segment *MUST* contain the (UTF8) string representation of the

1. `*` (`U+002A`, Asterisk) character, if the uEntity type identifier is the xref:../basics/uri.adoc#pattern-matching[wildcard type ID].
2. the upper-case link:https://www.rfc-editor.org/rfc/rfc4648#section-8[base16 encoding] of the uEntity type identifier with all leading `0` characters omitted.

|`ue_instance`
|`ue_id`
a| The segment *MUST* contain the (UTF8) string representation of the

1. `*` (`U+002A`, Asterisk) character, if the uEntity instance identifier is the xref:../basics/uri.adoc#pattern-matching[wildcard instance ID].
2. the upper-case link:https://www.rfc-editor.org/rfc/rfc4648#section-8[base16 encoding] of the uEntity instance identifier with all leading `0` characters omitted.

|`ue_version`
|`ue_version_major`
a| The segment *MUST* contain the (UTF8) string representation of the

1. `*` (`U+002A`, Asterisk) character, if the uEntity major version is the xref:../basics/uri.adoc#pattern-matching[wildcard version].
2. the upper-case link:https://www.rfc-editor.org/rfc/rfc4648#section-8[base16 encoding] of the uEntity major version with all leading `0` characters omitted.

|`resource`
|`resource_id`
a| The segment *MUST* contain the (UTF8) string representation of the

1. `*` (`U+002A`, Asterisk) character, if the resource identifier is the xref:../basics/uri.adoc#pattern-matching[wildcard resource ID].
2. the upper-case link:https://www.rfc-editor.org/rfc/rfc4648#section-8[base16 encoding] of the resource identifier with all leading `0` characters omitted.

|===

=== Examples

The examples below assume that the local entity's authority name is `device1`.

.Publishing an event on a topic
--
[cols="2,8"]
|===
|*Source URI*
|`up:/10AB/3/80CD`

|*Sink URI*
|-

|*Zenoh Key*
|`up/device1/10AB/0/3/80CD/{}/{}/{}/{}/{}`
|===
--

.Sending a Notification to another uEntity
--
[cols="2,8"]
|===
|*Source URI*
|`up://device1/10AB/3/80CD`

|*Sink URI*
|`up://device2/300EF/4/0`

|*Zenoh Key*
|`up/device1/10AB/0/3/80CD/device2/EF/3/4/0`
|===
--

.Sending an RPC Request to a service provider
--
[cols="2,8"]
|===
|*Source URI*
|`up:/403AB/3/0`

|*Sink URI*
|`up://device2/CD/4/B`

|*Zenoh Key*
|`up/device1/3AB/4/3/0/device2/CD/0/4/B`
|===
--

.Subscribe to a specific topic
--
[cols="2,8"]
|===
|*Source Filter*
|`up://device2/10AB/3/80CD`

|*Sink Filter*
|-

|*Zenoh Key*
|`up/device2/10AB/0/3/80CD/{}/{}/{}/{}/{}`
|===
--

.Receive all Notifications for a local uEntity instance
--
[cols="2,8"]
|===
|*Source Filter*
|`up://+++*+++/FFFFFFFF/FF/FFFF`

|*Sink Filter*
|`up:/300EF/4/0`

|*Zenoh Key*
|`up/+++*+++/+++*+++/+++*+++/+++*+++/+++*+++/device1/EF/3/4/0`
|===
--

.Receive all RPC Requests from all instances of a specific uEntity type
--
[cols="2,8"]
|===
|*Source Filter*
|`up://+++*+++/FFFF05A1/2/FFFF`

|*Sink Filter*
|`up://device1/300EF/4/B18`

|*Zenoh Key*
|`up/+++*+++/5A1/+++*+++/2/+++*+++/device1/EF/3/4/B18`
|===
--

.Receive all messages destined to the local authority
--
[cols="2,8"]
|===
|*Source Filter*
|`up://+++*+++/FFFFFFFF/FF/FFFF`

|*Sink Filter*
|`up://device1/FFFFFFFF/FF/FFFF`

|*Zenoh Key*
|`up/+++*+++/+++*+++/+++*+++/+++*+++/+++*+++/device1/+++*+++/+++*+++/+++*+++/+++*+++`
|===
--
