= Zenoh
:toc:
:sectnums:

The key words "*MUST*", "*MUST NOT*", "*REQUIRED*", "*SHALL*", "*SHALL NOT*", "*SHOULD*", "*SHOULD NOT*", "*RECOMMENDED*", "*MAY*", and "*OPTIONAL*" in this document are to be interpreted as described in https://www.rfc-editor.org/info/bcp14[IETF BCP14 (RFC2119 & RFC8174)]

----
Copyright (c) 2024 ZettaScale Technology

Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.

SPDX-FileType: DOCUMENTATION
SPDX-License-Identifier: Apache-2.0
----

== Overview

Zero Overhead Network Protocol.

Zenoh /zeno/ is a pub/sub/query protocol unifying data in motion, data at rest and computations. It elegantly blends traditional pub/sub with geo distributed storage, queries and computations, while retaining a level of time and space efficiency that is well beyond any of the mainstream stacks.

For more information, please visit https://projects.eclipse.org/projects/iot.zenoh or https://zenoh.io/

== Specifications

=== Zenoh Version

We **MUST** use Zenoh version `0.10.1-rc` to ensure the interoperability in different language bindings.

=== UAttribute Mapping

Zenoh supports user attachment.
We **MUST** send additional information with the mechanism, for example, UAttribute.
This reduces the unnecessary serialization on payload, which mostly takes time.

User attachment supports non-unique key-value pairs, which means one key can include several values.
In this case, the order of the values matters.
To decrease the network overhead, we **MUST** keep the key empty and put the value in the order according to the following table.

[cols="1,1"]
|===
| order | value

| 1
| UAttribute version (1 byte)
| 2
| UAttribute object encoded into protobuf
|===

We use 1 byte to represent the UAttribute version.
The version field will keep the flexibility of updating UAttribute in the future.
Now the version is always 0x01.

==== Message Type

There are 4 kinds of message types in uProtocol (publish, notification, request, response).
Different message types **MUST** use different Zenoh API.

[cols="1,1"]
|===
| uProtocol message type | Zenoh API

| publish | put
| notification | put
| request | get (query)
| response | reply (queryable)
|===

==== Priority Mapping (uProtocol to Zenoh):

[cols="1,1"]
|===
| uProtocol priority | Zenoh Priority

| CS0 | BACKGROUND
| CS1 | DATA_LOW
| CS2 | DATA
| CS3 | DATA_HIGH
| CS4 | INTERACTIVE_LOW
| CS5 | INTERACTIVE_HIGH
| CS6 | REAL_TIME
|===

=== URI Mapping

UUri **MUST** be able to be serialized into link:../basics/uri.adoc#42-micro-uris[micro form].
Then we can transform the micro-form UUri, which is `u8` array, into string in lowercase hexadecimal representation.

Zenoh key for uProtocol consists of three parts and they are separated by `/`.
Zenoh key **MUST** start with `upl/` or `upr/`.
While the local UUri maps to `upl/`, the remote UUri maps to `upr/`.
If UAuthority is defined in UUri, it **MUST** be put in the second part.
Then the rest of the UUri **MUST** be put in the last part.

To be more specific:

* The local UUri without UAuthority: `upl/[hexadecimal representation of the UUri]`
* The remote UUri with UAuthority: `upr/[hexadecimal representation of the UAuthority]/[hexadecimal representation of the rest of the UUri]`

Note that there is a special case. If the UUri only contains UAuthority with empty UEntity and UResource,
it's defined as a special form of Zenoh key `upr/[byte hexadecimal of UAuthority]/**`.
It can listen to all the messages sending to a certain UAuthority.

Some examples:

* The local UUri without UAuthority:

[source]
----
UUri {
  authority: empty,
  entity: UEntity {
    name: "body.access",
    version_major: 1,
    id: 1234,
  }
  resource: UResource {
    name: "door",
    instance: "front_left",
    message: "Door",
    id: 5678,
  }
}
----

It's a local UUri, so it starts with `upl`.
Also, we leave the second part blank since it doesn't have UAuthority.
Only ID in UEntity and UResource matters while serializing into link:../basics/uri.adoc#421-local-micro-uri[micro-form Uri].
Then transform it into lowercase hexadecimal representation.
The Zenoh key is `upl/0100162e04d20100`.

* The remote UUri with UAuthority

[source]
----
UUri {
  authority: UAuthority {
    name: UAuthName,
    number: Id({01, 02, 03, 10, 11, 12})
  },
  entity: empty,
  resource: empty,
}
----

It's a remote UUri, so it starts with `upr`.
The UAuthority is serialized into mirco form.
Given how a UAuthority containing an ID is serialized into micro form as outlined in link:../basics/uri.adoc#422-remote-micro-uris[the spec],
it is length + serialized UUri in lowercase hexadecimal representation, which is `06` + `0102030a0b0c`.
The UEntity and UResource are all blank, so it is the special form UUri.
It means that the third part is `+++**+++`.
Therefore, the Zenoh key is `upr/060102030a0b0c/+++**+++`.

=== UPayload

Although UPayload can be encoded into protobuf, it saves a lot of time without encoding.
UPayload consists of three parts: length, format, data.

* Length only works with shared memory, and we ignore it temporarily.
* Format **SHOULD** be sent with Zenoh encoding. Zenoh supports `Encoding::WithSuffix`. The encoding here is `KnownEncoding::AppCustom` and the UPayloadFormat (int32) is transformed into the string.

[source, rust]
----
Encoding::WithSuffix(
    KnownEncoding::AppCustom,
    payload.format.value().to_string().into(),
)
----

* Zenoh takes data as a buffer simply and sends it directly. Ignore the shared memory (reference) temporarily.

=== Work Flow

The section provides the details how it works in different message types.

==== Transfer Publish message

1. A uEntity (`origin-authority/origin-entity`) creates a message with
    * source: `up://origin-authority/origin-entity/origin-version/origin-resource.instance#message`
    * sink: `-`

2. `UTransport.send` maps source (**origin UUri**) to Zenoh key
    * local (w/o origin-authority): `upl/` + `origin-resource-id + origin-entity-id + origin-version`
    * remote (with origin-authority): `upr/` + `origin-authority-id/` + `origin-resource-id + origin-entity-id + origin-version`

3. Subscriber registers a listener on **origin UUri**
    * `up://origin-authority/origin-entity/origin-version/origin-resource.instance#message`

4. which `UTransport.registerListener` maps to Zenoh key
    * local (w/o origin-authority): `upl/` + `origin-resource-id + origin-entity-id + origin-version`
    * remote (with origin-authority): `upr/` + `origin-authority-id/` + `origin-resource-id + origin-entity-id + origin-version`

5. Since this is **Publish URI**, `Zenoh subscriber` will be used to bind the `registerListener`

==== Transfer Notification message

1. A uEntity (`origin-authority/origin-entity`) creates a message with
    * source: `up://origin-authority/origin-entity/origin-version/origin-resource.instance`
    * sink: `up://dest-authority/dest-entity/dest-version/dest-resource.instance`

2. `UTransport.send` maps sink (**destination UUri**) to Zenoh key
    * local (w/o dest-authority): `upl/` + `dest-resource-id + dest-entity-id + dest-version`
    * remote (with dest-authority): `upr/` + `dest-authority-id/` + `dest-resource-id + dest-entity-id + dest-version`

3. Receiver (dest-authority/dest-entity) registers a listener on **destination UUri**
    * `up://dest-authority/dest-entity/dest-version/dest-resource.instance`

4. which `UTransport.registerListener` maps to Zenoh key
    * local (w/o dest-authority): `upl/` + `dest-resource-id + dest-entity-id + dest-version`
    * remote (with dest-authority): `upr/` + `dest-authority-id/` + `dest-resource-id + dest-entity-id + dest-version`

5. Since this is **Notification URI**, `Zenoh subscriber` will be used to bind the `registerListener`

==== Transfer Request message

1. Service consumer (`consumer-authority/consumer-entity`) creates a message with
    * source: `up://consumer-authority/consumer-entity/consumer-version/rpc.response`
    * sink: `up://provider-authority/provider-entity/provider-version/rpc.methodname`

2. `UTransport.send` maps sink (**destination UUri**) to Zenoh key
    * local (w/o provider-authority): `upl/` + `provider-resource-id(> [METHOD_ID_RANGE]) + provider-entity-id + provider-version`
    * remote (with provider-authority): `upr/` + `provider-authority-id/` + `provider-resource-id(> [METHOD_ID_RANGE]) + provider-entity-id + provider-version`

3. Service provider (provider-authority/provider-entity) registers a listener on **destination UUri**
    * `up://provider-authority/provider-entity/provider-version/rpc.methodname`

4. which `UTransport.registerListener` maps to Zenoh key
    * local (w/o provider-authority): `upl/` + `provider-resource-id(> [METHOD_ID_RANGE]) + provider-entity-id + provider-version`
    * remote (with provider-authority): `upr/` + `provider-authority-id/` + `provider-resource-id(> [METHOD_ID_RANGE]) + provider-entity-id + provider-version`

5. Since this is **Request URI**, `Zenoh queryable` will be used to bind the `registerListener`

==== Transfer Response message

The way to transfer Response message is different from others, because Zenoh can reply the message with its own mechanism and doesn't need to map the UUri to another Zenoh key.

1. Service provider receives a Request message with `Zenoh queryable`, and it can store this query with `UAttributes.id`.

2. `UTransport.send` will retrieve the specific query by comparing the `UAttributes.reqid`, and then send back the message with that query.

3. There are two ways for service consumer to receive the response message:
    * Using `invoke_method`:
        - After sending query with `Zenoh get`, we can receive the reply by using `recv()`.
    * Using `register_listener`:
        - Service consumer (consumer-authority/consumer-entity) registers a listener on **Response UUri** (`up://consumer-authority/consumer-entity/consumer-version/rpc.response`)
        - While the request is sent by `UTransport.send`, the listener will be registered in `Zenoh get` and triggered if receiving the response message.

==== Message routing

1. A streamer that is interested in all incoming messages for dest-authority registers a listener for
    * `up://dest-authority////`

2. which `UTransport.registerListener` maps to Zenoh key
    * `upr/` + `dest-authority-id/` + `**`
