= RpcClient Interface
:toc:
:sectnums:

The key words "*MUST*", "*MUST NOT*", "*REQUIRED*", "*SHALL*", "*SHALL NOT*", "*SHOULD*", "*SHOULD NOT*", "*RECOMMENDED*", "*MAY*", and "*OPTIONAL*" in this document are to be interpreted as described in https://www.rfc-editor.org/info/bcp14[IETF BCP14 (RFC2119 & RFC8174)]

----
SPDX-FileCopyrightText: 2023 Contributors to the Eclipse Foundation

See the NOTICE file(s) distributed with this work for additional
information regarding copyright ownership.

This program and the accompanying materials are made available under
the terms of the Apache License Version 2.0 which is available at
https://www.apache.org/licenses/LICENSE-2.0
 
SPDX-FileType: DOCUMENTATION
SPDX-License-Identifier: Apache-2.0
----

== Overview

`RpcClient` defines a common, language specific interface for method invocation to allow the auto-generation of client-side & server-side code per-language (SDK) in lieu of per platform. 

.API Definition Terminology
[width="80%",cols="20%,80%"]
|===
|Term | Description

| `IN` | Input parameter
| `OUT`| Output parameter
| `&` | Parameter passed by reference
| `?` | Parameter is optional
| `Future<T, E>` | Language specific mechanism to access the result of asynchronous operations, e.g. https://en.cppreference.com/w/cpp/thread/future[`std::future`] for C++, https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/concurrent/CompletableFuture.html[`CompletableFuture`] for Java etc. +
`T` is the type of the operation's successful outcome. `E` is the type of the operation's erroneous outcome.

|===


== Interface

All link:../languages.adoc[language-specific uProtocol libraries] *MUST* declare the `RpcClient` interface with method:

[source]
----
invokeMethod(
  IN method: UUri,
  IN options: CallOptions,
  IN payload: UPayload?,
  OUT result: Future<UMessage, UStatus>
)
----

.Parameters
[#parameters, width="100%",cols="15%,25%,60%"]
|===

| Parameter | Type | Description

| method
| link:../basics/uri.adoc[UUri]
| The URI representing the service method to invoke.

| options
| CallOptions
| Additional meta data to include in the request message.

| payload
| link:../basics/upayload.adoc[UPayload]
| The payload data to include in the request message.

| result
| Future<Void, link:../basics/error_model.adoc[UStatus]>
| A succeeded future containing the response message returned by the service provider. +
A failed future indicating an error that occurred while transmitting the request or response message.
|===


== Implementation

Implementations communicate to their underlining transport through the link:../up-l1/README.adoc#_utransport[uTransport Interface].

* Every link:../upclient.adoc[uPClient library] *MUST* implement the `RpcClient` interface.

* The `UUri` and `CallOptions` passed to `invokeMethod()` *MUST* be cached non-persistent memory per call, this is to be able to complete the `Future` when the response is received from the server.

* The `UPayload` passed to `invokeMethod()` *MAY* be null or empty.

* Method invocation that fails, *MUST* return exceptionally as defined by the link:../basics/error_model.adoc[uProtocol Error Model].

* Cached requests must be completed exceptionally with  `DEADLINE_EXCEEDED` when `UAttributes.isExpired()` is `true`. This notifies the calling context that the request has expired.

* *MUST* return `INVALID_PARAMETER` if `UUri` is null or empty or `CallOptions.priority() < CS4`

* *MUST* return `ALREADY_EXISTS` if the same request already exists (i.e. same `UUri` and `CallOptions`). This is to prevent duplicate requests.

* *MUST* complete future successfully when the response is received from the server.






 
