= RpcClient Interface
:toc:
:sectnums:

The key words "*MUST*", "*MUST NOT*", "*REQUIRED*", "*SHALL*", "*SHALL NOT*", "*SHOULD*", "*SHOULD NOT*", "*RECOMMENDED*", "*MAY*", and "*OPTIONAL*" in this document are to be interpreted as described in https://www.rfc-editor.org/info/bcp14[IETF BCP14 (RFC2119 & RFC8174)]

----
Copyright (c) 2023 General Motors GTO LLC

Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.

SPDX-FileType: DOCUMENTATION
SPDX-FileCopyrightText: 2023 General Motors GTO LLC
SPDX-License-Identifier: Apache-2.0
----

== Overview

RpcClient defines a common, language specific, interface for method invocation to allow the auto-generation of client-side & server-side code per-language (SDK) in lieu of per platform. 

.API Definition Terminology
[width="80%",cols="20%,80%"]
|===
|Term | Description

| `IN` | Input parameter
| `OUT`| Output parameter
| `IN/OUT` | Input/output parameter
| `&` | Parameter passed by reference
| `Future` | Language specific mechanism to access the result of asynchronous operations, ex. https://en.cppreference.com/w/cpp/thread/future[`std::future`] for C++, https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/CompletableFuture.html[`CompletableFuture`] for Java, etc...

|===

NOTE: For more details about the data model used in this interface, please refer to link:../up-l1/README.adoc:_data_model[uP-L1 Data Model].

== Interface

The following are the interface definition and requirements that *MUST* be implemented by all SDKs.

 * Interface *MUST* be called `RpcClient`
 * *MUST* contain the method:

`OUT Futurelink:../up-l1/README.adoc#_upayload[<UPayload>] invokeMethod(IN link:../basic/uuri.adoc[UUri], IN link:../up-l1/README.adoc#_upayload[UPayload], IN link:../up-l1/README.adoc#_uattributes[<UAttributes>])`


== Implementation

RpcClient interface is implemented by each platform APIs, i.e. in the library that also implements uTransport interface. 

 * Every uPlatform client library *MUST* implement the interface.

Implementations communicate to their underlining transport through the link:../up-l1/README.adoc#_utransport[uTransport Interface].

 * The `UUri` and `UAttributes` passed to `invokeMethod()` *MUST* be cached non-persistent memory per call, this is to be able to complete the `Future` when the response is received from the server.

 * Method invocation that fails, *MUST* return exceptionally per link:../basics/error_model.adoc[uProtocol Error Model].

 * Cached requests must be completed exceptionally with  `DEADLINE_EXCEEDED` when the `UAttributes.isExpired()` is true. This notifies the calling context that the request has expired.

 * *MUST* return `INVALID_PARAMETER` for the following errors:
  * `UUri` is null or empty
  * `UAttributes.type() != UMessageType.REQUEST`
  `UAttributesValidator.validate()` fails (i.e. one of the UAttributes is invalid per UAttributesValidator).

* *MUST* return `ALREADY_EXISTS` if the same request already exists (i.e. same `UUri` and `UAttributes`). This is to prevent duplicate requests.

* *MUST* complete future successfully when the response is received from the server.






 
