= RpcServer Interface
:toc:
:sectnums:

The key words "*MUST*", "*MUST NOT*", "*REQUIRED*", "*SHALL*", "*SHALL NOT*", "*SHOULD*", "*SHOULD NOT*", "*RECOMMENDED*", "*MAY*", and "*OPTIONAL*" in this document are to be interpreted as described in https://www.rfc-editor.org/info/bcp14[IETF BCP14 (RFC2119 & RFC8174)]

----
Copyright (c) 2023 General Motors GTO LLC

Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.

SPDX-FileType: DOCUMENTATION
SPDX-FileCopyrightText: 2023 General Motors GTO LLC
SPDX-License-Identifier: Apache-2.0
----

== Overview

RpcServer is the server-side interface for method invocation meaning to provide the ability to register listeners for incoming requests such that they can be handled by services then responded to. The RpcServer interface defines the API that is declared by the various programming languages and implemented by the uPClient libraries.  

.API Definition Terminology
[width="80%",cols="20%,80%"]
|===
|Term | Description

| `IN` | Input parameter
| `OUT`| Output parameter
| `IN/OUT` | Input/output parameter
| `&` | Parameter passed by reference
| `Future` | Language specific mechanism to access the result of asynchronous operations, ex. https://en.cppreference.com/w/cpp/thread/future[`std::future`] for C++, https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/CompletableFuture.html[`CompletableFuture`] for Java, etc...

|===

NOTE: For more details about the data model used in this interface, please refer to link:../up-l1/README.adoc:_data_model[uP-L1 Data Model].

== Interface

The following are the interface definition and requirements that *MUST* be implemented by all SDKs.

 * Interface *MUST* be called `RpcServer`

=== RegisterRpcListener()

Register a listener for a particular method URI to be notified when requests are sent against said method

API Signature: 

`OUT UStatus registerRpcListener(IN UUri&, IN URpcListener&)`


 * *MUST* support registering only one listener per method URI
 * *MUST* support registering more than one topic per listener
 

==== Parameters
.RegisterListener Parameters
[width="100%",cols="20%,80%"]
|===
|Parameter | Description

| UUri
| Topic to register the listener for

| URpcListener
| Listener to be registered

|===


=== UnregisterRpcListener()

Unregister an RPC listener for a given method Uri. Messages arriving on this topic will no longer be processed by this listener.

API Signature: 

`OUT UStatus unregisterListener(IN UUri, IN URpcListener&)`

==== Parameters
.UnregisterListener Parameters
[width="70%",cols="20%,80%"]
|===
|Parameter | Description

| UUri
| Topic to unregister the listener for

| URpcListener
| Listener to be unregistered

|===







 
