@startuml
'https://plantuml.com/sequence-diagram

' SPDX-FileCopyrightText: 2023 Contributors to the Eclipse Foundation
'
' See the NOTICE file(s) distributed with this work for additional
' information regarding copyright ownership.
' 
' This program and the accompanying materials are made available under
' the terms of the Apache License Version 2.0 which is available at
' https://www.apache.org/licenses/LICENSE-2.0
'
' SPDX-FileType: SOURCE
' SPDX-License-Identifier: Apache-2.0

autonumber

box Device2 #white
	actor uApp #red
	entity uSubscription as SM1 #brown
end box
box Device1 #white
	entity uSubscription as SM2 #brown
	entity uExample #blue
end box

uApp -> SM1: Subscribe(SubscriptionRequest)
note right
 	<size:12>**SubscriptionRequest:**</size> 
	""topic:"" { ""uri"": ""//topic//"" }  
	""subscriber"": { ""uri"": "up://Device2/uApp/" }
	""attributes"": { //Subscription Attributes// }
end note
SM1 --> uApp: SubscriptionResponse
note right
	<size:12>**SubscriptionResponse:**</size> 
	""status:"" { 
		\t""state"": ""SUBSCRIBE_PENDING"",
		\t""code"": ""OK""
	}
	""config:"" { //Platform specific config// }
end note
|||
opt 1st Subscription
	SM1 -> SM2: Subscribe(SubscriptionRequest)
	note right
		<size:12>**SubscriptionRequest:**</size> 
		""topic:"" { ""uri"": ""//topic//"" }  
		""subscriber"": { ""uri"": "up://Device2/core.usubscription/" }
		""attributes"": { //Subscription Attributes// }
	end note
 |||
	alt Success
		SM2 --> SM1: SubscriptionResponse
		note right
			<size:12>**SubscriptionResponse:**</size> 
			""status:"" {
				\t""state"": ""SUBSCRIBED"", 
				\t""code"": ""OK""
			}
			""config:"" { //Platform specific config// }
		end note

		SM2 -[#0000FF]-\ uExample: <font color=blue>Update</font>
		note right
			<size:12>**Update:**</size>
			""topic:"" { ""uri"": ""//topic//"" }
			""subscriber"": { ""uri"": "up://Device2/core.usubscription/" }
			""status:"" {
				\t""state"": ""SUBSCRIBED"", 
				\t""code"": ""OK"" 
			}
 			""attributes"": { //Subscription Attributes// }
	    end note

 		SM1 -[#0000FF]-\ uApp: <font color=blue>Update</font>
 		note right
			<size:12>**Update:**</size>
			""topic:"" { ""uri"": ""//topic//"" }
			""subscriber"": { ""uri"": "up://Device2/uApp/" }
			""status:"" {
				\t""state"": ""SUBSCRIBED"",
				\t""code"": ""OK""
			}
			""attributes"": { //Subscription Attributes// } 
		end note
 |||

	else Failure
		SM2 --> SM1: SubscriptionResponse
	 	note right
			<size:12>**SubscriptionResponse:**</size> 
			""status:"" { 
				\t""state"": ""UNSUBSCRIBED"", 
				\t""code"": ""INVALID_ARGUMENT | NOT_FOUND | PERMISSION_DENIED""
			}
		end note

 		SM1 -[#0000FF]-\ uApp: <font color=blue>Update</font> 
 		note right
			<size:12>**Update:**</size>
			""topic:"" { ""uri"": ""//topic//"" }
			""subscriber"": { ""uri"": "up://Device2/uApp/" }
 			""status:"" { 
				\t""state"": ""UNSUBSCRIBED"", 
				\t""code"": ""INVALID_ARGUMENT | NOT_FOUND | PERMISSION_DENIED""
			}
 			""attributes"": { //Subscription Attributes// } 
	end note
	end alt
end opt
@enduml