= uProtocol Messages
:toc:
:sectnums:

The key words "*MUST*", "*MUST NOT*", "*REQUIRED*", "*SHALL*", "*SHALL NOT*", "*SHOULD*", "*SHOULD NOT*", "*RECOMMENDED*", "*MAY*", and "*OPTIONAL*" in this document are to be interpreted as described in https://www.rfc-editor.org/info/bcp14[IETF BCP14 (RFC2119 & RFC8174)]

----
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
----

uProtocol leverages https://cloudevents.io/[CNCF CloudEvents (CE)] as _the_ way of describing the messages in a common way. For more information on CloudEvents please visit link:../../basics/cloudevents.adoc[CloudEvents Overview] section.

Messages types are used to differentiate the architecture pattern used by uEs (RPC, publish, notification) when communicating with each other as different patterns require different attributes.
Table <<message-types>> below list the defined event types with links to their versions.

.Message Types
[width=100%",cols="20%,15%,65%"]
[#message-types]
|===
|Event Type |Version |Details

|*Publish*
| link:v1/README.adoc[v1]
|Publication of events (1:many)

|*Notification*
| link:v1/README.adoc[v1]
|Published event to a specific destination (1:1)

|*Request*
| link:v1/README.adoc[v1]
|RPC Request message

|*Response*
| link:v1/README.adoc[v1]
|RPC Response Message

|===
