# ********************************************************************************
#  Copyright (c) 2025 Contributors to the Eclipse Foundation
#
#  See the NOTICE file(s) distributed with this work for additional
#  information regarding copyright ownership.
#
#  This program and the accompanying materials are made available under the
#  terms of the Apache License Version 2.0 which is available at
#  https://www.apache.org/licenses/LICENSE-2.0
#
#  SPDX-License-Identifier: Apache-2.0
# *******************************************************************************/

name: Lint Gherkin Features

on:
  workflow_dispatch:
  pull_request:
    paths:
      - '**/*.feature'

jobs:
  lint-gherkin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: install gherklin
        run: |
          npm install -D gherklin
          npm install -D tsx

      - name: lint feature files
        run: |
          npx tsx ./node_modules/.bin/gherklin
